### ISSUE TITLE
BigRQuery fails on invocation from kernel_gateway POST

### ISSUE THREAD

**Issue by Praxiteles** [r-dbi/bigrquery#160]
When running R code directly in a notebook using a set_service_token(path) command - notebooks are able to access Google BigQuery. 

However, when a kernal_gateway post is made to a notebook, that same code returns an "Invalid Credentials" error. 

Here is sample failing code: 

```
# POST /test
library(httr)
library('bigrquery')
setwd("/home/jovyan/work")
path <- "server_key.json"
set_service_token(path)
sql <- "SELECT year, month, day, weight_pounds FROM [publicdata:samples.natality] LIMIT 5"
query_exec(sql, project = "your-googlebq-project-name")
```

**Comment by hadley** [comment]
What is a "kernal_gateway" post?

**Comment by Praxiteles** [comment]
Kernel Gateway allows notebook cells to be started and run by typing a URL into a web browser (i.e. A web services "GET" - as opposed to a "POST")
[https://github.com/jupyter/kernel_gateway](https://github.com/jupyter/kernel_gateway)

Here is quick overview from IBM: [http://blog.ibmjstart.net/2016/01/28/jupyter-notebooks-as-restful-microservices/](http://blog.ibmjstart.net/2016/01/28/jupyter-notebooks-as-restful-microservices/)

Kernel gateway also allows cells to be started and run through a web POST command. In the example above, we configured the cell to receive a POST at a url ending "/test". (The POST configuration allows data from a web form to get posted to this cell. The Jupyter cell then would then respond with the results.)

We can give you access to our environment if it helps.

**Comment by hadley** [comment]
Have you checked that the working directory is as you expect?

**Comment by Praxiteles** [comment]
Yes - if we run this command in our cell: 
           `print(list.files(all.files=TRUE))` 
...then we can see the file in the listed directory:
 
[1] "set path successfully."
 [1] "."                               ".."                             
 [3] "all_df.pickle"                   "Big query connection on R.ipynb"
 [5] "df.pickle"                       "healthlabs4"                    
 [7] ".ipynb_checkpoints"              "michael2.ipynb"                 
 [9] "michael9100.ipynb"               "pydatalab"                      
[11] "random_forest.p"                 "scotch_api_julia.ipynb"         
[13] "scotch_api_r.ipynb"              "server_key.json"      <===============Here it is             
[15] "Untitled-Copy1.ipynb"            "Untitled.ipynb"                 
[17] "y.pickle"                       

Yet, as soon as the code hits the query_exec command we get this error as a response to our HTTP POST to the Jupyter cell: 
`Error ERROR: Error: Invalid Credentials
`

Our code runs fine if we run it from the notebook. It just when we use Kernel Gateway so the cell is invoked by a web call that BigRQuery seems to lose its access to the credentials. 

Any idea why or how BigRQuery might be losing its access to the credentials when invoked by Kernel Gateway?

**Comment by krlmlr** [comment]
Would #167 resolve this problem?

**Comment by hadley** [comment]
This seems like to be an issue with kernel gateways which unfortunately I don't know anything about.
