### ISSUE TITLE
HTTP2 stream error:  bigrquery commands error in R studio on Windows 10, but not in Base R

### ISSUE THREAD

**Issue by aumdavis** [r-dbi/bigrquery#165]
I have several programs written in R that use bigrquery to run queries, table deletes, and upload data.  These were all written in R studio with R version 3.3.1 on a windows 7 machine.  No issues at all running them over and over.

A new hire is trying to run the same exact programs on Windows 10.  Same version of base R and R studio.  The packages all install fine and there are no errors of any kind.  But commands sent to bigquery through the code (i.e., query_exec, insert_upload_job) will submit, but they hang for several minutes, then return the following error:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Stream error in the HTTP/2 framing layer

These queries run in 2 seconds normally.  These commands run fast in base R on the same machine with no errors.

I have a Windows 10 laptop at home so I installed everything the same way, and it is displaying the same behavior.  The commands run fine in base R but "hang" in R studio for several minutes before returning the error above.

What is weird is that periodically the same commands run fine in R studio, but most of the time we get the error.

I looked for this issue and found:
https://github.com/r-hub/rhub/issues/32

But I am not able to figure out how to turn off http2 on the client side to see if that would help.

Any help is appreciated!

**Comment by aumdavis** [comment]
One thing I noticed is that when I check the curl version with:
curl::curl_version()
It shows version 7.47.1 on my Windows 7 machine (the one that works) and does it does not show an http2 value.

On the Windows 10 machine, it shows curl version 7.53.1, and shows an http2=TRUE parameter.

I haven't been able to figure out how to deprecate the version of curl on the Win10 machine to see if that would fix the issue.

In any case, I would think if it's an issue with the latest version that other folks would be having the same issue.

**Comment by aumdavis** [comment]
I created a workaround by doing the following steps: 
1. Removed the curl folder in my base R win-library subfolder (when I tried installing an older version of curl it wasn't able to automatically remove the current version) 
2. Install curl version 0.9.7 (this version does NOT use http2) install.packages("https://cloud.r-project.org/bin/windows/contrib/3.1/curl_0.9.7.zip",repos=NULL,type="source")

run curl::curl_version() to confirm no http2 parameter

Hopefully someone can help me figure out how to get bigrquery to work with the most recent version of curl, as I'm afraid deprecating my curl version isn't a good long term solution.

**Comment by aumdavis** [comment]
On stackoverflow, a user posted the following comment which could be helpful.  I wasn't able to figure out  how to access the handle in bigrquery but perhaps there is a way?  In any case, getting http/2 to work with bigrquery will be a helpful fix.

curl:: handle_setopt() lets you set curl handle options. You're looking to ensure http_version is set to 2 which maps to CURL_HTTP_VERSION_1_1 in the cURL library. However, I don't use bigquery enough to know how to get that handle passed into it for ops. – hrbrmstr

**Comment by hadley** [comment]
This seems like more of a curl problem than a bigquery problem

@jeroen any ideas why curl would try and default to http2?

**Comment by jeroen** [comment]
http/2 is always preferred when supported by both client and server. You can disable it using `handle_setopt(http_version = 2)` (2 is the value for `CURL_HTTP_VERSION_1_1`).

I am considering disabling http/2 altogether because it is broken for so many google services :/

**Comment by jeroen** [comment]
Actually @aumdavis could you try to install the dev version of `curl` to test if this changes anything?

```r
install.packages("https://github.com/jeroen/curl/archive/master.tar.gz", repos = NULL)

```

**Comment by aumdavis** [comment]
Sure I'll try it and report back.

**Comment by jeroen** [comment]
@hadley you can reproduce such problems by building `curl` with HTTP/2 support. I kind of recommend that you do because it is almost impossible to avoid these days.

```
brew reinstall curl --with-nghttp2
brew link --force curl
```

And then

```
install.packages("https://github.com/jeroen/curl/archive/master.tar.gz", repos = NULL)
```

And then check `curl::curl_version()` to see if http2 is enabled now.

**Comment by hadley** [comment]
@jeroen thanks!

@craigcitro any ideas why http/2 is a problem with bigquery?

**Comment by jeroen** [comment]
This error often appears when the server is advertising HTTP/2 support, however there is an older intermediate reverse proxy (usually nginx) that doesn't fully support HTTP/2. So the client and server negotiate an update to HTTP/2 but the proxy breaks things.

Browsers deal with this somewhat more gracefully than `libcurl` unfortunately. Some references:

 - https://github.com/curl/curl/issues/1040
 - https://github.com/curl/curl/issues/1587

**Comment by craigcitro** [comment]
I don't know any reason BQ would report supporting HTTP/2 and then fail to actually stream. I'm OOO today, but if someone can give me a quick repro, I'll get a bug filed and report back.

**Comment by aumdavis** [comment]
@jeroen I tried to install curl from your link but it's not working.  I made sure that curl and devtools were not loaded as you requested.

> install.packages("https://github.com/jeroen/curl/archive/master.tar.gz", repos = NULL)
Installing package into ‘C:/Users/Mark/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://github.com/jeroen/curl/archive/master.tar.gz'
Content type 'application/x-gzip' length 82633 bytes (80 KB)
downloaded 80 KB

Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package 'curl' ...
Warning: running command 'sh ./configure.win' had status 127
ERROR: configuration failed for package 'curl'
* removing 'C:/Users/Mark/Documents/R/win-library/3.2/curl'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.5/bin/x64/R" CMD INSTALL -l "C:\Users\Mark\Documents\R\win-library\3.2" "C:/Users/Mark/AppData/Local/Temp/Rtmp8oiyxC/downloaded_packages/master.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/Mark/AppData/Local/Temp/Rtmp8oiyxC/downloaded_packages/master.tar.gz’ had non-zero exit status

**Comment by jeroen** [comment]
@aumdavis you are running a very old version of R (3.2). Please install [R 3.4.0](https://cran.r-project.org/bin/windows/base/) and [Rtools34.exe](https://cran.r-project.org/bin/windows/Rtools/) and try again.

**Comment by aumdavis** [comment]
OK I updated the versions and it installed properly.

However, I am still getting the same error with this version of curl:
> job <- insert_upload_job(project, dataset, "client_upcs_string", upcs)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Stream error in the HTTP/2 framing layer

The same error occurs for query_exec commands, but does not seem to happen for delete_table commands.

**Comment by TerryZhangHL** [comment]
any luck with this issue? I have the same error.

**Comment by aumdavis** [comment]
Terry:

I can get around it by deprecating my version of curl, but obviously that is not ideal.  Until someone fixes this issue I don't know of any other solution.

Steps to depricate curl version:
1...Remove current version of curl by deleting curl folder in:
c:\users\...\documents\R\win-library\3.4\

2.  Install curl version 0.9.7 (this version does NOT use http2)
install.packages("https://cloud.r-project.org/bin/windows/contrib/3.1/curl_0.9.7.zip",repos=NULL,type="source")

3.  run curl::curl_version() to confirm no http2 parameter

**Comment by TerryZhangHL** [comment]
thanks @aumdavis 
it worked!

**Comment by jeroen** [comment]
Did you run the latest version of curl? It should nog have this issue.

**Comment by aumdavis** [comment]
Thanks jeroen!  I just tested the latest version of curl 2.8.1 and it worked perfectly.

I also noticed in the curl_version() log that http2 is now set to FALSE.

Back in business!

**Comment by analyse9823** [comment]
Dancing around the issue that still alive.
Getting:
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  gnutls_handshake() failed: An unexpected TLS packet was received.
```
when using cronR for scheduling the bigrquery scripts to upload data to BQ.
Tried:
```
handle <- new_handle()
handle_setopt(handle, http_version = 0L)
```
but it's not working at all.
The `curl_version()` is still having HTTP2 enabled:
```
$version
[1] "7.58.0"

$ssl_version
[1] "GnuTLS/3.5.18"

$libz_version
[1] "1.2.11"

$libssh_version
[1] NA

$libidn_version
[1] "2.0.4"

$host
[1] "x86_64-pc-linux-gnu"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps"  "ldap"   "ldaps"  "pop3"   "pop3s"  "rtmp"   "rtsp"   "smb"    "smbs"  
[18] "smtp"   "smtps"  "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] TRUE

$idn
[1] TRUE
```
Running VM instance from GCP.

Any help much appreciated.

**Comment by jeroen** [comment]
Can you try with `handle_setopt(handle, http_version = 2)` (which will use HTTP 1.1), see the vignette chapter on http/2: https://cran.r-project.org/web/packages/curl/vignettes/intro.html#disabling_http2

**Comment by jeroen** [comment]
Alternatively you can `apt-get install libcurl4-openssl-dev` and then reinstall the curl R package.

**Comment by analyse9823** [comment]
Sure - I've tried that too. Same results

**Comment by analyse9823** [comment]
`apt-get install libcurl4-openssl-dev` - tried. Same as before - didn't help.

**Comment by jeroen** [comment]
Did you reinstall the curl package afterwards? It's impossible you get a `gnutls_handshake` error with the openssl version of libcurl.

**Comment by analyse9823** [comment]
Yes of course.

Strange thing happened - the issue is disappeared yesterday. Get no idea on why. Will look forward for a while.

**Comment by mahdiarsadeghi** [comment]
Any idea how your problem disappeared? I get this error time to time. Working with R on GCP. Here is my curl version: 

`$version
'7.58.0'
$ssl_version
'GnuTLS/3.5.18'
$libz_version
'1.2.11'
$libssh_version
NA
$libidn_version
'2.0.4'
$host
'x86_64-pc-linux-gnu'
$protocols
'dict' 'file' 'ftp' 'ftps' 'gopher' 'http' 'https' 'imap' 'imaps' 'ldap' 'ldaps' 'pop3' 'pop3s' 'rtmp' 'rtsp' 'smb' 'smbs' 'smtp' 'smtps' 'telnet' 'tftp'
$ipv6
TRUE
$http2
TRUE
$idn
TRUE`

**Comment by valentas-kurauskas** [comment]
This workaround worked for me: https://github.com/cloudyr/googleCloudStorageR/issues/71#issuecomment-332781571
