### ISSUE TITLE
Use auth from gargle

### ISSUE THREAD

**Issue by hadley** [r-dbi/bigrquery#167]
To support wider variety of methods.

**Comment by jpvelez** [comment]
Hi there! Just wanted to check in on the status of this issue.

**Comment by hadley** [comment]
And user agent helper #245

**Comment by craigcitro** [comment]
Because some folks were asking: my understanding is that Jenny is tackling some googlesheets4 work; once that's done, she'll tackle gargle, and then integrate it into this library.

**Comment by craigcitro** [comment]
Also, here "gargle" means https://github.com/r-lib/gargle

**Comment by hadley** [comment]
Also library means package 😛

**Comment by ZainRizvi** [comment]
Hi, is there any progress on this? I see there is an orphaned pull request by @jennybc from three months ago that would fix this issue.

Thanks

**Comment by jennybc** [comment]
gargle has been submitted to CRAN 4 times in the last 10 days and keeps getting held up, despite passing all checks. Once this blocker is resolved, then, yes, gargle can be used for auth here and it should handle the GCE scenario.

**Comment by ZainRizvi** [comment]
Gotcha, thanks for the context and thank you for making this much needed fix @jennybc! Looking forward to see it live :)

**Comment by alokpattani** [comment]
Hi there, I work with @ZainRizvi at Google and wanted to +1 the desire for an improved auth experience in BigRQuery, which it looks like gargle will enable.

For greater context, I'm hoping to advocate for the use of R with Google Cloud Platform, and having an improved workflow for this piece will go a long way to that end. Looking forward to any updates you can share, and really appreciate the work!

**Comment by jennybc** [comment]
CRAN continues to be the problem. I know of no obstacles at this point. gargle is just sitting there. 5 resubmissions so far and 3 weeks and lots of email 😬 I'm doing everything I know to do.
