### ISSUE TITLE
return empty table with no-result query

### ISSUE THREAD

**Issue by TerryZhangHL** [r-dbi/bigrquery#171]
Hi,

first thanks for creating this amazing package. When I used version 0.3.0, i was able to get an empty table from no result query (Query returned zero records). However, when i used latest version in CRAN 0.4.1, it will return an error: Error: x > 0 is not TRUE

Do you have any suggestions?

Thanks

**Comment by EricGoldsmith** [comment]
Can confirm that the case of no results is not being handled properly.

According to a traceback:
```
Error: x > 0 is not TRUE 
11. stop(sprintf(ngettext(length(r), "%s is not TRUE", "%s are not all TRUE"), 
    ch), call. = FALSE, domain = NA) 
10. stopifnot(x > 0) 
9. assert_positive_scalar(total) 
8. pb_init(self, private, format, total, width, stream, complete, 
    incomplete, callback, clear, show_after, force) 
7. .subset2(public_bind_env, "initialize")(...) 
6. progress::progress_bar$new(..., show_after = delay) 
5. bq_progress("Retrieving data [:bar] :percent eta: :eta", total = pages, 
    quiet = quiet) 
4. list_tabledata_callback(project, dataset, table, append_rows, 
    table_info = table_info, page_size = page_size, max_pages = max_pages, 
    warn = warn, quiet = quiet) 
3. list_tabledata(dest$projectId, dest$datasetId, dest$tableId, 
    page_size = page_size, max_pages = max_pages, warn = warn, 
    quiet = quiet) 
2. query_exec(sql, project = bqProject, quiet = TRUE) 
1. getBQWatchHistory(fromDate, toDate, userId = 7146486) 
```

The culprit appears to be that an assertion within the progress_bar function expects the `total` value to be > 0. When it's = 0 (i.e. no results), execution is halted.

The suspect code in [here](https://github.com/rstats-db/bigrquery/blob/master/R/tabledata.r#L80-L85), and needs to handle the case of no results before setting up a progress bar.

**Comment by EricGoldsmith** [comment]
Here's a fix:

In the case of no query results (i.e. `pages == 0`), satisfy the `progress_bar` asseration that `total > 0`

![screenshot 2017-09-01 18 09 34](https://user-images.githubusercontent.com/3375152/29989413-bcb68dbe-8f40-11e7-8341-ef0cc47fb0c9.png)

**Comment by byapparov** [comment]
@EricGoldsmith than you for solution, it fixes the problem.

**Comment by JesseCastro** [comment]
I still get this error with the latest build from github.  Loading the script as follows: 
`devtools::install_github("r-dbi/bigrquery")`
And doing any query that returns zero rows.
