### ISSUE TITLE
SQL chunk output does not get saved into variable when knitting

### ISSUE THREAD

**Issue by bulam** [r-dbi/bigrquery#181]
When I use a BigQuery SQL chunk in an Rmarkdown document and save the output to a variable, it works properly only in an interactive mode. When I try to knit, the output from the SQL chunk is not saved. This appears to only happen when using BigQuery in the SQL chunk.
Example:
**Code chunk 1:**
```
{r setup, include=FALSE, warning=FALSE, message=FALSE}
# load necessary libraries
library(bigrquery)
library(knitr)
library(tidyverse)

db <- dbConnect(dbi_driver(), dataset = 'sandbox', project = 'project_id', use_legacy_sql = FALSE)

df <- NULL
```

**Code chunk 2:**
```
{sql, connection=db, output.var=df}
select * from example_dataset
limit 10
```
_returns dataset_

**Code chunk 3:**
```
{r}
head(df)
```
_returns NULL_

**Comment by j450h1** [comment]
I was able to get this working. Perhaps its due to something simple like the fact that you have not put quotes around df like "df"  for the sql chunk?

```{r, echo = FALSE, include=FALSE, warning=FALSE, message=FALSE}
library(bigrquery)
options("httr_oob_default" = TRUE)
project <- "{PROJECT_NAME_HERE}"
db <- dbConnect(dbi_driver(), dataset = 'sandbox', project = project, use_legacy_sql = TRUE)
```

```{sql, connection=db, output.var="df"}
{BQ Query here}
```

```{r}
df
```

**Comment by bulam** [comment]
Thank you for the comment! Yes, I was able to get it to work by adding double quotation marks. Somebody on Stackoverflow pointed that out.
