### ISSUE TITLE
Error: don't know how to convert type record

### ISSUE THREAD

**Issue by ras44** [r-dbi/bigrquery#183]
Using bigrquery with standard sql, I receive the below error when selecting all fields from two or more joined tables:
```
Error: don't know how to convert type record
```

An example that causes the error follows:

```
query_exec("
  WITH first_table AS (
    SELECT 777 AS key, 1 AS x, 2 AS y, 3 AS z
  ),
  second_table  AS (
    SELECT 777 AS key, 4 AS x, 5 AS y, 6 AS z
  )
  SELECT a, b
  FROM first_table AS a
  JOIN second_table AS b 
  ON a.key = b.key",
  project=<YOUR_PROJECT_ID>,
  use_legacy_sql=FALSE)
```

**Comment by byapparov** [comment]
Hi @ras44,

you query is ambiguous in a sense that `a` and `b` are table aliases and though bigquery manages to return results they are structured as records. 

If I change your query a bit to this it works fine:

```sql
WITH first_table AS (
           SELECT 777 AS key, 1 AS x, 2 AS y, 3 AS z
),
           second_table  AS (
           SELECT 777 AS key, 4 AS xx, 5 AS yy, 6 AS zz
           )
           SELECT a.*, b.xx, b.yy, b.zz
           FROM first_table AS a
           JOIN second_table AS b 
           ON a.key = b.key
```

This is not a package issue as it not supposed to flatten the data.

**Comment by ras44** [comment]
@byapparov in many uses cases, it would help to handle the case where GBQ returns records.  With other tools, I am able to convert the json response from the GBQ enpoint into an object, where I can then iterate through repeated records.  With bigrquery, would it be possible to do something similar, and conver the response to a list/object if it contains records?

**Comment by byapparov** [comment]
Well, this is similar to:

https://github.com/r-dbi/bigrquery/issues/168

And the source of the problem will be solved by this:

https://github.com/r-dbi/bigrquery/issues/145

I think it is a duplicate if you agree.

**Comment by ras44** [comment]
Absolutely, thanks for catching that!
