### ISSUE TITLE
Add Support for Parameterized Queries

### ISSUE THREAD

**Issue by JHowix** [r-dbi/bigrquery#191]
Via https://cloud.google.com/bigquery/docs/parameterized-queries#bigquery-query-params-api it is possible through the API to set and use parameters in a query.  It doesn't appear to be possible via the R package.

**Comment by riccardopinosio** [comment]
I second that. I tried today but doesn't seem to be possible as yet. @hadley  is it difficult to implement? I might have a look at it myself at some point.

**Comment by byapparov** [comment]
I see two options in terms of the how parameters argument can be structured:
```R 
# Explicit Type
query_exec(query = "SELECT * FROM orders 
                                    WHERE amount < @max_value AND first_name = @name ", 
                           project = "my-project",
                           parameters = list(max_value = list(type = "INTEGER", value = 10)))

# Implicit Type
query_exec(query = "SELECT * FROM orders 
                                    WHERE amount < @max_value AND first_name = @name ", 
                           project = "my-project",
                           parameters = list(max_value = 10, name = "Bob")))
```

It seems that other places in the package are relying on the implicit typing (which works most of the time). 

I will be happy to write the code for either version, should not be hard. Error handling is the only other unknown for this issue.

**Comment by byapparov** [comment]
There is also an option to use positional parameters (`?`). lets say it is not part of this.

**Comment by byapparov** [comment]
@riccardopinosio I have created PR, have a look.
