### ISSUE TITLE
Rows get swapped in BigQuery when using insert_upload_job()

### ISSUE THREAD

**Issue by c3212218** [r-dbi/bigrquery#193]
Hi,

I am not sure if I am the only one facing the issue but when I use **_insert_upload_job()_** to insert the data to BigQuery, the rows in the table within BigQuery get swapped for some reason.

There is no specific pattern I could found in the row swapping. Anyone else had similar issue?

Thanks

**Comment by mrizwanbashir** [comment]
Sorry about that, I believe that is not an issue. I had the same problem when pushing or importing data to BigQuery from other sources including Google Cloud Storage. This is how BigQuery works with data stored in no natural sequence.

**Comment by c3212218** [comment]
This is not an issue. BigQuery stores the data in no natural sequence.
