### ISSUE TITLE
Issue with R oath Verification

### ISSUE THREAD

**Issue by vivshume** [r-dbi/bigrquery#194]
Hi , 
I am facing issue with R Oath verification.When I am trying to  run the query, It is going on the browser and says "Error: invalid_request". How to fix it ?

**Comment by minimaxir** [comment]
Hitting this issue as well.

```
Error: invalid_request

Missing required parameter: redirect_uri
```

**Comment by j450h1** [comment]
There is a workaround for this, run this before authenticating/making a call:

```options("httr_oob_default" = TRUE)```

See issue [182](https://github.com/r-dbi/bigrquery/issues/182) for more details.

**Comment by hadley** [comment]
Duplicate of #182
