### ISSUE TITLE
Travis setup broken

### ISSUE THREAD

**Issue by haavardw** [r-dbi/bigrquery#196]
The Travis tests fails as there's no keys available. 

Example from the log at https://travis-ci.org/r-dbi/bigrquery/jobs/328963609:

> Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

...

> $ openssl aes-256-cbc -K $encrypted_95be9bef5db7_key -iv $encrypted_95be9bef5db7_iv -in tests/testthat/service-token.json.enc -out ~/.bigrquery-token.json -d
iv undefined
The command "openssl aes-256-cbc -K $encrypted_95be9bef5db7_key -iv $encrypted_95be9bef5db7_iv -in tests/testthat/service-token.json.enc -out ~/.bigrquery-token.json -d" failed and exited with 1 during .

**Comment by byapparov** [comment]
Any ideas how we can move forward with this?

**Comment by byapparov** [comment]
I have moved `bigrquery-examples` hardcoded project name into environment variable here: https://github.com/byapparov/bigrquery/pull/7

It is not exactly the solution to this issue, but can be useful for someone who wants to test bigquery package locally or in their own CI. 

With that change I have managed to see the green ticks for all tests except DBI.

**Comment by hadley** [comment]
Should only try and decrypt that file if the env vars are present; then `skip_if_no_auth()` should catch the rest.
