### ISSUE TITLE
? could you check, please

### ISSUE THREAD

**Issue by VictArt** [r-dbi/bigrquery#200]
https://github.com/r-dbi/bigrquery/blob/192d9423cd6a01d064e9320db3e57658b3262ed0/R/tables.r#L184

**Comment by VictArt** [comment]
bq_post(url, body = bq_body(body, ...)) - copy_table works well with this

**Comment by byapparov** [comment]
It is a bug. can you make a PR?

**Comment by byapparov** [comment]
I need it fixed my self, here is the PR#208

**Comment by hadley** [comment]
Duplicate of #172
