### ISSUE TITLE
In CI jobs I would like to create tables from schemas defined in files

### ISSUE THREAD

**Issue by byapparov** [r-dbi/bigrquery#204]
Currently the only way to create a table with fields seems to be uploading data, which causes problems as field types are assigned implicitly based on types in R. 

There is a `insert_table` function which allows to create empty table without fields. Not sure what is the use case for that. It would be great if we were able to define table with fields.

**Comment by VictArt** [comment]
Did you try this?
insert_upload_job(your_project,
                                dataset_name,
                                table_name,
                                file,
                                create_disposition = "CREATE_IF_NEEDED",
                                schema = read_json('given_schema.json'))
this works great with files <= 10MB

**Comment by byapparov** [comment]
What if I need to create an empty time partitioned table?

**Comment by byapparov** [comment]
Also looking at the code of insert_upload_job it is not obvious that schema passed in `schema` parameter will not be overridden by  `schema_fields(values)`

**Comment by VictArt** [comment]
Hmm, `schema = schema_fields(values)` it just a predefined parameter in `config` which will be
changed by explicitly specified argument in `insert_upload_job(schema = read_json('given_schema.json'), ...)`. Looks obvious, as for me.

**Comment by VictArt** [comment]
Yes, you are right - `schema_fields(values)` will override argument `schema` of function `insert_upload_job`. I was wrong.
Looks like `schema = schema` in `config` list will be better

**Comment by byapparov** [comment]
Have a look at PR #203, I intend to use in our workflow asap.
