### ISSUE TITLE
responseTooLarge reason is not output in R/request.r::signal_reason()

### ISSUE THREAD

**Issue by ras44** [r-dbi/bigrquery#209]
When querying a table that contains many fields, I will occasionally receive the ambiguous output:

`Internal Error`

An example:
```
  SELECT *
      FROM `bigquery-public-data.samples.github_timeline`
```

The issue occurs in `R/request.r`: results are retrieved from `bq_get`, which calls httr `GET` and finally `process_request`.  The error that arises from `process_request` is passed to `R/request.r::signal_reason`, which signals a condition, but since this condition isn't handled, `signal_reason` ends with:
```
stop(message, call. = FALSE)
```

Unfortunately, the `message` output is uninformative, it only contains "Internal Error".  Helpful information is contained in `reason`.  In this case, it contains  `responseTooLarge`.

This specific issue can be solved by reducing the page_size argument, however my point is that `reason` contains additional information that is useful for troubleshooting.  Outputting `reason` and not just `message` in `R/request::signal_reason.r` would be helpful.

Another option is to handle the bigrquery_responseTooLarge class condition that is signaled, perhaps with a message recommending a smaller page_size argument.

**Comment by hadley** [comment]
Do you want to turn this into a PR? It would be helpful to include a link to the error API docs in a comment.
