### ISSUE TITLE
Add option to run query with batch priority

### ISSUE THREAD

**Issue by byapparov** [r-dbi/bigrquery#212]
I am referring to ‘query.priority’ setting here:
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.query.priority

**Comment by hadley** [comment]
https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines

**Comment by byapparov** [comment]
I am referring to ‘query.priority’ setting here:
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.query.priority

>> configuration.query.priority
>> [Optional] Specifies a priority for the query. Possible values include INTERACTIVE and BATCH. The default value is INTERACTIVE.
