### ISSUE TITLE
Fail to create tbl using arbitrary sql

### ISSUE THREAD

**Issue by hadley** [r-dbi/bigrquery#218]
```
library(dplyr, warn.conflicts = FALSE)
library(bigrquery)

con_us <- DBI::dbConnect(
  dbi_driver(),
  project = "bigquery-public-data",
  dataset = "utility_us",
  billing = "profound-ranger-99202"
)

x <- tbl(con_us, sql("SELECT * FROM utility_eu.country_code_iso"))
```

(Part of #101)

**Comment by czeildi** [comment]
I am not sure if you are already aware of this but the issue now is that `db_query_fields.BigQueryConnection` in `dplyr.r` calls `get_table` with `sql` as 3rd parameter while `get_table` expects a table name.

**Comment by hadley** [comment]
I think fixing this requires a change to dbplyr. Currently `tbl()` calls `dplyr:::tbl.DBIConnection` which calls `dbplyr::src_dbi()`. `src_dbi()` is not currently generic, so there's no way for bigrquery to insert correct behaviour.

**Comment by hadley** [comment]
@czeildi nope, I was wrong and your analysis was correct 😄
