### ISSUE TITLE
FR: provide one function for query + wait + download

### ISSUE THREAD

**Issue by czeildi** [r-dbi/bigrquery#239]
as far as I understand not counting deprecated functions you can only download the result of a query in two steps: first call `bq_project_query` and than `bq_table_download` I believe these two after each other are such a common case that it would be worth to offer a shortcut

previously `query_exec` did all this

**Comment by hadley** [comment]
Is there a reason that you don't want to use the DBI interface for this? The `bq_` API is quite deliberately low-level, and I wanted to make it very clear that in BigQuery running a query always creates a table.

**Comment by czeildi** [comment]
no reason, thanks! the DBI interface is probably great for me, I am looking at it right now. And now I understand that the `bq_` is more a 1-to-1 api wrapper
