### ISSUE TITLE
Collect strptime and gmtime somewhere for re-use?

### ISSUE THREAD

**Issue by eddelbuettel** [r-dbi/bigrquery#244]
The packages brings its own copies of `strptime` and `gmtime`.  Should those be  'library-ified' somewhere?

I also needed `strptime` once so I exported the one from R itself in a package [RApiDatetime](https://github.com/eddelbuettel/rapidatetime). You can see the [header with its exports here](https://github.com/eddelbuettel/rapidatetime/blob/master/inst/include/RApiDatetime.h).  It may make sense to have something with minimal dependencies (ideally: none, which is what RApiDatetime has).  I could probably also look into adding `gmtime` to the existing package.  

Thoughts?

**Comment by hadley** [comment]
I was thinking that the right way to handle this is a new zero-dep C library for parsing dates (poor cross-platform support) and integers (since the C api is tricky to get right). I've been chatting with potential collaborators via email.

**Comment by eddelbuettel** [comment]
Yes, having something like that would be good.  My thinking had been the get what R itself has out -- hence `RApiDatetime` -- so that we get the same behaviour in R and C(++) code.   

It is also tricky to link to an external C library that is not system level.  Where you thinking of having the library in one package, and using the exporting mechanism to provide the object code?

**Comment by hadley** [comment]
Given that the embedded `gmtime()` doesn't support date/times before unix epoch, I no longer think extracting the functions from this package is a good idea.
