### ISSUE TITLE
User Agent String Does not Follow GPN format

### ISSUE THREAD

**Issue by cpcgoogle** [r-dbi/bigrquery#245]
The current package produces a user agent string similar to "bigrquery/0.4.1 httr/1.2.1,gzip(gfe)" which does not follow the user agent compliance with RFC (http://tools.ietf.org/html/rfc7231#section­5.5.3)

Suggested format
"<prod_name>/ver (GPN:<company name>; <other comments>) <other prod>/ver "*

Example
"Product_A/1.1 (GPN:Partner_ABC; staging) Product_B/1.3
Google­HTTP­Java­Client/1.20.0"

Making this small modification would enable tracking of the use of this package in the Google Cloud Platform.

**Comment by hadley** [comment]
Broken this into new issues - adding support for the format in gargle, and then using gargle in bigrquery.
