### ISSUE TITLE
query causes R to crash

### ISSUE THREAD

**Issue by ras44** [r-dbi/bigrquery#247]
I run into an issue where R crashes if I download a large table.  I'm not sure if everything is being stored in memory, but I'm using a GCE instance with 15GB of RAM.

Here's a quick reprex:
```
query <- "
  SELECT *
  FROM `fh-bigquery.dbpedia.place`
"

query_exec(project=project,
  query=query,
  max_pages=Inf,
  page_size=500000,
  use_legacy_sql=FALSE
)
# this correctly fails with a responseTooLarge error

bq_table_download(
  bq_project_query(project, whisker.render(query,config)),
  page_size=200
)
# this continues downloading with page_size 200 and then eventually R crashes
```

I'm not sure if this is related to #169.

In my case, I'm query a table with thousands of features and would like to pull it into a dataframe in R.  Please let me know if I can provide any additional information.  Since I'm on R Studio Server on a GCE instance with oob auth, I'm unable to create reprexs with the reprex library.

**Comment by hadley** [comment]
It's likely to be a bug with the C++ code that turns bq json into data frames. Can you please try and narrow down the cause? It's likely to be one cell that's causing the problem, so I'd suggest first doing a search on the rows (e.g. try `max_pages = 1`), and then figure out what column is the source.

Alternatively, if you know how to use a C debugger, I can help you figure out the source that way.

**Comment by ras44** [comment]
I can confirm the query works if I use `query_exec`, so I think your hunch is probably correct.  The difficulty with debugging on `max_pages=1` is that it downloads about 75% of the data before failling.  That might indicate some kind of nefarious memory leak that isn't being free'd.  If you have recommendations for debugging via a C debugger, I'd be happy to devote some time to that as having the speed of bq_table_download will save me time in the long-run.

**Comment by ras44** [comment]
The crash actually happens during the "Retrieving data" step, not the parse step.  Do you think it would still be related to the C++ code in that case?

**Comment by hadley** [comment]
Oh hmmmm, that is quite surprising, so a C debugger might be the way to go. What platform are you on?

**Comment by ras44** [comment]
I'm on a CentOS linux platform via ssh, so I'm working primarily via the command line (aside from R Studio Server).  I've used gdb in a very limited way with compiled C/C++ programs, but since the C code here is wrapped within R libs, I'm not sure how I would use something like gdb.  If there's something within R Studio that I'm unaware of, I'd be happy to learn.

**Comment by ras44** [comment]
Thanks for the guidance.

When I run with the debugger, I receive the response from the API:
```
Complete
Billed: 0 B
Downloading 639,450 rows in 3198 pages.
Downloading data [---------------------------------------------]   0% eta: 14hError: Exceeded rate limits: Your project: 168476834607 exceeded quota for tabledata.list bytes per second per project. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors [rateLimitExceeded]
```
However, when I run in R Studio, it crashes and I receive a pop-up that says something along the lines of "the previous R Session terminated unexpectedly".

**Comment by hadley** [comment]
Hmmmm, typically that indicates there's some mismatch of installed C++ libraries so you're getting an crash instead of an error. Next step (unfortunately) is to try reinstalling all your packages.

**Comment by ras44** [comment]
of course the next time I ran it, it crashed.  I will continue to update all packages and then reinstall all of them if necessary.

**Comment by stPhena** [comment]
I have exactly the same issue. I assume, after reading documentation, that it is because `bq_table_download()` does not allow specifying a rate limit. BQ allows a maximum of 60 MB/s and 150000 rows/second when downloading data.
```
Traceback:
 1: bq_parse_files(schema_path, page_paths, n = page_info$n_rows, quiet = bq_quiet(quiet))
 2: bq_table_download(bq_table(...), page_size = 1000, quiet = FALSE)
```

**Comment by ras44** [comment]
@stPhena thanks for taking the time to look into this.  This has been a persistent issue that has been hard for me to diagnose.  Are you able to reproduce the issue with the reprex mentioned at the start of this thread, namely:


```
query <- "
  SELECT *
  FROM `fh-bigquery.dbpedia.place`
"

query_exec(project=project,
  query=query,
  max_pages=Inf,
  page_size=500000,
  use_legacy_sql=FALSE
)
# this correctly fails with a responseTooLarge error

bq_table_download(
  bq_project_query(project, whisker.render(query,config)),
  page_size=200
)
# this continues downloading with page_size 200 and then eventually R crashes
```

If it's a rate limiting issue, perhaps we could look into keeping the transfers within that range via a PR.  It would obviously have to calculate the size of a row and then and rate limit to 60MB/s and 150k rows/sec.

**Comment by stPhena** [comment]
@ras44 It is indeed a rate-limiting issue, as shown by the message `exceeded quota for tabledata.list bytes per second per project`, which I had verbatim. In our case, it is the number of rows rather than the MB per second.
You can find BQ rate limits [here](https://cloud.google.com/bigquery/quotas#queries).

**Comment by ras44** [comment]
@stPhena I'm seeing two issues:

- the error you've described (`exceeded quota for tabledata.list bytes per second per project`) is output to the console
- no error is output, and R crashes and restarts

I'm having trouble creating a reproducible example that produces only one of the above errors consistently.  Currently, I'm using this one:

```
query <- "
  SELECT *
  FROM `fh-bigquery.dbpedia.place`
"

bq_table_download(
  bq_project_query(project, query),
  page_size=200
)
```
But it produces both errors and I'm unable to distinguish why it crashes sometimes and why it outputs an error other times.

Have you run into R crashing without outputting an error message?

**Comment by ras44** [comment]
I've modified the output settings so that in the cases when R does crash, I see this error reported prior to crashing:

Resolving timed out after 10000 milliseconds

**Comment by ras44** [comment]
It looks like this issue is related to [bigquery quotas](
https://cloud.google.com/bigquery/quotas).  It manifests itself in a variety of ways, with the following ad-hoc solutions:

### Too much data returned (large tables with many fields)
- Limits
  - Maximum bytes per second per project returned by calls to tabledata.list: 60 MB/second
  - Maximum rows per second per project returned by calls to tabledata.list: 150,000/second
- Solution
  - reduce page_size: `bq_table_download(..., page_size=200)`
  - reduce max_connections: `bq_table_download(..., page_size=100, max_connections=1)`

### Too many requests (large tables with few fields)
- Limits
  - API requests per second, per user — 100
- Solution
  - increase page_size: `bq_table_download(..., page_size=2000)`
  - reduce max_connections: `bq_table_download(..., page_size=100, max_connections=1)`

**Comment by ras44** [comment]
I've had some luck diagnosing by adding a very rudimentary callback:
```
bq_download_fail_callback <- function(page, path) {
  function(err) {
    print(err)
    print(page)
    print(path)
  }
}
```
and adding:
```
fail = bq_download_fail_callback(i, paths[[i]])
```
here:

https://github.com/r-dbi/bigrquery/blob/a3ef603f36495bc13d9a5f5081010084bf3c146c/R/bq-download.R#L126-L129

While this doesn't resolve this issue (I believe there would have to be some kind of smart bigrquery rate-limiting implementation), it does at least provide output to the user that there was an error.  Otherwise, R crashes without any output.

It may be helpful to abort the download if one of the requests fails as this might prevent the program from crashing.

**Comment by hadley** [comment]
The above query works fine for me. Does anyone else have an example that crashes for them?

**Comment by ras44** [comment]
This has been a difficult one to produce a consistent reprex for.  Going off the hypothesis that this is [related to quotas](https://github.com/r-dbi/bigrquery/issues/247#issuecomment-413813613), possibly attempt to increase the page_size?  Failing that, perhaps some variation of page_size and max_connections?

**Comment by ras44** [comment]
I think this was originally posted running R 3.4.x and with packrat managing the libraries.  Have you created a packrat project?  I would be happy to test it out again as I'm running 3.5.x now and can set up a packrat project pretty easily.

**Comment by hadley** [comment]
If you only see it with packrat, I think it's highly likely its a package incompatibility problem, not a bug in bigrquery (especially since I can't recreate it locally)

**Comment by gavinsteininger** [comment]
I am getting the same issue with R 3.6.2 GUI 1.70 El Capitan build (7735). The crashes are intermittent. But with a tendency to happen if  I either have not queried for a while ( an hour or so) or the query is big ( 100k plus rows) but they happen at other times as well.
