### ISSUE TITLE
set_service_token error

### ISSUE THREAD

**Issue by SergeiMakarovWeb** [r-dbi/bigrquery#258]
I try to run set_service_token("file.json"), but get error: 
```
Error in init_oauth_service_account(self$secrets, scope = self$params$scope,  : 
  Bad Request (HTTP 400).
```
But the weird thing is that it had worked before one random day. 
Another weird thing is that it works on local computer with the same json.

I'm stupid and can't find solution)
I have to run it remotly.

**Comment by DylanGraham** [comment]
Did you manage to solve this?

**Comment by SergeiMakarovWeb** [comment]
Not yet. Something with my environment, cause it doesn't work with other libraries like googleAuthR and etc

**Comment by DylanGraham** [comment]
Updating to the latest version worked for me:

    devtools::install_github("r-dbi/bigrquery")
