### ISSUE TITLE
Error: The maximum query length is 256.000K characters

### ISSUE THREAD

**Issue by dujm** [r-dbi/bigrquery#259]
Hi there, 
could you help me to have a look at this Error message? I am using bigrquery and DBI package. 

"Warning: Error in : The query is too large. The maximum query length is *256.000K* characters, including comments and white space characters."

### How could I increase the size limit of query length? 

Thank you very much!

**Comment by andrewm4894** [comment]
think thats a hard limit in BQ. StandardSQL might have a bigger one. Whats the query? Probably a case of needing to break it down into smaller parts and build up sub tables as you go. 
e.g. i've had to do this before where table was very very wide, just break it into N parts, make those tables, and then just join the tables later then.

**Comment by dujm** [comment]
@andrewm4894: Hi! Thank you very much for your comments. I didn't find a way to increase the query size in BQ using command lines. I'm going to follow your suggestion and break the query into N parts.

The codes I used for querying:  
`<
library(DBI)
library(bigrquery)
library(dplyr)

connect <- dbConnect(
  bigrquery::bigquery(),
  project = "project",
  dataset = "app",
  billing = "billing"
)

table <- tbl(connect, "bqfilename") 

result <- table %>% 
  filter(Start %in% inFile$Start) %>%
  filter(Chr %in% inFile$Chr)
>`

**Comment by hadley** [comment]
You'd probably be better off with a semi-join — it's likely to be much faster and won't need such a long SQL string.

**Comment by byilma** [comment]
I'm getting an error message saying [Error in `db_copy_to()`:! BigQuery does not support temporary tables] when trying to use semi_join ... would greatly appreciate any suggestions
