### ISSUE TITLE
DBI::dbWriteTable field.types not supported by bigrquery

### ISSUE THREAD

**Issue by selcukakbas** [r-dbi/bigrquery#263]
(this is my first issue in github)

`dbWriteTable(con_bq1, "mybq_table", myr_table, append = TRUE)`
Error: Invalid schema update. Field id has changed type from STRING to INTEGER [invalid]
> packageVersion("bigrquery")  # [1] ‘1.0.0’
> packageVersion("DBI") # [1] ‘1.0.0’

all column types of myr_table are character
all column types of mybq_table are string

`dbWriteTable(con_bq1, "mybq_table", myr_table, append = TRUE)`
this command was wroking with previous versions 
> packageVersion("DBI") # [1] ‘0.7’
> packageVersion("bigrquery") # [1] ‘0.4.1’

noticed that DBI::dbWriteTable added an option field.types but this is not supported by bigquery.
This error error occurs when I try
` dbWriteTable(con_bq1, "mybq_table", myr_table, append = TRUE, field.types = "character")`
Error: `field.types` not supported by bigrquery

dbWriteTable converts field types and then insert to BQ table. And types does not match.

I also tried github version of bigrquery package. Didn't work.

**Comment by aps2201** [comment]
Had the same problem, pulled my hair for hours because the auto-detect "feature" kept telling me my data was float when it was clearly string, my simple fix out of dumb luck:
```
dbWriteTable(bqconnection, table_name, data_frame, 
    fields = bq_table_schema, row.names = F, 
    append = T)
```
where bq_table_schema was the existing table's schema to maintain consistency which we can call here:
```
bq_table_schema = bq_table(project,dataset,table) %>%
    bq_table_fields()
```

Yeah, this works somehow and I think should be added to the docs.

**Comment by selcukakbas** [comment]
I switched to previous version.
devtools::install_version("DBI", version = "0.8", repos = "http://cran.us.r-project.org")
devtools::install_version("bigrquery", version = "0.4.1", repos = "http://cran.us.r-project.org")

thanks for bq_table_* didn't know this feature. Will use this.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Comment by dnlmc** [comment]
@aps2201  thanks for this solution!  saved me lots of (additional) hair-pulling

**Comment by jimcrozier** [comment]
If any one else runs into this, you can use bigrquery insert_upload_job() instead of the DBI functionality. 

```
 job <- insert_upload_job(project, dataset, "mtcars", mtcars)
 wait_for(job)
```

**Comment by abalter** [comment]
@hadley A MRE for this would require, in R, all the steps for creating a bigquery account, setting up a database, creating a datasource, creating a local oauth key, and then running the R code.

How would you suggest going about this?

**Comment by hadley** [comment]
@abalter you can assume that I have a bigquery account

**Comment by abalter** [comment]
Very interesting. I get this:

```
conn = DBI::dbConnect(
    bigrquery::bigquery(),
    project = "eacri-genomics",
    dataset = "clinvar_9302020"
    )

df = data.frame(
    A = c(1:10000, "X", 1),
    B = c(rep(letters[1:10], times=1000), "a", "b"),
    C = c(1:10000, 1, 1)
)

df %>% summary() %>% print()

df = df %>% mutate_all(as.character)

df %>% summary() %>% print()

DBI::dbWriteTable(
    conn=conn, 
    name="new_table", 
    value=df, 
    overwrite=T
)
       A              B              C        
 1      :   2   a      :1001   Min.   :    1  
 10     :   1   b      :1001   1st Qu.: 2499  
 100    :   1   c      :1000   Median : 5000  
 1000   :   1   d      :1000   Mean   : 5000  
 10000  :   1   e      :1000   3rd Qu.: 7500  
 1001   :   1   f      :1000   Max.   :10000  
 (Other):9995   (Other):4000                  
      A                  B                  C            
 Length:10002       Length:10002       Length:10002      
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  

R[write to console]: Complete

R[write to console]: Input:  317.84 kB

R[write to console]: Output: 168.92 kB
```

But this:

```
conn = DBI::dbConnect(
    bigrquery::bigquery(),
    project = "eacri-genomics",
    dataset = "clinvar_9302020"
    )

df = data.frame(
    A = c(1:100000, "X", 1),
    B = c(rep(letters[1:10], times=10000), "a", "b"),
    C = c(1:100000, 1, 1)
)

df %>% summary() %>% print()

df = df %>% mutate_all(as.character)

df %>% summary() %>% print()

DBI::dbWriteTable(
    conn=conn, 
    name="new_table", 
    value=df, 
    overwrite=T
)
%%R

conn = DBI::dbConnect(

    bigrquery::bigquery(),

    project = "eacri-genomics",

    dataset = "clinvar_9302020"

    )

​

df = data.frame(

    A = c(1:100000, "X", 1),

    B = c(rep(letters[1:10], times=10000), "a", "b"),

    C = c(1:100000, 1, 1)

)

​

df %>% summary() %>% print()

​

df = df %>% mutate_all(as.character)

​

df %>% summary() %>% print()

​

DBI::dbWriteTable(

    conn=conn, 

    name="new_table", 

    value=df, 

    overwrite=T

)

       A               B               C         
 1      :    2   a      :10001   Min.   :     1  
 10     :    1   b      :10001   1st Qu.: 24999  
 100    :    1   c      :10000   Median : 50000  
 1000   :    1   d      :10000   Mean   : 50000  
 10000  :    1   e      :10000   3rd Qu.: 75000  
 100000 :    1   f      :10000   Max.   :100000  
 (Other):99995   (Other):40000                   
      A                  B                  C            
 Length:100002      Length:100002      Length:100002     
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  

R[write to console]: Error: Job 'eacri-genomics.job_zidzvjxpLfkcyJwUnXWgfisZdfCL.US' failed
✖ Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 100000; errors: 1; max bad: 0; error percent: 0 [invalid]
✖ Error while reading data, error message: JSON parsing error in row starting at position 3377754: Could not convert value 'string_value: "1e+05"' to integer. Field: C; Value: 1e+05 [invalid]
Run `rlang::last_error()` to see where the error occurred.


Error: Job 'eacri-genomics.job_zidzvjxpLfkcyJwUnXWgfisZdfCL.US' failed
✖ Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 100000; errors: 1; max bad: 0; error percent: 0 [invalid]
✖ Error while reading data, error message: JSON parsing error in row starting at position 3377754: Could not convert value 'string_value: "1e+05"' to integer. Field: C; Value: 1e+05 [invalid]
```

Size issue with either `dbWriteTable` or BigQuery?

**Comment by darynaiva** [comment]
@abalter , try adding `options(scipen = 20)` at the beginning of the script  or adding `row.names = F` in the `dbWriteTable` command. I think the problem might be with row names. R uses scientific notation to 100000, which BigQuery is unable to recognize as an integer value.
