### ISSUE TITLE
Two test fails with "Access Not Configured [...] JSON API."

### ISSUE THREAD

**Issue by rasmusab** [r-dbi/bigrquery#265]
I've been trying, but failing, to get the test suit for `bigrquery` to run without tests failing. Two tests (`gs-object.R#27` and `test-gs-object.R#12`) fails due to the following reason:

> Access Not Configured. Cloud Storage JSON API has not been used in project 465736758727 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/storage-api.googleapis.com/overview?project=465736758727 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [accessNotConfigured]

If I click the link, I get to know that "you don't have permission", which makes sense as it's not my project.

**Could it be that enabling Cloud Storage JSON API for project 465736758727 would solve this?**

(Or could this be an issue on my side?)

How to replicate
----------------------------

Follow the instructions for testing found by running `?bq_test_init` in the R-prompt. Then run the following to run all the tests in the test suit:

```
library(testthat)
test_dir("tests/")
```

Full output when I run the test suite for `bigrquery`
------------------------

```R
> test_dir("tests/")


✔ | OK F W S | Context
── 1. Failure: can round trip data frame with list-cols (@test-bq-table.R#66)  ───
`df1` not equal to `df2`.
Incompatible type for column `val`: x numeric, y integer

── 2. Error: can roundtrip via save + load (@gs-object.R#27)  ───
Access Not Configured. Cloud Storage JSON API has not been used in project 465736758727 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/storage-api.googleapis.com/overview?project=465736758727 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [accessNotConfigured]
1: gs_object_delete(gs)
2: process_request(req) at .../coding/bigrquery/R/gs-object.R:27
3: bq_check_response(status, type, content) at .../coding/bigrquery/R/bq-request.R:171
4: signal_reason(json$error$errors[[1L]]$reason, json$error$message) at .../coding/bigrquery/R/bq-request.R:188

── 3. Failure: can retrieve full query results (@test-dbi-result.R#11)  ───
`df` not equal to tibble(count = 32).
Incompatible type for column `count`: x integer, y numeric

── 4. Failure: can retrieve without dataset (@test-dbi-result.R#17)  ───
`df` not equal to tibble(count = 32).
Incompatible type for column `count`: x integer, y numeric

── 5. Failure: can delete objects (@test-gs-object.R#7)  ───
gs_object_exists(gs) isn't false.

── 6. Error: can delete objects (@test-gs-object.R#12)  ───
Access Not Configured. Cloud Storage JSON API has not been used in project 465736758727 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/storage-api.googleapis.com/overview?project=465736758727 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [accessNotConfigured]
1: gs_object_delete(gs) at testthat/test-gs-object.R:12
2: process_request(req) at .../coding/bigrquery/R/gs-object.R:27
3: bq_check_response(status, type, content) at .../coding/bigrquery/R/bq-request.R:171
4: signal_reason(json$error$errors[[1L]]$reason, json$error$message) at .../coding/bigrquery/R/bq-request.R:188

══ testthat results  ═══
OK: 229 SKIPPED: 0 FAILED: 6
1. Failure: can round trip data frame with list-cols (@test-bq-table.R#66) 
2. Error: can roundtrip via save + load (@gs-object.R#27) 
3. Failure: can retrieve full query results (@test-dbi-result.R#11) 
4. Failure: can retrieve without dataset (@test-dbi-result.R#17) 
5. Failure: can delete objects (@test-gs-object.R#7) 
6. Error: can delete objects (@test-gs-object.R#12) 

`sessionInfo()`
-----------

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.10

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=sv_SE.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=sv_SE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=sv_SE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=sv_SE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DBI_1.0.0.9000       testthat_2.0.0       bigrquery_1.0.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18      rstudioapi_0.7    bindr_0.1.1       magrittr_1.5      progress_1.2.0   
 [6] hms_0.4.2         tidyselect_0.2.4  R6_2.2.2          rlang_0.2.2       fansi_0.3.0      
[11] httr_1.3.1        dplyr_0.7.6       tools_3.4.4       utf8_1.1.4        cli_1.0.0        
[16] withr_2.1.2       dbplyr_1.2.2      openssl_1.0.2     yaml_2.2.0        assertthat_0.2.0 
[21] tibble_1.4.2      crayon_1.3.4      bindrcpp_0.2.2    purrr_0.2.5       readr_1.1.1      
[26] curl_3.2          glue_1.3.0        compiler_3.4.4    pillar_1.3.0      prettyunits_1.0.2
[31] jsonlite_1.5      pkgconfig_2.0.2  
```

**Comment by hadley** [comment]
I _think_ these tests should just be skipped if you don't have auth available, but I'm not sure why they aren't failing with the travis build that is supposed to not have auth enabled.

**Comment by jennybc** [comment]
When I recently worked on the test set up, I definitely came to the conclusion that the `BIGQUERY_TEST_PROJECT` must have both BigQuery and the Cloud Storage JSON API enabled.
