### ISSUE TITLE
Provide option to set environment variables for project name and auth file

### ISSUE THREAD

**Issue by byapparov** [r-dbi/bigrquery#271]
Ideally on production projects variables like project name and path to auth file would be set in Environment Variables outside of the code. 

For example:

```
# .Renviron
BIGQUERY_PROJECT=my-dev-project
BIGQUERY_DEFAULT_DATASET=my-dev-project
BIGQUERY_AUTH_FILE=~/Documents/myproject/access_token.json
```

All package functionality will respect those settings which will make development process safe and logical. 

See similar logic implemented here:

https://github.com/cloudyr/googleCloudStorageR

**Comment by hadley** [comment]
I think our vision is that you'd use https://github.com/rstudio/config, rather than creating environment variables for every single database.
