### ISSUE TITLE
Random table names break Google query cache

### ISSUE THREAD

**Issue by tdsmith** [r-dbi/bigrquery#276]
Bigtable caches results in temporary tables for ~24 hours and tries to use them to return responses for duplicate queries, as might arise during iterative development workflows. Using the cache should return a query faster and without additional cost.

In order for a query to return a cached result, "the duplicate query text must be exactly the same as the original query." [1]

When dbplyr constructs a query with subqueries, the subqueries are labeled with random names -- e.g., the following expression

```r
clients_daily %>%
  filter(submission_date_s3 >= "2018-11-01") %>%
  group_by(submission_date_s3) %>%
  summarize(
    n=n(),
    devtools_n=sum(as.integer(devtools_toolbox_opened_count_sum > 0), na.rm=TRUE)
  ) %>%
  mutate(devtools_fraction=devtools_n/n)
```

is compiled to

```sql
SELECT `submission_date_s3`, `n`, `devtools_n`, `devtools_n` / `n` AS `devtools_fraction`
FROM (SELECT `submission_date_s3`, count(*) AS `n`, SUM(SAFE_CAST(`devtools_toolbox_opened_count_sum` > 0.0 AS INT64)) AS `devtools_n`
FROM (SELECT *
FROM `telemetry.clients_daily_v6`
WHERE (`submission_date_s3` >= '2018-11-01')) `sxgpziifpl`
GROUP BY `submission_date_s3`) `jmwrcxoxrq`
```

Note the randomly generated identifiers `` `sxgpziifpl` `` and `` `jmwrcxoxrq` ``, which change on each evaluation.

This breaks the cache, so running the dplyr expression twice results in two unique queries, which are executed and billed twice, instead of using the cached result.

It would be great if either bigrquery or dbplyr could use deterministic identifiers for subquery expressions to avoid cache-breaking.

[1] https://cloud.google.com/bigquery/docs/cached-results

**Comment by hadley** [comment]
I don't see any easy way to use deterministic identifiers here. But maybe BigQuery doesn't require the table names in subqueries?

**Comment by hadley** [comment]
@tdsmith does the following SQL work?

```R
SELECT `submission_date_s3`, `n`, `devtools_n`, `devtools_n` / `n` AS `devtools_fraction`
FROM (SELECT `submission_date_s3`, count(*) AS `n`, SUM(SAFE_CAST(`devtools_toolbox_opened_count_sum` > 0.0 AS INT64)) AS `devtools_n`
FROM (SELECT *
FROM `telemetry.clients_daily_v6`
WHERE (`submission_date_s3` >= '2018-11-01'))
GROUP BY `submission_date_s3`)
```

**Comment by hadley** [comment]
Now tracking in dbplyr: https://github.com/tidyverse/dbplyr/issues/336
