### ISSUE TITLE
package install hangs 

### ISSUE THREAD

**Issue by izzetagoren** [r-dbi/bigrquery#277]
Fresh install of R version 3.5.1 (2018-07-02) -- "Feather Spray", Platform: x86_64-pc-linux-gnu (64-bit), a f1-micro VM instance on Google Cloud Platform using googleComputerR CRAN package

hangs at: 

* DONE (rapidjsonr) * installing *source* package ‘bigrquery’ ... ** package ‘bigrquery’ successfully unpacked and MD5 sums checked ** libs g++  -I"/usr/local/lib/R/include" -DNDEBUG -DSTRICT_R_HEADERS -I"/usr/local/lib/R/site-library/progress/include" -I"/usr/local/lib/R/site-library/rapidjsonr/include" -I"/usr/local/lib/R/site-library/Rcpp/include" -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c BqField.cpp -o BqField.o

**Comment by hadley** [comment]
You probably need more memory
