### ISSUE TITLE
Edit Metadata Specifically Labels.

### ISSUE THREAD

**Issue by jordanwebb10** [r-dbi/bigrquery#281]
It would be helpful to edit Metadata, specifically Table Labels through the API.

**Comment by hadley** [comment]
Can you please provide more details including a link to the corresponding API documentation?

**Comment by J535D165** [comment]
This would be very helpful. 

Here is the documentation for loading the table into BQ: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load.

Bare example 
```
job <- insert_upload_job(
  "project", 
  "dataset", 
  "table", 
  iris, 
)
wait_for(job)
```

This can be something like:
```
job <- insert_upload_job(
  "project", 
  "dataset", 
  "table", 
  iris, 
  description = "This is iris."
  labels = c("iris")
)
wait_for(job)
```

Now the arguments description and labels are passed to `bq_body`, but they don't work (obviously).

**Comment by byapparov** [comment]
This actually works with `bq_table_create()` like this:

```R
bq_table_create(
  bq_mtcars,
  friendly_name = "Motor Trend Car Road Tests",
  description = "The data was extracted from the 1974 Motor Trend US magazine",
  labels = list(category = "temp")
)
```
