### ISSUE TITLE
Unable to work/download with NUMERIC columns

### ISSUE THREAD

**Issue by Iuiu1234** [r-dbi/bigrquery#282]
Bigrquery don't know how to work with NUMERIC columns.
 
**ERROR**
Next code
`conbq <- DBI::dbConnect(bigrquery::bigquery(), dataset = bqdataset, project = bqproject ,
                        billing = bqproject, use_legacy_sql = FALSE)`
`sql =  "select cast(2 as NUMERIC) numeric_column"`
`dbGetQuery(conbq,sql)`

gives the error
`Error in bq_parse_files(schema_path, page_paths, n = page_info$n_rows,  : 
  Unknown type NUMERIC`

**SOLUTION**
In the file 'srt/BqField.cpp' line 48, adding the code 
`  } else if (x == "NUMERIC") {
    return BQ_FLOAT;`
solves the problem.

**Comment by SurinSpace** [comment]
Numeric columns are still causing me to have an Error: 
**Error in is_fun_list(.x) : object 'as.float' not found**

![image](https://user-images.githubusercontent.com/28264470/53740161-91c70580-3e61-11e9-90ba-93bce40506ad.png)

**Comment by saabeilin** [comment]
I'm facing probably the same/similar issu:

```
> res <- bigrquery::query_exec(sql, project=project, use_legacy_sql = FALSE)
200.0 megabytes processed
Error: Don't know how to convert type numeric
```

Notice the lowercase `numeric`.
