### ISSUE TITLE
query_exec() returns error for tables from asia-south1 location.

### ISSUE THREAD

**Issue by Saikri5hna** [r-dbi/bigrquery#288]
Created new Dataset & tables under 'asia-south1' location which was opened recently for BigQuery in the same project where I've used Datasets from 'US' location.
Using query_exec() in R Server returns the following error -
Error: Not found: Job data-science-204210:job_UXRvdPsKJSThnw_t3HD_trtrwZJc [notFound]

Insert_upload_job is working fine.
Currently using a roundabout solution - 
1) Write the output of the query to a table in BigQuery using bq_perform_query()
2) Write the table to GCP bucket using bq_perform_extract()
3) Mount the bucket and load the data to the R environment.

I have got tons of automation scripts with query_exec() failing. So wondering if there would be fix in the next update or the above roundabout solution is the only way?

**Comment by hadley** [comment]
See #246 for a solution.
