### ISSUE TITLE
Move testthat to Imports?

### ISSUE THREAD

**Issue by jennybc** [r-dbi/bigrquery#291]
A total nitpick.

`testthat::skip()` is used in "regular" package functions that are, to be clear, only to be called by people interested in testing. But these functions are still exported (albeit marked internal) and still have at least one example. I'm talking about `bq_test_project()` and friends. Example:

https://github.com/r-dbi/bigrquery/blob/ff5c22e3aba28dc586b3805d11bc69c1da9b9dd6/R/bq-test.R#L30

I guess if it has never cause a problem, perhaps it is not a problem.

**Comment by hadley** [comment]
I think that since these should always be used inside tests, it's ok.
