### ISSUE TITLE
Translation problem with dev dbplyr

### ISSUE THREAD

**Issue by jennybc** [r-dbi/bigrquery#293]
Git bisect suggests that this dbplyr commit caused bigrquery to start failing:

https://github.com/tidyverse/dbplyr/commit/9b6e46e3a4b82721cdd097932475cd2b6881dffe

Most important snippet of a travis log for `dbplyr="devel"`:

https://travis-ci.org/r-dbi/bigrquery/jobs/498471785

```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  ── 3. Failure: %||% translates to IFNULL (@test-dplyr.R#131)  ──────────────────
  sql$select[[2]] not equal to "IFNULL(`x`, 2) AS `y`".
  1/1 mismatches
  x[1]: "IFNULL(`x`, 2)"
  y[1]: "IFNULL(`x`, 2) AS `y`"
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 235 SKIPPED: 4 FAILED: 3
  1. Failure: casting uses bigquery types (@test-dplyr.R#120) 
  2. Failure: casting uses bigquery types (@test-dplyr.R#121) 
  3. Failure: %||% translates to IFNULL (@test-dplyr.R#131)
```

**Comment by jennybc** [comment]
This is **absolutely not urgent** but if it's easy to fix it would bring me the happy, because then I could actually try to "keep things green" as I work in my PR. But I can also put in some strategic `skip()`s over there.

**Comment by hadley** [comment]
This is a correct behaviour change — you'll need to switch on version of dbplyr in the test. 

Something vaguely resembling this:

```R
if (packageVersion("dbplyr") > "???") {
  expect_equal(sql$select[[2]], "IFNULL(`x`, 2) AS `y`")
}  else {
  expect_equal(sql$select[[2]], "IFNULL(`x`, 2)")
}
```
