### ISSUE TITLE
Error connecting to Google Big query in Rstudio

### ISSUE THREAD

**Issue by YuanyuanZhang1986** [r-dbi/bigrquery#294]
library(bigrquery) 
project <- "project id " 
sql <- "SELECT year, month, day, weight_pounds FROM [publicdata:samples.natality] LIMIT 5" 
query_exec(sql, project = project) 

However getting error as below. 

Waiting for authentication in browser... 
Press Esc/Ctrl + C to abort 
Authentication complete. 
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached 

As you can see the authentication had been completed. Can anyone provide me a solution for this?? 
And i'm using a MAC, does it matter?

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
