### ISSUE TITLE
Display bq connection in Rstudio

### ISSUE THREAD

**Issue by iuiu34** [r-dbi/bigrquery#298]
RStudio 1.1< allows to display sets from the Sql DDBB's connections.

This works with DBI, for example the driver odbc::odbc. 
But not with bigrquery i.e. sets from bigquery don't display in the UI.

More info on the release, [here](https://support.rstudio.com/hc/en-us/articles/115010915687) and [here](https://rstudio.github.io/rstudio-extensions/rstudio-connections.html)

**Comment by byapparov** [comment]
@luiu1234 can you try version of bigrquery from my PR to confirm it is doing what you were asking for.
