### ISSUE TITLE
Tables as `data.table` rather than `tibbles`

### ISSUE THREAD

**Issue by saptarshiguha** [r-dbi/bigrquery#300]
Hello,
thank your for the very easy to use bigquery package. I use `data.tables` a lot and wrapped my bigquery functions as 

```
function(s,n=200,con=NULL){
    ## be careful with n=-1 !!
    if(is.null(con)) con <- ocon
    data.table(dbGetQuery(con, s, n = n))
  }
```

reporting my results as a `data.table`. However if the query returns a table with a column with type  'array of structs' (e.g. in BQ parlance `ARRAY<STRUCT<n INT64, m FLOAT64>>`) bigrquery very nicely returns this as a tibble column e.g.

```
> ll[, list(n, ttotal_n, ttotal_m)]
     n ttotal_n ttotal_m
 1: 18        0 <tbl_df>
 2:  6        1 <tbl_df>
```

Is there a way the package could optionally use `data.tables` instead of tibbles where it applies? This is what i'm doing now

```
> ff=ll[, list(n, ttotal_n, ttotal_m)]
> ff[, ttotal_m2:= lapply(ttotal_m, as.data.table)]
> ff
     n ttotal_n ttotal_m    ttotal_m2
 1: 18        0 <tbl_df> <data.table>
 2:  6        1 <tbl_df> <data.table>
 3:  3        3 <tbl_df> <data.table>
 4: 52       33 <tbl_df> <data.table>
...
```

**Comment by hadley** [comment]
I think your work around is the right approach. It would be a lot of work to parameterise this behaviour.
