### ISSUE TITLE
Add support for using arrays in parameterized queries

### ISSUE THREAD

**Issue by janejuenyang** [r-dbi/bigrquery#303]
The bigrquery package is a great interface; thanks for all who have contributed to its development! It would be very helpful if the package could be extended to handle arrays in parameterized queries, [a la their API documentation](https://cloud.google.com/bigquery/docs/parameterized-queries#bigquery_query_params_arrays-python). It seems that currently passing in array parameters is not supported in bigrquery.

I often find myself wanting to subset data from my BigQuery tables based on a set of IDs generated from another dataset that lives elsewhere. Have tried a couple ways of passing an array into `bq_dataset_query()` but gotten the error message: "Second argument of IN UNNEST must be an array but was STRING at..." 

Here's an example of what I've been trying. The commented out code show variations I've tried adding.

```R
library(dplyr)
library(bigrquery)
library(jsonlite)

project <- "bigquery-public-data"
dataset <- "un_sdg"

q <- "
  SELECT geoareaname, goal, count(goal) as n
  FROM `un_sdg.indicators`
  WHERE geoareaname IN UNNEST(@countries)
  GROUP BY geoareaname, goal
"

params <- c("Belgium", "Brazil", "Bulgaria") # %>% array() %>% toJSON()

d <- bq_dataset_query(
  x = paste0(project, ".", dataset),
  query = q,
  parameters = list(countries = params)
) %>%
  bq_table_download()

glimpse(d)
```

**Comment by byapparov** [comment]
here is an example JSON for query configuration that works:

```json
{
  "configuration": {
    "query": {
      "query": "SELECT COUNT(*) cnt FROM moon_phases WHERE phase IN UNNEST(@phases)",
      "useLegacySql": false,
      "priority": "INTERACTIVE",
      "queryParameters": [
        {
          "name": "phases",
          "parameterType": {
            "type": "ARRAY",
            "arrayType": {
              "type": "STRING"
            }
          },
          "parameterValue": {
            "arrayValues": [
              {
                "value": "First Quarter"
              },
              {
                "value": "Last Quarter"
              }
            ]
          }
        }
      ],
      "defaultDataset": {
        "projectId": "bigquery-public-data",
        "datasetId": "moon_phases"
      }
    }
  }
} 
```

**Comment by byapparov** [comment]
@janejuenyang do you mind trying version of the package from the byapparov:array-param branch to confirm this version does what you asked for:

```r
devtools::install_github("byapparov/bigrquery", ref = "array-param")
```
Thanks!

**Comment by janejuenyang** [comment]
@byapparov: it does indeed work! Thanks so much for extending the package to accommodate the array parameters; this will be so useful!

**Comment by warnes** [comment]
Many SQL variants limit the number of elements in a list used with 'IN'.   To work around this, I recently started using temporary tables.  Pseudo-code:
```
dbWriteTable(con, "__temporary_table__", tibble(ID=id_vector) )
df <- dbGetResults(con, "
    SELECT * 
    FROM some_other table AS ot
    RIGHT JOIN __temporary_table__ AS tt
       ON ot.ID = tt.ID
   ")
dbRemoveTable(con, "__temporary_table__", tibble(ID=id_vector) )
```

**Comment by byapparov** [comment]
@warnes I think this approach works very well for DML statements, e.g. `UPDATE` and goes inline with BigQuery recommendations. 

It is ok for batch pipe-lines, but it would not work for reporting.

Most common use case for this is a shinyapp with several multi-select filters, where having ability to pass vector in a variable is essential.
