### ISSUE TITLE
Issue RateLimit Exceeded

### ISSUE THREAD

**Issue by evandropp10** [r-dbi/bigrquery#306]
I'm using dyplr this is the code:
con <- dbConnect(
  bigrquery::bigquery(),
  project = "project",
  dataset = "dataset",
  billing = "project",
)

df <- tbl(con, "table")
df %>% collect()

And this is the error:
Downloading 5,102,682 rows in 511 pages.
Downloading data [=======================>--------------------------------------------------------------------------------------------------------------------------------]  16% ETA:  2mError: Exceeded rate limits: Your project: XXXXXXXXXX exceeded quota for tabledata.list bytes per second per project. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors [rateLimitExceeded]

I tried to use page_size but with no success. 
I don't know what i can do.

Help.

**Comment by riccardopinosio** [comment]
I would suggest you export the table to google cloud storage first, and download the data from there. It's better when you are dealing with a lot of data like that.

**Comment by byapparov** [comment]
There is a new endpoint in BigQuery which is in Beta now: 

https://cloud.google.com/bigquery/docs/reference/storage/ 

Corresponding python library is available:
https://github.com/googleapis/google-cloud-python/tree/master/bigquery_storage
