### ISSUE TITLE
What is the role of the API key in bigrquery?

### ISSUE THREAD

**Issue by jennybc** [r-dbi/bigrquery#315]
Current API key treatment comes from here:

https://github.com/r-dbi/bigrquery/pull/49

Is the BigQuery API usable with just an API key? Is there any point is sending one? I can't find any mention of API keys in current BigQuery docs.

If an API key is useful, I need to rework the gargle auth interface to also implement the API key.

If API keys are irrelevant, perhaps we should remove current API key code in the name of simplicity.

**Comment by jennybc** [comment]
cc @craigcitro 

Thoughts?

**Comment by jennybc** [comment]
From an alternative communication channel:

There is an API key use case, but it only applies to those internal to Google. Internally, there is a type of credential that is not associated with a project and thus still needs to be used with an API key for quote purposes. So you'd need to send token *and* API key. But this is not a general use case.

We are not set up for this 👆 and that's probably OK. I'm going to delete the existing API key code, which I believe serves no use case right now.

**Comment by hadley** [comment]
Any thoughts on this? If things are currently working, I'd be inclined to leave everything as is, given the amount of development resources currently available for bigrquery.

**Comment by jennybc** [comment]
I would just leave this open. But I know you hate that.

But when/if/next time someone digs in here (e.g. validating against the Discovery Document as we do in googledrive and googlesheets4), we should get off this particular fence. Logic either needs to be added or taken away.

**Comment by hadley** [comment]
Given that no one has complained about this, I'm going to close, but we can resurrect if needed.
