### ISSUE TITLE
Ability to create views

### ISSUE THREAD

**Issue by byapparov** [r-dbi/bigrquery#322]
table.insert API endpoint allows to create views, which would be great to have as an option.

It will allow to developers to have view's SQL code under source control and view updates could become part of automated release, or at least be done with script. 

Here is the link to API documentation:
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#ViewDefinition

Also, just realised that views can be created with DDL:
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_view_statement

**Comment by ljkong** [comment]
hi @byapparov, did you figure out a way to create views via bigrquery? thanks.

**Comment by byapparov** [comment]
Yes, you can do this with DDL statement passed to bq_query_execute()

**Comment by ljkong** [comment]
Thank you very much @byapparov
