### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by byapparov** [r-dbi/bigrquery#323]
Hi @hadley @jennybc,

I think this project would benefit from CONTRIBUTE.md file. For example, comments from #305 are not clear about the acceptance criteria for the code.

Project does not pass the `styler`. Is new code expected to pass specific checks? 
I had problems before with the style of tests, that would be good to cover. 

Instructions on testing locally would be much appreciated. I could not make it work after `gargle` integration.

Possibly other points can be added from the conduct perspective. 

Thanks
Bulat

**Comment by jennybc** [comment]
Yes, bigrquery should have a CONTRIBUTING.md file. I now see that it has never gotten our "standard" treatment for adding that (among other things).

In the meantime, I can answer a few specifics.

> Project does not pass the styler. Is new code expected to pass specific checks?

bigrquery predates the release of styler, so I am sure that, as a whole, styler would make many changes to the code. One day perhaps a maintainer will do a global restyling, although that has some downsides from a history point-of-view. So the pragmatic compromise is to try to make sure that new code or code that is modified has been styled well.

> Instructions on testing locally would be much appreciated. I could not make it work after gargle integration.

The gargle article [Managing tokens securely](https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html) describes our approach to the testing token. However, this approach was taken directly from bigrquery, though, so switching to gargle should not have really changed anything. I'm interested to hear more about what used to work for you but doesn't work now.

**Comment by byapparov** [comment]
I have the following:

-  `service-token.json` file in the root of the project. 
- `BIGQUERY_TEST_PROJECT` environment variable needs is set in .Renviron file.

Still tests are skipped:
```
test-bq-dataset.R:4: skip: can create and delete datasets
No BigQuery access credentials available
```

**Comment by jennybc** [comment]
It sounds like you don't have an encrypted service account token stored exactly as described in the article linked above:

[Managing tokens securely](https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html)

**Comment by byapparov** [comment]
I have tried this: 

```R
gargle:::secret_pw_name("bigrquery")

gargle:::secret_write(
  package = "bigrquery",
  name = "service-token.json",
  input = "service-token.json"
)
json <- secret_read("bigrquery", "service-token.json")
```
it throws error:
> Error in sodium::data_decrypt(raw, key = secret_pw_get(package), nonce = secret_nonce()) :  Failed to decrypt

May be you have seen this before?

**Comment by jennybc** [comment]
Are you skipping steps in the process for encrypting your service account token? Because several are missing above. Such as generating your random password and storing it as an env var.

**Comment by byapparov** [comment]
I have password stored in `.Renviron` and loaded in memory. 

Different error is raised if password is not set up.

**Comment by jennybc** [comment]
It's hard to say ... but it sounds like maybe the password stored in the env var is not the actual password used to encrypt the token? Maybe delete the encrypted token and re-encrypt?

Because here's the body of `secret_can_decrypt()` and it's only checking that you've got sodium and an env var that appears to have the write *name*:

```
secret_can_decrypt <- function(package) {
  requireNamespace("sodium", quietly = TRUE) && secret_pw_exists(package)
}
```

**Comment by byapparov** [comment]
I literally run this in one go (Command + Enter):

```r
gargle:::secret_write(
  package = "bigrquery",
  name = "service-token.json",
  input = "service-token.json"
)

json <- secret_read("bigrquery", "service-token.json")
``` 
I don't know if this is of any help:

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.14.3

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_1.0.1           bigrquery_1.1.1.9000

loaded via a namespace (and not attached):
 [1] pillar_1.3.1      git2r_0.15.0      prettyunits_1.0.2 tools_3.3.3       progress_1.1.2    testthat_2.0.0    digest_0.6.13    
 [8] packrat_0.4.8-1   bit_1.1-14        jsonlite_1.5      memoise_1.1.0     tibble_2.0.1      gargle_0.2.0.9002 pkgconfig_2.0.2  
[15] rlang_0.3.1       DBI_0.8           rstudioapi_0.10   commonmark_1.4    curl_3.1          withr_2.1.2       httr_1.3.1       
[22] stringr_1.3.0     roxygen2_6.1.1    xml2_1.1.1        knitr_1.20        desc_1.2.0        fs_1.3.1.9000     devtools_1.13.5  
[29] rprojroot_1.3-2   bit64_0.9-7       glue_1.3.0        R6_2.2.2          magrittr_1.5      backports_1.1.2   assertthat_0.2.0 
[36] stringi_1.1.7     sodium_1.1        crayon_1.3.4 
```

**Comment by jennybc** [comment]
Apologies if I am taking you too literally, but the above snippet encrypts a service account token, then *overwrites* it. And maybe you've done it more than once?

The snippet for encrypting the token shown in the [Encrypt the secret file](https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html#encrypt-the-secret-file) section shows what I would expect:

``` r
gargle:::secret_write(
  package = "gargle",
  name = "gargle-testing.json",
  input = "a/very/private/local/folder/gargle-testing.json"
)
```

> This writes an encrypted version of `gargle-testing.json` to `inst/secret/gargle-testing.json` relative to the current working directory, which is presumably the top-level directory of gargle’s source. This encrypted file should be committed and pushed.

Namely, that the main, unencrypted file holding the service account token lives somewhere outside the project, probably in some hidden directory up at the user level. Then the encrypted version is written into the project.

**Comment by byapparov** [comment]
It would not override the original file because encrypted token is saved in `inst/secret/service-token.json`, while original file stays untouched. (input and name have different relative paths as mentioned in the above quote) 

I have tried it from external folder, same error. 

Should I post it as bug in gargle, this specific problem is potentially not very relevant to bigrquery?

I will ask a members of my team to try this documentation and see if they can succeed and let you know.

**Comment by jennybc** [comment]
OK thanks. I believe @andrie got it to work when he wired gargle into [gcalendr](https://github.com/andrie/gcalendr) recently, so that is one positive data point.

**Comment by byapparov** [comment]
Ok, so the code in the `bigrquery` is different from `gargle`, I guess it is older version or something. 

This works based on the reverse engineering of the functions:

```R
secret_write(
  package = "bigrquery",
  name = "service-token.json",
  data = readChar("service-token.json", nchars = file.size("service-token.json"))
)

json <- rawToChar(secret_read("bigrquery", "service-token.json"))
```

**Comment by jennybc** [comment]
> Ok, so the code in the bigrquery is different from gargle, I guess it is older version or something.

Ah yes. The helpers in gargle were written more recently, inspired by those in bigrquery. But everything I've set up uses the helpers in gargle.

Sorry about that but glad we got to the bottom of it.

**Comment by byapparov** [comment]
Maybe these functions could be removed from `bigquery` in this case and exported from `gargle`? It would make this documentation reproducible. 

Let me know if you would prefer me to init the CONTRIBUTING file or you are happy to add it.

**Comment by jennybc** [comment]
> Maybe these functions could be removed from bigquery in this case and exported from gargle? It would make this documentation reproducible.

Yes, I am sitting down to do this right now, based on your experience above. I had sort of forgotten older versions still lived here.

**Comment by jennybc** [comment]
> Let me know if you would prefer me to init the CONTRIBUTING file or you are happy to add it.

We have a template for that file and others, so I've already added them all. I'm working on some customizations of CONTRIBUTING that apply to bigrquery specifically.
