### ISSUE TITLE
Drop old files and functions

### ISSUE THREAD

**Issue by byapparov** [r-dbi/bigrquery#335]
As version has progressed beyond `1.1.0` it would make sense to drop all the old code that comes from prior `1.0.0` to make it cleaner, e.g. `old-*.R` files and corresponding tests. 

I don't think anyone using  the old API should be able to notice the difference between `1.0.0` and `1.1.0`.

**Comment by hadley** [comment]
Unfortunately I think it needs to be deprecated first.

**Comment by byapparov** [comment]
Yes, deprecating would be the first thing to do.

I probably could have a try with PR next week

**Comment by hadley** [comment]
That would be great. I'm going to try and get a small bigrquery release out in the next couple of weeks, so I'll be paying attention to PRs. I should get to your current PRs early next week.
