### ISSUE TITLE
Cannot use legacy SQL with dbConnect

### ISSUE THREAD

**Issue by downloaderfan** [r-dbi/bigrquery#338]
Hi, I'm using dbConnect() along with dbGetQuery() to fetch data from Google BigQuery to RStudio. The queries I have are in legacySQL format. The reason why I'm using these instead of query_exec() is because query_exec() doesn't seem to work on non US datasets & my table is not stored in the US server. It's located in Asia-South 1.

<details>

The [documentation](https://www.rdocumentation.org/packages/bigrquery/versions/1.1.1/topics/bigquery) of dbConnect() mentions:

> use_legacy_sql
> If TRUE will use BigQuery's legacy SQL format.

Below is my example test code:

```
con <- dbConnect(
  bigrquery::bigquery(),
  project = project,
  billing = billing,
  use_legacy_sql = TRUE
)
sql <- paste0("SELECT * FROM [bigquery-public-data:samples.github_nested]")

samples <- dbGetQuery(con, sql)
```

On running the above, I get the following error.

> Error: Syntax error: Unexpected "[" at [1:15]. If this is a table identifier, escape the name with `, e.g. `table.name` rather than [table.name]. [invalidQuery]

Even if I use #legacySQL in the query  so that it becomes

```
sql <- paste0("#legacySQL
                      SELECT * FROM [bigquery-public-data:samples.github_nested]")
```

I get the following error

> Error: Query text specifies use_legacy_sql:true, while API options specify:false [invalid]

Any idea what might be causing this? Seems like a bug to me.

R version 3.6.0 (2019-04-26)
RStudio v1.2.1335
bigrquery v1.1.1
DBI v1.0.0

</details>

**Comment by downloaderfan** [comment]
Hi, any update on this? I'm still unable to fetch table located in Bigquery Asia-South dataset using dbConnect() along with dbGetQuery() to R. Would make fetching data from BigQuery to R a lot more convenient & reliable at my company if I'm able to do so using this method.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(bigrquery)
options(gargle_oauth_email = "hadley@rstudio.com")
con <- DBI::dbConnect(
  bigrquery::bigquery(),
  project = bq_test_project(),
  use_legacy_sql = TRUE
)
sql <- paste0("SELECT * FROM [bigquery-public-data:samples.github_nested]")

samples <- DBI::dbGetQuery(con, sql)
#> Error: Syntax error: Unexpected "[" at [1:15]. If this is a table identifier, escape the name with `, e.g. `table.name` rather than [table.name]. [invalidQuery]
```

<sup>Created on 2020-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I think the easiest way to resolve this is just to use `#legacySQL` at the start of your SQL block, i.e. https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql#sql-prefix
