### ISSUE TITLE
bq_auth() not connecting via R-Studio Web UI

### ISSUE THREAD

**Issue by spiddy69** [r-dbi/bigrquery#339]
I am trying to connect my R studio web interface non-interactively to BigQuery, but am experiencing some trouble having google verify my JSON credentials. 

I have uploaded the service account JSON and OAuth JSON files into the R studio server. 
When I run bq_auth_config(path = "path/to/oauth/json"), I get no error.
Then I run bq_auth(path = "path/to/serviceaccount/json"), I get the error described below. 

Additionally, I have tried running bq_auth() with complementing options such as email and scopes, but consistently get the same error.

I know @jennybc is seasoned with handling google api authentication issues and would greatly appreciate your assistance or colleague recommendation.

```r
> options(gargle_quiet = FALSE)
> bq_auth_configure(path = "/local/apps/R-google-keys/BigRQuery_OAuth_ClientID.json")
> bq_auth( path = "/local/apps/R-google-keys/bigrquery-svcacct.json")
trying token_fetch()
trying credentials_service_account()
adding 'userinfo.email' scope
Error: `scope` must be a length 1 character vector.
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
adding 'userinfo.email' scope
Error: 'is_interactive' is not an exported object from 'namespace:rlang'
Error: Can't get Google credentials.
Are you running bigrquery in a non-interactive session? Consider:
  * Call `bq_auth()` directly with all necessary specifics.
```

**Comment by jennybc** [comment]
A couple observations:

  * If you're using a service account token, you should not need to mess with the OAuth app at all, i.e. the `bq_auth_configure()` step can be omitted.
  * It looks like `rlang::is_interactive()` appeared in rlang v0.3.1. Perhaps you need to update rlang?
  * The error about the length of `scope` is weird to me. Is there any chance you're providing the OAuth app JSON as the service account token, i.e. the file names got wonky? Otherwise, it would be good to see the result of `traceback()` or `rlang::last_trace()`.

**Comment by gkkr99** [comment]
Thanks for reply. after upgrading rlang to "rlang_0.4.0", i am able to Authenticate with ADC.
Note: Service Account still an issue with SCOPE.
-----------------------------------------------------

Details from R-Studio UI:

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.10 (Final)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_1.5    gargle_0.3.1    bigrquery_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       assertthat_0.2.0 R6_2.2.2         DBI_0.7          httr_1.2.1       rlang_0.4.0      curl_2.8.1      
 [8] fs_1.3.1         tools_3.4.2      bit64_0.9-7      glue_1.3.1       bit_1.1-12       httpuv_1.3.5     compiler_3.4.2  
[15] openssl_0.9.6    tibble_1.3.3    


---------------------------------------------------------------------------------------
Sys.setenv("GOOGLE_APPLICATION_CREDENTIALS"="/home/$USER/R/application_default_credentials.json")
---------------------------------------------------------------------------------------

## trying with both Service Account first and then ADC.

> bq_auth(path="/local/apps/R-google-keys/bigrquery-svcacct.json")
trying token_fetch()
trying credentials_service_account()
adding 'userinfo.email' scope
Error: `scope` must be a length 1 character vector.
trying credentials_app_default()
file exists at ADC path: /home/$USER/R/application_default_credentials.json
ADC cred type: authorized_user

---------------------------------------------------------------------------------------

> project <- "name_of_the_project"
> sql <- "Select Current_date"
> query_exec(sql, project = project)

Error in if (self$params$as_header) { : argument is of length zero
---------------------------------------------------------------------------------------

to fix above error, i have followed "https://github.com/r-dbi/bigrquery/issues/336" and upgraded "gargle to gargle_0.3.1 .  

it didn't help.

**Comment by jennybc** [comment]
I don't understand where things stand with ADC.

> Thanks for reply. after upgrading rlang to "rlang_0.4.0", i am able to Authenticate with ADC.

but also:

> Error in if (self$params$as_header) { : argument is of length zero
> to fix above error, i have followed "#336" and upgraded "gargle to gargle_0.3.1 .
> it didn't help.

Not sure if ADC is working for you or not?

---

Re: the service account token. This remains my main observation and request:

> The error about the length of scope is weird to me. Is there any chance you're providing the OAuth app JSON as the service account token, i.e. the file names got wonky? Otherwise, it would be good to see the result of traceback() or rlang::last_trace().

Can you put the JSON here, but replacing sensitive bits with placeholder text? I'd like to confirm that the structure of this JSON reflects the service account tokens I've seen and planned around.

**Comment by spiddy69** [comment]
JSON to service account: 

>{
  "type": "service_account", 
  "project_id": "########",
  "private_key_id": "#########",
  "private_key": "-----BEGIN PRIVATE KEY-----
  "client_email": "bigrquery-svcacct@project.iam.gserviceaccount.com",
  "client_id": "#######",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/######"
}

**Comment by jennybc** [comment]
Your JSON has the same structure as my service account tokens.

I note that, in general, R and many relevant packages are fairly out of date (e.g. jsonlite, R6, httr, curl). So, personally, updating packages and perhaps R would be my next steps.

I have a hard time understanding your exact sequence of steps. It would be good to see a complete example of what you're executing, possibly with `options(gargle_quiet = FALSE)`.
