### ISSUE TITLE
Take note of the BigQuery sandbox

### ISSUE THREAD

**Issue by jennybc** [r-dbi/bigrquery#341]
https://cloud.google.com/blog/products/data-analytics/query-without-a-credit-card-introducing-bigquery-sandbox

**Comment by hadley** [comment]
Could use for testing (instead of paid account), and should advertise in vignettes etc.

**Comment by hadley** [comment]
Looking at this again, I think we should stick with a paid account for testing, but we should definitely mention this in the docs as an easy way to get started.
