### ISSUE TITLE
 JSON table encountered too many errors

### ISSUE THREAD

**Issue by selesnow** [r-dbi/bigrquery#344]
Hello!

When i try append rows to table over `dbWriteTable` or `bq_table_upload` i get error:

```
Running job 'netpeak-1079.job_17_tEqowfIkI3anM5J5FoKnTGhZL.US' [/]  2s
Error: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details. [invalid]
```

can I somehow get the error details?

maybe `bq_job_meta` or other function provide get the job details?

**Comment by selesnow** [comment]
I find solution:

```
bq_job(project = "netpeak-1079",job = "job_17_tEqowfIkI3anM5J5FoKnTGhZL", location = "US") %>% bq_job_meta()
```

thanks

**Comment by nielmangeka** [comment]
hei salesnow, can you explain for that solution, because i got same issue when i wanna import table from GCS to BQ. Thx!
