### ISSUE TITLE
Difficulties authenticating on dockerinstance

### ISSUE THREAD

**Issue by dmoimpact** [r-dbi/bigrquery#345]
Hi,
I am currently trying to authenticate using Gargle with the latest version of bigrquery. This is fairly easy to do locally, however I am not sure what the steps are to doing it on rStudio Server. I have tried viewing documentation from different sources, however I can only find examples for gmailr and googlesheets/drive. I also tried looking at https://gargle.r-lib.org/articles/non-interactive-auth.html, but I could not seem to figure out how to do the authentication properly.

**Comment by jennybc** [comment]
@dmoimpact Since you closed this, I hope that means you got it to work? Please let me know if not or if there is a some big documentation gap.

**Comment by dmoimpact** [comment]
Hi Jenny,
I actually thought that i was required to do authentication by Gargle, however i learned that i could simple refer to a service account from my vm's - Been trying to get Gargle to work today on a virtual environment with no luck, but it is fortunately not important now as the service account file helps with everything. Great work with this package =)

**Comment by jennybc** [comment]
gargle aims to automagically use the service account for VM's running on GCE. But I don't have any documented success or failure with that. Does that apply to you?

Or are you just saying that you got it to work with an explicit service account token? I.e. you pointed it at a JSON file?

Basically, we are flying rather blind right now with respect to some of the token flows that are highly tuned for Google infrastructure and I would dearly love to find a chatty user of said workflows.

**Comment by dmoimpact** [comment]
I was actually on an azure instance today trying to see if i could get it to work, while also trying the same things on a local dockerinstance.

I got it to work by pointing the json file, it was me not paying attention to the new setup and thought i had to use the gargle auth method, which is a lot easier to do locally.

I am definitely up for a chat about this, we are using VM's on GCE for most of our work, but it happens from time to time that we need to work in other environments, and in some cases also have to start thinking about running authentication serverless disregarding platforms.

There is definitely a lot of ways to do things, while you also have to make sure that everything is stable, and easy to adjust should API's change or things break down. I am hoping to do a bit of blogging about authenticating on different platforms and different scenarios soon, as I think that the documentation can a bit of a hassle to understand if you are not very technical.

**Comment by jennybc** [comment]
> I got it to work by pointing the json file, it was me not paying attention to the new setup and thought i had to use the gargle auth method, which is a lot easier to do locally.

I want to clear up what I sense is some confusion. What do you mean by "the gargle auth method"? **All auth** in bigrquery now runs through gargle. If you are using bigrquery, you are using gargle for auth. gargle supports several different token flows and I suspect you are referring to "gargle auth method" to refer to one specific flow.

So, when you say "gargle auth method", what exactly do you mean?

Yes I would like to hear more from you, especially re: finding and using the service account available from the metadata service for VMs on GCE. gargle is supposed to do this but I would not be surprised if this still needs work.
