### ISSUE TITLE
Cannot use new bq_auth() function with DBI

### ISSUE THREAD

**Issue by theclue** [r-dbi/bigrquery#347]
I'm using bigrquery using DBI wrapper and set_service_token().

I saw that the aforementioned is deprecated so I tried to switch to bq_auth(path =...., scope = ...)

This doesn't seems to work with DBI wrapper functions, as I get a "Invalid Credential (invalid)" message. Apparently, the new auth scheme is not applied to the (old) DBI wrappers?

I had to revert back to the deprecated function.

**Comment by jennybc** [comment]
Can you provide an actual small transcript of your exact calls and messages? Which command lead to "Invalid Credential (invalid)"? Did `bq_auth()` appear to succeed?

**Comment by jennybc** [comment]
The DBI example in the README is "live", i.e. we are actually running that code. So it certainly works at some level, hence my request for more details.

**Comment by theclue** [comment]
Hello, tnx for prompt support. Lemme paste some code then

This actually works:

```
set_service_token(Sys.getenv("GCP_BIGQUERY_AUTH_FILE"))

db.connection <- DBI::dbConnect(bigquery(),
                                project = bigquery.project,
                                dataset = bigquery.dataset,
                                use_legacy_sql = FALSE)

results <- suppressMessages(dbSendQuery(db.connection, query, use_legacy_sql = FALSE))
ga.data <- suppressMessages(quiet(dbFetch(results, n=-1)))
```

While this not (pasting console output here):

```
> bq_auth(path = Sys.getenv("GCP_BIGQUERY_AUTH_FILE"),
+         scopes = "https://www.googleapis.com/auth/devstorage.read_only")
> db.connection <- DBI::dbConnect(bigquery(),
+                                 project = bigquery.project,
+                                 dataset = bigquery.dataset,
+                                 use_legacy_sql = FALSE)
> results <- suppressMessages(dbSendQuery(db.connection, query, use_legacy_sql = FALSE))
Error: Invalid credential [invalid]
> bq_has_token()
[1] TRUE
```
As you may see, no error from bq_auth()

**Comment by jennybc** [comment]
What if you don’t specify a scope in bq_auth(), ie make the two calls actually comparable? How sure are you that this scope is sufficient?

**Comment by jennybc** [comment]
It is also possible that something else is misconfigured re this service account, which is making this scope problematic. set_service_account() just calls bq_auth(), so I suspect this is all about the scope and not about bq_auth() per se.
