### ISSUE TITLE
How to use own clientID in bq_auth

### ISSUE THREAD

**Issue by selesnow** [r-dbi/bigrquery#351]
Hello!

Could you help my, how i can use own client_id and client_secret in `bq_auth()` ?

**Comment by jennybc** [comment]
This is the best reference:

https://gargle.r-lib.org/articles/get-api-credentials.html

Specifically this section:

https://gargle.r-lib.org/articles/get-api-credentials.html#oauth-client-id-and-secret

**Comment by selesnow** [comment]
Very thanks!
