### ISSUE TITLE
Internal error when trying to download data

### ISSUE THREAD

**Issue by acvelozo** [r-dbi/bigrquery#352]
Hi,

Thanks a lot for this awesome package, we've been using it for a few months and it's been really useful for us. Since the past two days, we've been facing an issue, which we think is related to BigQuery and not the bigrquery package itself, but as we are not sure, we decided to report it here as well.

We have been getting regularly an error message when we try to download data from BigQuery. The same code works fine on some occasions and on others results in the error message: `An internal error occurred and the request could not be completed. [internalError]`. The code we have been executing looks something like this:

```r
library(bigrquery)

bq_auth(path="myCredentials.json")

dfr <- bq_table_download(bq_project_query("projectId","
          SELECT *
          FROM `projectId.datasetId.table1_*`
          WHERE _TABLE_SUFFIX IN ('suffix1')")),
    page_size=1000)
```
Due to the type of the error message and the fact that sometimes it works and sometimes it doesn't we think it should be an error related to BigQuery. However, when we logged a bug on Google's Issue Tracker, we noted that the other people that are facing this issue also seem to be using R when they encounter this issue. Maybe it's just a coincidence, but we're not sure.

Thanks in advance for any insight,
Best regards,
Alexandre Velozo

**Comment by byapparov** [comment]
Do you mind sharing a link to the issue tracker?

**Comment by acvelozo** [comment]
Sure, this is the link that we found for the Google Issue Tracker for BigQuery:
https://issuetracker.google.com/issues?q=componentid:187149%20status:open
 
And this is the specific issue that we logged there:
https://issuetracker.google.com/issues/142457683

**Comment by byapparov** [comment]
Thanks for sharing, it's very useful.

**Comment by jennybc** [comment]
I have no idea if it's related but there are reports of odd behaviour in googledrive over the past few weeks, that appear to be related to consistency/overlap of multiple requests that should form some sort of coherent whole. Again, I am speculating, but I have wondered if there is some general degradation re: synchronicity that is affecting multiple products.

**Comment by hadley** [comment]
Unfortunately there's not much I can do without a reproducible example 😞
