### ISSUE TITLE
Download type 'BYTE'

### ISSUE THREAD

**Issue by Iuiu1234** [r-dbi/bigrquery#354]
bigrquery is unable to download tables with column type: 'BYTE'.

**query** 
select sha1('abc') 
**error** 
Error in bq_parse_files(schema_path, page_paths, n = page_info$n_rows,  : 
  Unknown type BYTES

**Comment by imSheryans** [comment]
Hey, is this issue resolved? I'm having the same problem right now. Any idea on how to fix this?

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(bigrquery)

ds <- bq_test_dataset()
tb <- bq_dataset_query(ds, "select sha1('abc')")
bq_table_download(tb)
#> Error in bq_parse_files(schema_path, page_paths, n = page_info$n_rows, : Unknown type BYTES
```

<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
