### ISSUE TITLE
drop table if exists statement throws error if table doesn't exist

### ISSUE THREAD

**Issue by ras44** [r-dbi/bigrquery#357]
The DDL statement "DROP TABLE IF EXISTS dataset.tablename" currently throws an error if the table does not exist.  The statement should drop the table if it doesn't exist and not error otherwise, as described in the [bigquery api documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#examples_5):

> The DROP TABLE IF EXISTS DDL statement deletes a table in the specified dataset only if the table exists. If the table name does not exist in the dataset, no error is returned, and no action is taken.

---

Brief description of the problem:

```r
  query <- "
    DROP TABLE IF EXISTS dataset.table_that_does_not_exist
  "
  
  query_exec(
    project = project,
    query = query,
    use_legacy_sql = FALSE
  )
```

**Comment by valentas-kurauskas** [comment]
This happens with any `DBI::dbExecute("drop table..")` statement. Any `DBI::dbGetQuery()` statement that shouldn't return rows (`insert`, `create table`, `drop table`) does return or attempt to return the rows and fail.

**Comment by hadley** [comment]
If you want to unconditionally drop a table, just use `DROP TABLE`?
