### ISSUE TITLE
Unable to create partitioned tables 

### ISSUE THREAD

**Issue by Iuiu1234** [r-dbi/bigrquery#359]
In case exists, I want to write_truncate data in a partition table.
And in case not, I want to create the table, with the partition column, and then write the data.
All using the same command.
Ideally, command should look like
```
out = bq_project_query(x = 'ds-billing',
                       query = "select cast('2019-10-10' as date) day,  7 n ",
                  destination_table = "ds-project.ds_project.test_5$20191010",
                 write_disposition = 'WRITE_TRUNCATE',
                 time_partitioning = list(field = 'day', type='DAY'))
bq_table_download(out)
```
But this **not work**.

If it  helps, in python
```
client.query(query = 
"select cast('2019-10-10' as date) day,  7 n "
,
job_config=bigquery.QueryJobConfig(destination="ds-project.ds_project.test_5$20191010",
write_disposition=bigquery.job.WriteDisposition.WRITE_TRUNCATE,
time_partitioning=bigquery.table.TimePartitioning(field="day"))
).to_dataframe()
```
**works**

**Comment by Iuiu1234** [comment]
Solution is
```
out = bq_project_query(x = 'ds-billing',
                       query = "select cast('2019-10-10' as date) day,  7 n ",
                  destination_table = "ds-project.ds_project.test_5$20191010",
                 write_disposition = 'WRITE_TRUNCATE',
                 configuration = list(
                        query = list(time_partitioning = list(field = 'day', type='DAY'))))
bq_table_download(out)
```

This should be documented.

**Comment by byapparov** [comment]
Technically it is documented in tests and in the bigrquery API.

You can pass any parameter that API supports in the same way.

**Comment by MaximumV** [comment]
@byapparov pls advice me how to perform partitioned tables
I tried this, it creates table, but not partitioned
bq_table(project = "xxx",
         dataset = "email",
         table   = "test3") %>%
  bq_table_upload(values = data_messages,
                  create_disposition = "CREATE_IF_NEEDED",
                   write_disposition = 'WRITE_TRUNCATE',
                  fields = as_bq_fields(data_messages),
                  configuration = list(timePartitioning = list(field = 'send_date', type='DAY'))
                  )

**Comment by praneethkvs** [comment]
@byapparov @Iuiu1234 

Tried doing the same to create a partitioned table from bq_table_create as below, does not give me a partitioned table, just a regular table. 

bq_table_create('project.dataset.table',
                as_bq_fields(dataframe),
                configuration = list(
                  query = list(time_partitioning = list(field = 'part_date', type='DAY'))))

**Comment by byapparov** [comment]
@praneethkvs @MaximumV 


Here is a snippet from the code that works:
```r
bigrquery::bq_table_create(
      tbl,
      fields = read_json(schema.file),
      timePartitioning = list(type = "DAY"),
      clustering = clustering
    )
```

I don't think I have ever tried this with a named field.

**Comment by praneethkvs** [comment]
@byapparov  That works, even with the named field. Thank you so much !

**Comment by MaximilianoChiamulera** [comment]
Hi guys
if you want user only one comand you can use

bq_table_upload(bq_table(your information, "your table name"), 
                values=your table, 
                create_disposition='CREATE_IF_NEEDED', 
                write_disposition='WRITE_TRUNCATE', 
                fields = as_bq_fields(your table),
                configuration =list(timepartitioning = list(type="type of partition", field= "partition field")),
                quiet = NA)
 
I hope it is usefull for someone
