### ISSUE TITLE
Use GOOGLE_APLICATION_CREDENTIALS var for auth

### ISSUE THREAD

**Issue by Iuiu1234** [r-dbi/bigrquery#360]
As default call GOOGLE_APPLICATION_CREDENTIALS var in bq_auth.
`bq_auth(path = Sys.getenv('GOOGLE_APPLICATION_CREDENTIALS'))`

As [google site](https://cloud.google.com/docs/authentication/getting-started#auth-cloud-implicit-python) recommends.

**Comment by jennybc** [comment]
The first token-fetching method attempted by `bq_auth()` is application default credentials and this env var is the first consulted by `gargle::credentials_app_default()`. So we are effectively doing this, but implemented in a different way.

Are you experiencing an actual problem? If so, please provide more details.
