### ISSUE TITLE
Cannot connect via bqr_auth by using JSON file

### ISSUE THREAD

**Issue by ArbenKqiku** [r-dbi/bigrquery#362]
Hi,

I am trying to connect to my BigQuery project through R.

This is my code:
`install.packages("bigQueryR", repos = c(getOption("repos"), "http://cloudyr.github.io/drat"))
library(bigQueryR)

options("bigQueryR.scopes" = c("https://www.googleapis.com/auth/bigquery", 
                                          "https://www.googleapis.com/auth/bigquery.insertdata"))

bqr_auth(json_file = "/Users/arbenkqiku/Desktop/Scripts/BigQuery/Google Big Query - 2019-12-04-a5b53f332e6a.json")`

Here is what the Json file looks like:
`{
  "type": "service_account",
  "project_id": "xxxxxx",
  "private_key_id": "xxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMxxxxxx\n",
  "client_email": "xxxxxxxx.iam.gserviceaccount.com",
  "client_id": "xxxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/bigquery%40xxxxxb-xxxx9.iam.gserviceaccount.com"
}`

**Unfortunately, I get the following error**:
Error in init_oauth_service_account(self$secrets, scope = self$params$scope,  : 
  Bad Request (HTTP 400).

Do you know what is causing the issue?

Thank you for your help.

**Comment by kbmorales** [comment]
I think you might be looking for bigQueryR https://github.com/cloudyr/bigQueryR

**Comment by jennybc** [comment]
Yes as @kbmorales this does not appear to be about the bigrquery package.

We would load credentials for a service account via something like this:

``` r
bq_auth(path = "path/to/foofy-83ee9e7c9c48.json")
```
