### ISSUE TITLE
Get error "Can't get Google credentials" running from "crontab"

### ISSUE THREAD

**Issue by andirey** [r-dbi/bigrquery#365]
First of all, thank you for the great package "bigrquery" !
I can run the code below in RStudio and from the console. But it gives me an error "Can't get Google credentials" when I try to run it via "crontab".

Here is the code

```r
# 1. Library
library(bigrquery)

# 2. Credentials
BQ_AUTH_PATH <- "file_name.json"
BQ_PROJECT_ID <- "project_id"

# 3. Auth to BQ via 'json' credentials
bq_auth(path = BQ_AUTH_PATH)

# 4. Define 'project_id'
project_id <- BQ_PROJECT_ID

# 5. Define SQL queries
sql <- "SELECT * FROM `Ads.cpm_data`"

# 5. Load data
query_exec(sql, project_id, use_legacy_sql = FALSE)
```
Please, advice me how to fix this issue.

Thanks

Andrii

**Comment by jennybc** [comment]
Before doing anything else, I would double then triple check that this is not a path problem.

That is, you need to be absolutely certain that `BQ_AUTH_PATH` is doing what you want before we assume this is a more sophisticated problem with auth and tokens.

**Comment by andirey** [comment]
I fixed this issue by adding Google email into "bq_auth" function call

```r
BQ_AUTH_PATH <- "path_credentials_json"
BQ_AUTH_EMAIL <- "google_email"
bq_auth(path = BQ_AUTH_PATH, email = BQ_AUTH_EMAIL)
```

**Comment by jennybc** [comment]
What sort of credentials are in your JSON? Service account or a user token?

Because if it's a service account, the `email` you're passing shouldn't have any effect on things. So something smells a bit off here, in terms of understanding *why* things are now working. That is, I'm glad it's working (!), but I think you should use `bq_user()` to see who you are logged in as and make sure it's what you intend.

**Comment by andirey** [comment]
Dear Jenny!

Thanks a lot for the answer.

1/ By using the command "bq_user()" I get the following result that is the same as "client_email" parameter in JSON credentials file (see 2nd section, please):
> bq_user()
Auto-refreshing stale OAuth token.
"<MODEL-NAME>@<BQ_PROJECT_ID>.iam.gserviceaccount.com"

2/ My JSON file has the following parameters:
"type": "service_account"
"project_id": <BQ_PROJECT_ID>
"private_key_id": ...
"private_key": ...
"client_email": "<MODEL-NAME>@<BQ_PROJECT_ID>.iam.gserviceaccount.com"
"client_id": ...
"auth_uri": "https://accounts.google.com/o/oauth2/auth"
"token_uri": "https://oauth2.googleapis.com/token"
"auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
"client_x509_cert_url": ...

3/ The issue is that in the command bq_auth(path = BQ_AUTH_PATH, email = BQ_AUTH_EMAIL) I used BQ_AUTH_EMAIL from my own Google account. The script I made is using credentials from the company server and running on the dev stage from my own computer.

Will be glad to know your vision on this issue!

Thanks

Andrii

**Comment by jennybc** [comment]
I don’t see how providing the email is relevant or helps in the service account scenario. Can you remove that from your call?

**Comment by jennybc** [comment]
You really need to check the user in the cron scenario, in case I did not make that clear.

**Comment by andirey** [comment]
RE: I don’t see how providing the email is relevant or helps in the service account scenario.
> to be honest i also can't understand clear why it works - but it just works

RE: Can you remove that from your call?
> If ask me to delete this message - it's not a problem to do it
https://github.com/r-dbi/bigrquery/issues/365#issuecomment-568241725

RE: You really need to check the user in the cron scenario
> How it can be done for Google account? Thanks

**Comment by jennybc** [comment]
How to check the user in the cron scenario:

Use `bigrquery::bq_user()`. Do that in some "auth health check" script or chunk that leaves its results behind for you to examine. Would also be interesting to add `gargle::gargle_oauth_sitrep()`.

https://bigrquery.r-dbi.org/reference/bq_user.html

https://gargle.r-lib.org/reference/gargle_oauth_sitrep.html

**Comment by jennybc** [comment]
You want to see the service account reported as the user.

Your cron job shouldn't really be using the OAuth cache. But the fact that adding an email "helped" you makes me think it's possible the cron job is falling to find the service account token, but successfully falling back to a user token (?).
