### ISSUE TITLE
str_extract fails - REGEXP_MATCH not found 

### ISSUE THREAD

**Issue by jimmyg3g** [r-dbi/bigrquery#369]
Using `str_extract()` with BigQuery throws this error: "Function not found: REGEXP_MATCH [invalidQuery]" BigQuery does not have a `REGEXP_MATCH` function, it does have `REGEXP_CONTAINS`

Here's a reprex: 
```r
con <- dbConnect(
  bigrquery::bigquery(), 
  project = 'bigquery-public-data', 
  dataset = 'austin_311', 
  billing = billing
)
d <- tbl(con, '311_service_requests')   
d %>%
  mutate(new_column = str_detect(complaint_description, 'Dog'))
```
It looks like the change to make is in the dplyr.R file's stringr equivalents. This has worked for me: 
```r
str_detect =  sql_prefix("REGEXP_CONTAINS", 2)
```

Cheers!

**Comment by hadley** [comment]
Would you be interested in doing a PR?
