### ISSUE TITLE
Pass ... in DBI methods

### ISSUE THREAD

**Issue by valentas-kurauskas** [r-dbi/bigrquery#374]
Priority ("BATCH" or "INTERACTIVE") is an important parameter, because
the table.list operations have a 60 Mb/s per dataset limit in BigQuery for the default interactive queries. This issue made this parameter available https://github.com/r-dbi/bigrquery/issues/212 in `bq_perform_query`. It would be great to have this parameter supported by the DBI commands as well.

```r
con <- DBI::dbConnect(bigrquery::bigquery(), project="myProject", dataset="myDataset")
#priority parameter is ignored
DBI::dbGetQuery(con, "select * from myDataset.myTable", priority="BATCH") 
DBI::dbDisconnect(con)
```

**Comment by meztez** [comment]
As the priority is only just relevant to bigquery, I would probably advise against adding a parameter to the DBI implementation.

Maybe in the driver as is done with the page_size or an option in zzz.R with matching default bq_perform_query.

**Comment by hadley** [comment]
I don't think we could make this work with `dbGetQuery()` because `...` is sent to both `dbSendQuery()` and `dbFetch()`. But `dbSendQuery()` and `dbFetch()` should pass `...` to the underlying `bq_` functions so that you can set individually if needed.

**Comment by hadley** [comment]
Also needed in `collect()`

**Comment by hadley** [comment]
Actually I think I'm wrong because the `BigQueryResult` method for `dbFetch()` can just ignore `...` since all important arguments to `bq_table_download` are controlled otherwise.
