### ISSUE TITLE
Redundant notFound exception when calling DBI::dbExecute("drop table ..")

### ISSUE THREAD

**Issue by valentas-kurauskas** [r-dbi/bigrquery#375]
When calling `drop table`, `drop view`, etc commands for an *existing* table (view, etc) through `DBI::dbExecute`, the command is completed, but an exception is thrown. This makes it necessary to surround each such query with `try()` as a workaround.

---

```r
con <- DBI::dbConnect(bigrquery::bigquery(), project="myProject", dataset="myDataset")
#priority parameter is ignored
DBI::dbExecute(con, "drop table myDataset.myTable")
#Error : Not found: Table myDataset.myTable [notFound]
DBI::dbDisconnect(con)
```

**Comment by meztez** [comment]
After execution, it is trying to retrieve the numbers of rows from the table listed in the job meta.

From https://github.com/r-dbi/bigrquery/blob/ff5c22e3aba28dc586b3805d11bc69c1da9b9dd6/R/dbi-result.R#L11

```
$configuration$query$destinationTable
$configuration$query$destinationTable$projectId
[1] "projectId"

$configuration$query$destinationTable$datasetId
[1] "datasetId"

$configuration$query$destinationTable$tableId
[1] "tableId"
...
$statistics$query$statementType
[1] "DROP_TABLE"

$statistics$query$ddlOperationPerformed
[1] "DROP"
```

I see a couple ways to avoid this error, the more obvious is to condition on the statementType.

But you could always use the more straight forward method DBI::dbRemoveTable.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(bigrquery)

bq_auth(email = 'hadley@rstudio.com')

con <- DBI::dbConnect(bigrquery::bigquery(), project = bq_test_project())
DBI::dbExecute(con, "drop table myDataset.myTable")
#> Error: Not found: Dataset gargle-169921:myDataset was not found in location US [notFound]
#Error : Not found: Table myDataset.myTable [notFound]
DBI::dbDisconnect(con)
```

<sup>Created on 2020-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Better reprex:

``` r
library(bigrquery)

ds <- bq_test_dataset()
con <- DBI::dbConnect(bigrquery::bigquery(), 
  project = ds$project,
  dataset = ds$dataset
)

DBI::dbExecute(con, "DROP TABLE IF EXISTS foo")
#> Error: Not found: Table gargle-169921:TESTING_mblhqtzrzw.foo [notFound]
```

<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
