### ISSUE TITLE
Getting error when uploading the table to big query

### ISSUE THREAD

**Issue by gikis1** [r-dbi/bigrquery#377]
I am trying to upload the data into Google Big Query using Bigrquery package in R - I was able to successfully run the script before, but today it failed with no changes within a script.

Please see the script below:

```
library(bigrquery)
df = mtcars
    bq_auth(email = "my@email.com")
    job <- insert_upload_job("project-id", "dataset", "table name", df)
```

When I run the script, it shows that it is working, but the upload takes an infinite amount of time. When I stop the upload process, I am getting below message:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback
```

Surprisingly, I was able to run the above script successfully before, and it is only today that it failed (I haven't changed anything). Please help.

Thanks!

**Comment by hadley** [comment]
Unfortunately there's not much I can do to investigate this without a reproducible example.
