### ISSUE TITLE
Feature: use BigQuery Storage API

### ISSUE THREAD

**Issue by meztez** [r-dbi/bigrquery#381]
Downloading large table from BigQuery with BigQuery REST API v2 has a few problems:

- page_size limit of 150000 rows
- json file size limit
- performance

BigQuery Storage API v1 is supposed to be a good alternative to that.

Maybe that is something that could be used to download table.

Ref:
https://cloud.google.com/bigquery/docs/reference/storage
https://github.com/apache/arrow/tree/master/r

We are working on it internally, opening this issue so I'll be reminded to share it back with community.

**Comment by thesuperzapper** [comment]
@meztez just wondering what your timeline on this is?

**Comment by byapparov** [comment]
I think it is easier to implement something like this externally from the package, as a wrapper that combines functionality of `bigrquery` and `googleCloudStorageR` packages.

See example of a wrapper here: 

Download Query Results via Storage:
https://github.com/madedotcom/retl/blob/c976b7d730342e68eca7062db6e6d3e912d02705/R/bigquery-execute.R#L137

Import Data via Storage
https://github.com/madedotcom/retl/blob/6fde62b2db6855e6e96c0a8317dcc879e31dc501/R/bigquery.R#L23

Data load here is the following steps:
1. Schedule query (returns job.id)  with `bigrquery::bq_perform_query()`
2. Export target table of the job to Storage with `bigrquery::bq_table_save()`
3. Load storage object to local file with `googleCloudStorageR:: gcs_get_object()`
4. read file with `data.table::fread()`

You probably can do the 3 & 4 steps through memory, which will be 2x times faster from experience with S3.

**Comment by meztez** [comment]
I don't think BigQuery Storage API uses cloud storage as described above. As you said, this can already be done. But you would still be subject to cloud storage and bigquery quotas.

> When you use the BigQuery Storage API, structured data is sent over the wire in a binary serialization format. This allows for additional parallelism among multiple consumers for a set of results.

I was thinking more along the line of using gRPC > avro > tibble

**Comment by thesuperzapper** [comment]
@hadley I think this supporting the `BigQuery Storage API` is the single most important thing for this package right now, without it, people are significantly constrained in the size of the data they can extract from BigQuery.

**Comment by meztez** [comment]
@thesuperzapper 
Last time, we got stuck trying to install the existing gRPC port on windows : https://github.com/nfultz/grpc and then we have other things to do.

I'm giving this another go starting fresh with source gRPC : https://github.com/grpc/grpc if anyone is interested. Any Rcpp experience would be great.

`gRPC` would be the `httr` equivalent for BigQuery Storage API.

**Comment by meztez** [comment]
So a little update.

Work is in this fork : https://github.com/meztez/gRPC

- Still was not able to build package + dependencies on Windows using RTools40. After about a week, went back to WSL2 and compiled from there. So it builds on debian.

- Adapted gRPC parser and figured how to arrange BigQuery Storage API proto files for RProtobuf to use.
- Working on https://github.com/meztez/grpc/blob/master/demo/bigquery_storage.R

So right now I probably have to build something like https://github.com/googleapis/python-bigquery-storage to facilitate channel building and replace python dependencies with R equivalent.

ANY help is welcome. Will update when I get to AVRO to R object representation.

I'm further than last time, which is a start.

**Comment by tswast** [comment]
> ANY help is welcome. Will update when I get to AVRO to R object representation.

You'll likely get better performance with Arrow, as I assume R uses a column-oriented format in-memory, right?

**Comment by bquinart** [comment]
Have you decided which of the two formats available through the BigQuery Storage API would be used?
You mention Avro, but support for Arrow in the R ecosystem has improved a lot recently.
It should be more performant both for the transfer and loading (refer for example to https://medium.com/google-cloud/announcing-google-cloud-bigquery-version-1-17-0-1fc428512171 for the python implementation).

**Comment by meztez** [comment]
I'm indifferent on exchange format, will most likely use the first one to work.
https://github.com/googleapis/googleapis/blob/00bbad4dfd6633cf4b5f9596c1f93b756bb5c776/google/cloud/bigquery/storage/v1beta2/stream.proto#L35

**Comment by nealrichardson** [comment]
👋  I'm happy to help make things work with Arrow. I'm not familiar with the BQ APIs, but if you can get something that is receiving Arrow data, I can help wire that up in R.

Looking through what the [`read_rows` method does in Python](https://github.com/googleapis/python-bigquery-storage/blob/master/google/cloud/bigquery_storage_v1/reader.py), it uses an iterator that yields RecordBatches, and those are collected and stacked into a Table. That's straightforward. To build the RecordBatches, it's using some lower-level methods [here](https://github.com/googleapis/python-bigquery-storage/blob/master/google/cloud/bigquery_storage_v1/reader.py#L649-L664), which are also implemented in the `arrow` R package. So I think we have all of the pieces we need on the Arrow side.

I'm not aware of any R package that reads Avro format (searching CRAN I only find https://github.com/chezou/sparkavro, which uses Spark to read Avro), so I think Arrow will be the best bet here.

**Comment by meztez** [comment]
I have established connection from R and receiving the data.

- Figured out the voodoo magic required to make googleapis accept my request.
- Working GCP credentials, not using gargle at the moment.
- Received a stream of data in arrow that looks like this
```R
> stream$arrow_record_batch$serialized_record_batch
   [1] ff ff ff ff 08 01 00 00 14 00 00 00 00 00 00 00 0c 00 16 00 06 00 05 00 08 00 0c 00 0c 00 00 00 00 03 03 00 18 00 00 00 60 53 00 00 00 00 00 00 00 00 0a 00 18 00 0c 00 04 00 08 00 0a 00
  [63] 00 00 9c 00 00 00 10 00 00 00 82 03 00 00 00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0c 0e 00 00 00 00 00 00 10 0e 00 00
 [125] 00 00 00 00 04 07 00 00 00 00 00 00 18 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 18 15 00 00 00 00 00 00 0c 0e 00 00 00 00 00 00 28 23 00 00 00 00 00 00 23 14 00 00 00 00 00 00 50 37
 [187] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 37 00 00 00 00 00 00 10 1c 00 00 00 00 00 00 00 00 00 00 03 00 00 00 82 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 82 03 00 00 00 00 00 00
 [249] 00 00 00 00 00 00 00 00 82 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00 04 00 00 00 06 00 00 00 08 00 00 00 0a 00 00 00 0c 00 00 00 0e 00 00 00 10 00 00 00 12 00
 [311] 00 00 14 00 00 00 16 00 00 00 18 00 00 00 1a 00 00 00 1c 00 00 00 1e 00 00 00 20 00 00 00 22 00 00 00 24 00 00 00 26 00 00 00 28 00 00 00 2a 00 00 00 2c 00 00 00 2e 00 00 00 30 00 00 00
 [373] 32 00 00 00 34 00 00 00 36 00 00 00 38 00 00 00 3a 00 00 00 3c 00 00 00 3e 00 00 00 40 00 00 00 42 00 00 00 44 00 00 00 46 00 00 00 48 00 00 00 4a 00 00 00 4c 00 00 00 4e 00 00 00 50 00
 [435] 00 00 52 00 00 00 54 00 00 00 56 00 00 00 58 00 00 00 5a 00 00 00 5c 00 00 00 5e 00 00 00 60 00 00 00 62 00 00 00 64 00 00 00 66 00 00 00 68 00 00 00 6a 00 00 00 6c 00 00 00 6e 00 00 00
 [497] 70 00 00 00 72 00 00 00 74 00 00 00 76 00 00 00 78 00 00 00 7a 00 00 00 7c 00 00 00 7e 00 00 00 80 00 00 00 82 00 00 00 84 00 00 00 86 00 00 00 88 00 00 00 8a 00 00 00 8c 00 00 00 8e 00
 [559] 00 00 90 00 00 00 92 00 00 00 94 00 00 00 96 00 00 00 98 00 00 00 9a 00 00 00 9c 00 00 00 9e 00 00 00 a0 00 00 00 a2 00 00 00 a4 00 00 00 a6 00 00 00 a8 00 00 00 aa 00 00 00 ac 00 00 00
 [621] ae 00 00 00 b0 00 00 00 b2 00 00 00 b4 00 00 00 b6 00 00 00 b8 00 00 00 ba 00 00 00 bc 00 00 00 be 00 00 00 c0 00 00 00 c2 00 00 00 c4 00 00 00 c6 00 00 00 c8 00 00 00 ca 00 00 00 cc 00
 [683] 00 00 ce 00 00 00 d0 00 00 00 d2 00 00 00 d4 00 00 00 d6 00 00 00 d8 00 00 00 da 00 00 00 dc 00 00 00 de 00 00 00 e0 00 00 00 e2 00 00 00 e4 00 00 00 e6 00 00 00 e8 00 00 00 ea 00 00 00
 [745] ec 00 00 00 ee 00 00 00 f0 00 00 00 f2 00 00 00 f4 00 00 00 f6 00 00 00 f8 00 00 00 fa 00 00 00 fc 00 00 00 fe 00 00 00 00 01 00 00 02 01 00 00 04 01 00 00 06 01 00 00 08 01 00 00 0a 01
 [807] 00 00 0c 01 00 00 0e 01 00 00 10 01 00 00 12 01 00 00 14 01 00 00 16 01 00 00 18 01 00 00 1a 01 00 00 1c 01 00 00 1e 01 00 00 20 01 00 00 22 01 00 00 24 01 00 00 26 01 00 00 28 01 00 00
 [869] 2a 01 00 00 2c 01 00 00 2e 01 00 00 30 01 00 00 32 01 00 00 34 01 00 00 36 01 00 00 38 01 00 00 3a 01 00 00 3c 01 00 00 3e 01 00 00 40 01 00 00 42 01 00 00 44 01 00 00 46 01 00 00 48 01
 [931] 00 00 4a 01 00 00 4c 01 00 00 4e 01 00 00 50 01 00 00 52 01 00 00 54 01 00 00 56 01 00 00 58 01 00 00 5a 01 00 00 5c 01 00 00 5e 01 00 00 60 01 00 00 62 01 00 00 64 01 00 00 66 01 00 00
 [993] 68 01 00 00 6a 01 00 00
 [ reached getOption("max.print") -- omitted 20616 entries ]
```

Next, build some a read_rows functionality (with iterable) to get that thing into a proper R data.format.

**Comment by meztez** [comment]
@nealrichardson Hi.

What do you think would be the best way to combine the batches.

Combine  all the streams then convert to data.frame?
Convert each batch to data.frame then combine data.frame?

I know next to nothing about `arrow` inner working cogs beside that it is blazing fast.

```R
> library(arrow)
> reader <- RecordBatchStreamReader$create(res$arrow_schema$serialized_schema)
> batch <- record_batch(stream$arrow_record_batch$serialized_record_batch, schema = reader$schema)
> c(batch,batch)
[[1]]
RecordBatch
898 rows x 3 columns
$state <string>
$name <string>
$number <int64>

[[2]]
RecordBatch
898 rows x 3 columns
$state <string>
$name <string>
$number <int64>

> as.data.frame(batch)
# A tibble: 898 x 3
   state name      number
   <chr> <chr>      <int>
 1 WA    Helen        156
 2 WA    Dorothy      122
 3 WA    Mary         112
 4 WA    Margaret     104
 5 WA    Ruth          94
 6 WA    Alice         67
 7 WA    Mildred       49
 8 WA    Elizabeth     48
 9 WA    Esther        48
10 WA    Florence      44
# … with 888 more rows
```

Getting closer to release a reviewable package at https://github.com/meztez/bigrquerystorage, then we will test it in production for a couple of months to iron out the kinks.

**Comment by meztez** [comment]
Well this is slow. Opening and closing gRPC channel for each request seems like the wrong way to go at it. 

Dropping to Cpp and calling arrow Table__from_record_batches directly there before returning to R should be feasable, right?

So from R, pass the information required to initiate the table download, drop to Cpp to do the actual work, and come back to R with the coveted data.

Hang on folks, seems like I will have to learn more about cpp if I want to optimize that thing.

**Comment by nealrichardson** [comment]
From the arrow side, you don't need to drop to C++ to assemble the Table. You can call `Table$create(batch1, batch2, ...)`: https://github.com/apache/arrow/blob/master/r/R/table.R#L213

Can I run https://github.com/meztez/bigrquerystorage/blob/master/demo/bigquery_storage.R or does it require credentials I don't have? If there's code I can run, I may be able to be of more help.

**Comment by meztez** [comment]
It requires credentials to a google project where google can bill you following google ADC strategy for authorization.
Plus the whole gRPC install.
And it does not work on windows.

Let me set up a VM with rstudio-server and I'll pass along some credentials

**Comment by nealrichardson** [comment]
Sorry, just noticed your comment edit and found your email in my spam folder. Will take a look

**Comment by meztez** [comment]
I'm happy to report that we have a working [prototype](https://github.com/meztez/bigrquerystorage).

At this moment in time I would gladly accept some feedback to make the library faster.

@nealrichardson anyway to create the arrow Table any faster. I will be updating your environment for you to test it if you want. The current implementation takes a bit more than half the time on processing record batches.

Other than that, it is mostly performance related to moving bytes around in the C++ code, if someone would like to take a look at that, it would be great. I'm using `cpp11` package and the returned record batches list has a bunch of null entries padded at the end. I'm also pretty sure the way I transfer from the protocol buffer message to cpp11::raws is bottlenecking.

```r
library(bigrquery)
library(bigrquerystorage)

#Test bigrquery speed
system.time({
  con <- bigrquery::dbConnect(
    bigrquery::bigquery(),
    project = "bigquery-public-data",
    dataset = "usa_names",
    billing = "labo-brunotremblay-253317",
    bigint = "numeric",
    quiet = FALSE)
  dta <- bigrquery::bq_table_download(bigrquery::as_bq_table("bigquery-public-data.usa_names.usa_1910_current"))
})

# Downloading 6,122,890 rows in 613 pages.
# user  system elapsed
# 16.510   3.608  23.138

#Test bigrquerystorage
system.time({
  dtb <- bigrquerystorage::bqs_table_download("bigquery-public-data.usa_names.usa_1910_current", "labo-brunotremblay-253317", TRUE)
})
# user  system elapsed
# 12.357   0.486  20.739

#Compare table
all.equal(dta, dtb)
# [1] TRUE
```

**Comment by nealrichardson** [comment]
Looking at profvis, a good chunk of the remaining time is spent converting the Arrow Table to an R data.frame. We're doing some work now that I hope will speed that up some in the next release. But even as is, this looks like a win.

Now that you've solved the easy part ;) I think the next challenge is getting a build setup for grpc and any other dependencies so that you can get this on CRAN. I can advise you on some of that, based on our experience with `arrow`. But perhaps that should be taken up as issues on your repo, assuming you're not planning on submitting this as a PR to `bigrquery`?

**Comment by meztez** [comment]
I'm thinking about overloading the `bq_table_download` method on user request by reassigning in namespace. Yes, next steps will be taken care of in the repo.

**Comment by hadley** [comment]
@meztez if you get it working, we can eventually hook it up from bigrquery so that users don't need to do anything unusual.

**Comment by meztez** [comment]
@hadley It works on windows too now. Haven't tested on the new M1 chip, hit me up if you want to integrate at some point or fill free to reuse what is there.

**Comment by hadley** [comment]
Would love to get this into bigrquery. Can it be a PR or is it big enough that it should be in its own package?

**Comment by meztez** [comment]
I can make it into a WIP PR. And you'll see if it makes senses to add all those dependencies. There should be a way to select which method to use within dbFetch and dbReadTable. I'll keep that in mind.

**Comment by thesuperzapper** [comment]
Any updates @meztez

**Comment by meztez** [comment]
@thesuperzapper We have been running [bigquerystorage](https://github.com/meztez/bigrquerystorage) internally on GCP VMs since November 2020. Nobody noticed the transition beside data transfer speed boost. So far about 500 TB has been transferred without any issue. We stopped having curl http2 layer errors and other quota exceeded. I don't plan on releasing the package on CRAN and I have no further plan at this moment.

**Comment by thesuperzapper** [comment]
@meztez can you and @hadley work to integrate these changes in the official 'bigrquery' library?

**Comment by meztez** [comment]
@thesuperzapper I understand your excitement. There was a PR, you can read our mutual comments there. I'm intrigued to know why you believe it should be part of the "official" package. I think it is fine by itself.

Sidenote
Maybe I'm reading your intention wrong, but from the tone of your sentences, it seems you have some kind of work expectation from people here? If that is the case, please don't, it takes the fun out of it.

No disrespect, but it also kind of make you sound like a project manager.

Otherwise, I'm sorry, tone is hard to interpret.

**Comment by thesuperzapper** [comment]
@meztez just trying to understand the outcome of this work, as not having this feature makes the library not very useful for larger datasets 

Are you and @hadley sure maintaining a fork for a single feature is the best path forwards?

My thoughts are:
- bigrquery is the main package people use for BigQuery with R, so it makes sense for it to support Google's recommended data API
- people will be more inclined to use this package due to its history of being maintained
- in my experience, forks for single features get abandoned 

You mentioned this has been discussed already, can you link it?

**Comment by jennybc** [comment]
This is converging somewhat with #412. We're going to fix `bq_download_table()` in the short-term, to make it deliver the requested result more often and fail informatively when it does not. But I think the BigQuery Storage Read API would be the more definitive solution.

**Comment by tswast** [comment]
Some more info: Arrow is only compiling the GCS components, so unfortunately the BigQuery components won't be built as part of that pipeline. Since Arrow won't directly benefit from integrating with BigQuery, I doubt this will change.

**Comment by hadley** [comment]
Closing this since https://github.com/meztez/bigrquerystorage now exists, and we'll see if we can help to get it onto CRAN.
