### ISSUE TITLE
Using sql chunks in Rmarkdown with query parameters

### ISSUE THREAD

**Issue by byapparov** [r-dbi/bigrquery#391]
I am trying to work out if there is a way to pass parameters to the `sql` chunks connected to bigquery:

```r
#{r setup}
bq_auth(path = "access_token.json")
db <- dbConnect(
  bigquery(), 
  dataset = 'my_data', 
  project = 'my-project', 
  use_legacy_sql = FALSE
)

parameter_value = 10L

```

```sql
--{sql, echo=FALSE, connection=db, output.var="x"}
SELECT @parameter_value
```

```r
#{r output}
print(x)
# I want to see 10 here.
```

Also posted here - https://stackoverflow.com/questions/62466760/using-sql-chunks-in-rmarkdown-with-query-parameters

It looks like this file needs to be re-implemented fo `bigquery` connection class to achieve usability on the `sql` chunks: 
https://github.com/r-dbi/DBI/blob/master/R/interpolate.R

**Comment by hadley** [comment]
Can you please provide a simple `.Rmd` file that demonstrates the problem, and point me to where this feature is documented? It's not mentioned in ["R Markdown: the definitive guide"](https://bookdown.org/yihui/rmarkdown/language-engines.html#sql).

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Comment by byapparov** [comment]
Duplicates: https://github.com/r-dbi/bigrquery/issues/444
