### ISSUE TITLE
bq_auth() cannot authenticate offline with ADC

### ISSUE THREAD

**Issue by jayBana** [r-dbi/bigrquery#392]
`bigrquery` version 1.3.1 cannot authenticate using Application Default Credentials on Compute Engine without Internet access in GCP (instance still has access to "internal" Google Cloud Platform APIs). 

```r
bq_auth(use_oob=TRUE)

trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
file exists at ADC path: /home/jlpuser/.config/gcloud/application_default_credentials.json
ADC cred type: authorized_user
Error: Timeout was reached: [accounts.google.com] Connection timed out after 10001 milliseconds
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: bigrquery
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache
initiating new token

Enter authorization code: 
```

The above offline ADC authentication flow works with the Python libraries on the same type of machines.

We believe that the [this line](https://github.com/r-lib/gargle/blob/master/R/credentials_app_default.R#L65) in `gargle` should look something like `endpoint <- "https://oauth2.googleapis.com/token"` as the application default credentials file includes a refresh token as per the "offline" access_type described [here](https://developers.google.com/identity/protocols/oauth2/web-server#offline). Passing the resulting token in should prevent the library from trying to acquire it's own.

**Comment by jennybc** [comment]
Paging @craigcitro

I think this really should be an issue in gargle, but we can leave it here for the moment.

**Comment by jayBana** [comment]
Shall I move it over?

**Comment by jennybc** [comment]
Yes, please, sure. BTW what it the intent of `use_oob=TRUE` above? I generally have that filed under "regular OAuth flow" and don't associate it with service accounts.

**Comment by jayBana** [comment]
Ok. I will migrate the issue tomorrow and reference it in here.

`use_oob` is set to `TRUE` as we are trying to do this from RStudio Server running on Compute Engines in GCP.

This issue was completely “hidden away” from us up until we tried it out on an instance which had no access to the “outside world”. On an instance with access to the “outside world”, we didn’t run into this issue and managed to successfully authenticate with an ADC using a completely non-interactive workflow as expected. Going forward we will only be able to work with Compute Engine instances that don’t have access to the “outside world”.

**Comment by jayBana** [comment]
A new issue was opened and migrated to [`gargle`- link here](https://github.com/r-lib/gargle/issues/147).
