### ISSUE TITLE
Failed to parse with bq_table_download()

### ISSUE THREAD

**Issue by afalcioni** [r-dbi/bigrquery#396]
We experienced today a strange error that was not present yesterday (same query same system configuration)

The code is:

```r
query=MY_QUERY
path=MY_KEYPATH
projectID=MY_PROJECT

options(scipen = 20)
bigrquery::bq_auth(path = path)
tb <- bigrquery::bq_project_query(x = projectID, query = query, 
                                  destination_table = NULL, 
                                  use_legacy_sql=FALSE) %>% 
  bigrquery::bq_table_download() 
```

Today it returns:
**Error in bq_parse_files(schema_path, page_paths, n = page_info$n_rows,  : 
  Failed to parse '/tmp/Rtmpyo2x5f/bq-24ce7e7591c8.json'
In addition: There were 13 warnings (use warnings() to see them)**

And the warnings are all the same:
**Warning messages:
1: In writeBin(result$content, con) : problem writing to connection
...**

The error occurs when calling the function `bigrquery::bq_table_download()`.

**Comment by hadley** [comment]
Is this the same problem as #395? i.e. does `options(scipen = 20)` make it go away?

**Comment by afalcioni** [comment]
Hi @hadley, It is a different problem. I forgot to include `options(scipen = 20)` in the example, I updated it now. 
Your proposed solution solved problem #395 we had yesterday, but today we have this new problem.

**Comment by hadley** [comment]
Can you please produce a reprex? Unless I can reproduce it locally, it's going to be impossible to fix.

**Comment by afalcioni** [comment]
I'm sorry, I forgot to close the issue. The error doesn't occur anymore. I think it was a temporary problem related to some update in BQ API's and now they solved it.
