### ISSUE TITLE
bigrquery errors when selecting a specific column(s) but not when selecting all columns

### ISSUE THREAD

**Issue by kesnalawrence** [r-dbi/bigrquery#397]
---
I'm having an issue where bigrquery will not allow me to select an individual column but will allow "select *" equivalents.

I can use bigqrquery to create tables, upload data to tables, and all the normal activities so long as I don't attempt to do an activity involving anything other than all columns in a table. See code example below:

```r
library(tidyverse)
library(bigrquery)


bq_auth(path="~/OneDrive/Documents/code/GoogleAPI/mha-dashboard-bigquery.json")


con <-con <- dbConnect(
  bigrquery::bigquery(),
  project = "bigquery-public-data",
  dataset = "census_bureau_acs",
  billing = "my_valid_project_id"
)



#this works
tbl(con, "censustract_2018_5yr") %>%
  head
```

```
#this does not work
tbl(con, "censustract_2018_5yr") %>%
  select(households)

```
Returns
```
Error: Invalid project ID 'my_project_id'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash. [invalid] 
```

Below is my session info

```
sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bigrquery_1.3.1.9000 forcats_0.4.0        stringr_1.4.0       
 [4] dplyr_1.0.0          purrr_0.3.3          readr_1.3.1         
 [7] tidyr_1.0.2          tibble_3.0.3         ggplot2_3.2.1       
[10] tidyverse_1.3.0      RPostgreSQL_0.6-2    DBI_1.1.0           

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0 ggthemes_4.2.0   haven_2.2.0      lattice_0.20-38 
 [5] gargle_0.5.0     colorspace_1.4-1 vctrs_0.3.2      generics_0.0.2  
 [9] utf8_1.1.4       rlang_0.4.7      pillar_1.4.6     glue_1.4.1      
[13] withr_2.2.0      bit64_0.9-7.1    dbplyr_1.4.2     modelr_0.1.5    
[17] readxl_1.3.1     lifecycle_0.2.0  munsell_0.5.0    gtable_0.3.0    
[21] cellranger_1.1.0 rvest_0.3.5      curl_4.3         fansi_0.4.1     
[25] broom_0.5.4      Rcpp_1.0.5       clipr_0.7.0      openssl_1.4.2   
[29] backports_1.1.5  scales_1.1.0     jsonlite_1.7.0   fs_1.4.2        
[33] bit_1.1-15.2     askpass_1.1      hms_0.5.3        stringi_1.4.6   
[37] grid_3.6.1       cli_2.0.2        tools_3.6.1      magrittr_1.5    
[41] lazyeval_0.2.2   crayon_1.3.4     pkgconfig_2.0.3  ellipsis_0.3.1  
[45] xml2_1.2.5       reprex_0.3.0     lubridate_1.7.4  assertthat_0.2.1
[49] httr_1.4.1       rstudioapi_0.11  R6_2.4.1         nlme_3.1-144    
[53] compiler_3.6.1  
```

**Comment by kesnalawrence** [comment]
I found this [link](https://issuetracker.google.com/issues/124102546) and from my reading, it appears the issue is not uncommon for clients using the bigquery API. I think there might be something that can be done in the client to prevent the issue. It has to do with a bigquery API bug that doesn't like dashes in project names even though they are valid characters according to their own error message. I speculate some type of escaping within the client will help. Thoughts?

**Comment by hadley** [comment]
This worked for me:

``` r
library(tidyverse)
library(dplyr, warn.conflicts = FALSE)

bigrquery::bq_auth("hadley@rstudio.com")

con <- DBI::dbConnect(
  bigrquery::bigquery(),
  project = "bigquery-public-data",
  dataset = "census_bureau_acs",
  billing = Sys.getenv("BIGQUERY_TEST_PROJECT")
)

df <- tbl(con, "censustract_2018_5yr")
select(df, households)
#> # Source:   lazy query [?? x 1]
#> # Database: BigQueryConnection
#>    households
#>         <dbl>
#>  1       1612
#>  2       1548
#>  3       1607
#>  4       1466
#>  5        910
#>  6       1255
#>  7       1163
#>  8       1071
#>  9        613
#> 10        800
#> # … with more rows
```

<sup>Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

So presumably it's been fixed upstream.

**Comment by kesnalawrence** [comment]
> This worked for me:
> 
> ```r
> library(tidyverse)
> library(dplyr, warn.conflicts = FALSE)
> 
> bigrquery::bq_auth("hadley@rstudio.com")
> 
> con <- DBI::dbConnect(
>   bigrquery::bigquery(),
>   project = "bigquery-public-data",
>   dataset = "census_bureau_acs",
>   billing = Sys.getenv("BIGQUERY_TEST_PROJECT")
> )
> 
> df <- tbl(con, "censustract_2018_5yr")
> select(df, households)
> #> # Source:   lazy query [?? x 1]
> #> # Database: BigQueryConnection
> #>    households
> #>         <dbl>
> #>  1       1612
> #>  2       1548
> #>  3       1607
> #>  4       1466
> #>  5        910
> #>  6       1255
> #>  7       1163
> #>  8       1071
> #>  9        613
> #> 10        800
> #> # … with more rows
> ```
> 
> Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)
> 
> So presumably it's been fixed upstream.

Thank you for testing. I copied your example.  Using my project ID to execute `df <- tbl(con1, "censustract_2018_5yr") select(df, households) %>% head(100)`,  I'm still getting the same error about "invalid project ID"  but doing `df %>% head` returns six rows 242 columns.  

I'm going to create a new project to see if it is tied to an item in my project.

**Comment by kesnalawrence** [comment]
I found the issue and it is weirdness in how the Bigquery API works. Basically, if all your connection and token information is correct you can run queries with an incorrect project ID so long as you don't select specific columns.
