### ISSUE TITLE
DBI::dbWriteTable error when writing to BigQuery — trying to coerce string to int

### ISSUE THREAD

**Issue by abalter** [r-dbi/bigrquery#410]
If you think this is a postgresql issue, I'm happy to repost there. But I wonder if it has to do with the way `dbWriteTable` is honoring the dataframe types.

I have a dataframe wtih all fields of type character. However I get the following message when I try to write the table:

>Error: Job 'eacri-genomics.job_DlKHF2XCYbua8aDlIMW65R0q44yn.US' failed
>✖ Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 740479; errors: 1; max bad: 0; error percent: 0 [invalid]
>✖ Error while reading data, error message: JSON parsing error in row starting at position 392688729: Could not convert value 'string_value: "X"' to integer. Field: CHROM; Value: X [invalid]
>Run `rlang::last_error()` to see where the error occurred.

It is true that at row 740479 CHROM goes from having values 1-34 to "X". But it should be treating all the values as characters.

```r
%%R
tempdf %>% summary() %>% print()

DBI::dbWriteTable(
    conn=clinvar_conn, 
    name=table_name, 
    value=tempdf, 
    overwrite=T
)
 CHROM               POS                 ID                REF           
 Length:775501      Length:775501      Length:775501      Length:775501     
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
     ALT                QUAL              FILTER              INFO          
 Length:775501      Length:775501      Length:775501      Length:775501     
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  

Error: Job 'eacri-genomics.job_DlKHF2XCYbua8aDlIMW65R0q44yn.US' failed
✖ Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 740479; errors: 1; max bad: 0; error percent: 0 [invalid]
✖ Error while reading data, error message: JSON parsing error in row starting at position 392688729: Could not convert value 'string_value: "X"' to integer. Field: CHROM; Value: X [invalid]
Run `rlang::last_error()` to see where the error occurred.

```

**Comment by byapparov** [comment]
@abalter, did you try to investigate this part of the error:

>> Could not convert value 'string_value: "X"' to integer. Field: CHROM; Value: X [invalid]

Is it possible that your target table has numeric type for the `CHROM` field, which contains non-numeric values?

**Comment by hadley** [comment]
Closing since no follow up in ~3 years.
