### ISSUE TITLE
Bigint download as character fails with dbplyr (but works with DBI)

### ISSUE THREAD

**Issue by LukasWallrich** [r-dbi/bigrquery#411]
I have a Google bigquery table with bigint fields that I would like to download as text. DBI::dbConnect() lets me set bigint = "character" but that only seems to work for SQL queries run without dbplyr. If I understand the documentation correctly, the option should also be respected by dbplyr. If not, then I'd be grateful for a hint.

I don't quite know how to provide a reprex. Below an outline of the code I use.

```r
con <- DBI::dbConnect(
  bigquery(),
  project = projectid,
  dataset = datasetid,
  billing = projectid,
  bigint = "character"
)

# This works
tb <- DBI::dbGetQuery(con, "SELECT `user_id` FROM `tweets`")

# This doesn't - returns NAs due to integer overflow
mini_tweets_bq <- tbl(con, "mini_tweets")
mini_tweets_bq  %>% select(user_id) %>%  collect()

```

**Comment by hadley** [comment]
Any chance you're still interested enough in this problem to provide a reprex using a publicly available dataset?

**Comment by hadley** [comment]
This doesn't have any really big integers, but it we get character vectors back, demonstrating that the `bigint` argument is passed through to the correct place:

``` r
library(bigrquery)
library(dplyr, warn.conflicts = FALSE)
options(gargle_oauth_email = TRUE)

ds <- bq_dataset("publicdata", "samples")
con <- DBI::dbConnect(
  ds,
  quiet = FALSE,
  billing = bq_test_project(),
  bigint = "character"
)

tbl(con, "natality") |> 
  select(year, month, day) |> 
  head(5)
#> ℹ The bigrquery package is using a cached token for 'hadley@posit.co'.
#> Complete
#> Billed: 0 B
#> Complete
#> Billed: 2.66 GB
#> Downloading first chunk of data.
#> First chunk includes all requested rows.
#> # Source:   SQL [5 x 3]
#> # Database: BigQueryConnection
#>   year  month day  
#>   <chr> <chr> <chr>
#> 1 2005  5     <NA> 
#> 2 2005  6     <NA> 
#> 3 2005  11    <NA> 
#> 4 2005  6     <NA> 
#> 5 2005  5     <NA>
```

<sup>Created on 2023-11-10 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>
