### ISSUE TITLE
Syntax error in `PERCENTILE_CONT` functions

### ISSUE THREAD

**Issue by ahmohamed** [r-dbi/bigrquery#419]
Functions that use `PERCENTILE_CONT` in BigQuery are not constructing the query correctly (`median`, `quantile`). Here is how the functions are currently translated.

``` r
library(tidyverse)
library(bigrquery)
billing <- Sys.getenv('BILLING')
path = Sys.getenv('AUTH_PATH')
bq_auth(path = path)
con <- dbConnect(
  bigrquery::bigquery(),
  project = bq_test_project(),
  billing = billing
)

q = tbl(con, "bq_test.mtcars") %>% 
  summarise(disp_median = median(disp, na.rm = TRUE))

collect(q)
#> Error: Job 'jk-test-compute-3e8da53f.job_gbu6LA8nKmSE5RBA0CEesIDcRQzK.US' failed
#> x Syntax error: Expected end of input but got keyword WITHIN at [1:29] [invalidQuery]

show_query(q)
#> <SQL>
#> SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY `disp`) AS `disp_median`
#> FROM `bq_test.mtcars`
```

<sup>Created on 2020-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Similar behavior is observed when `mutate` is used instead of `summarise`

## Solution

`PERCENTILE_CONT` in currently implemented as an analytical function in BQ. Aggregation is not yet supported. The current way to perform quantile aggregation is:

```sql
SELECT ANY_VALUE(disp_median) as disp_median
FROM(
  SELECT PERCENTILE_CONT(`disp`, 0.5) OVER() AS `disp_median`,
  FROM `jk-test-compute-3e8da53f.bq_test.mtcars`
)
```

**Comment by hadley** [comment]
Actually it looks like there's existing translation that works, but was put in the wrong location: `APPROX_QUANTILES(x, 2)[SAFE_ORDINAL(2)]`
