### ISSUE TITLE
Invalid project id - dbGetQuery

### ISSUE THREAD

**Issue by mauricioita** [r-dbi/bigrquery#428]
When using the  "dbGetQuery(conn = con, statement = sql_query)" function, I got this error message:

Erro: Invalid project ID 'XXXXXX-XXXXXX-XXXXXX'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash. [invalid] 

But in the error message it is displaying the billing account, actually. Though, when I do call "dbListTables(con)" everything goes fine.

**Comment by davidhoyer89** [comment]
I have the same issue.

**Comment by hadley** [comment]
If you can provide a reprex in a new issue, I can look into this further, but I suspect it's an instance of #486
