### ISSUE TITLE
Data Type: BIGNUMERIC support

### ISSUE THREAD

**Issue by eduardodrc** [r-dbi/bigrquery#435]
There is a new decimal type `BIGNUMERIC` available for Big Query tables (see [data types docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#decimal_types)). When we load a table with this type, we receive the error message:

```r
Running job 'example' [\]  1s
Complete
Billed: XX.XX MB
Downloading Y rows in Z pages.
Error in bq_parse_files(schema_path, page_paths, n = page_info$n_rows,  :                              
  Unknown type BIGNUMERIC
```

I think that we can just map BIGNUMERIC to float type (`Rcpp::DoubleVector`), but I'm not a master here. A similar request in the python SDK can help [python-bigquery/ issue 367](https://github.com/googleapis/python-bigquery/issues/367).

Thank you for the great work!

**Comment by dylanrussellmd** [comment]
Any update on this issue?

**Comment by hadley** [comment]
@dylanrussellmd if there were any updates, rest assured that they would appear here.

**Comment by kieran-mace** [comment]
any suggested workarounds for now, other than asking my database maintainer to change the data type?

**Comment by thomassie** [comment]
Would be nice to see some updates soon... ;)

**Comment by hadley** [comment]
@kieran-mace you could just cast to a supported type in your query

**Comment by thomassie** [comment]
That's actually the point here: you don't want to get into the process of changing the data type in a query/view, which is not that easily editable due to security measures. 
(Otherwise, I guess, this wouldn't be an issue here.)

**Comment by hadley** [comment]
@thomassie I understand it's a work around, but you can always do it, so it should unblock any specific problems.

**Comment by hadley** [comment]
I'd very much appreciate it if anyone could make me a reprex for this issue, i.e. some code that created a table with a BIGNUMERIC field and then tried to download from it. That would save me a little time and allow me to fix the underlying problem a little bit faster.

**Comment by hadley** [comment]
I think the easiest thing to do (which I'll do for all unknown types) is to just return the string data, so you can do what you will with it.
