### ISSUE TITLE
Upload strategy to avoid freeze or timeout: separate the df?

### ISSUE THREAD

**Issue by dsolito** [r-dbi/bigrquery#436]
Hello,

I have difficulties to upload dataframe to a table.
I found that spliting the dataframe by cols gives the ability to upload the complete dataframe.
Without that process freeze. If I wait enough I get an HTTP 408 Timout Error.

Are you concerned too ?
Any idea to resolve the issue ?

```r

target_project <- "project-1234"
target_dataset <- "dataset1"
target_table_1 <- paste0(format(Sys.time(), "%Y%m%d_%H%M%S"), "_1")
target_table_2 <- paste0(format(Sys.time(), "%Y%m%d_%H%M%S"), "_2")

bq_target <- bq_table(project = target_project, dataset = target_dataset, table = target_table_1)
job <- bq_perform_upload(bq_target, df[, c(1:30)])

bq_job_wait(job)

bq_target <- bq_table(project = target_project, dataset = target_dataset, table = target_table_2)
job <- bq_perform_upload(bq_target, df[, c(1, 31:length(p1))])

bq_job_wait(job)


```

**Comment by muschellij2** [comment]
I've gotten similar errors before as well.  Looked at https://stackoverflow.com/questions/59547299/bigrquery-r-package-error-408-request-timeout, but had no answers.  It's difficult to send a `reprex` for this as I don't know how to induce this behavior.

**Comment by tinoater** [comment]
I've had this error before too, restarting R usually fixes it. Can be really frustrating when it's mid way through a long running script.

**Comment by hadley** [comment]
Unfortunately it's going to be hard to fix without a reprex. Does this seem to occur with particularly long or particularly large datasets?

**Comment by hadley** [comment]
Since I haven't heard back in over a month, I'll assume it's no longer important to y'all. Please feel free to open an new issue with more details if you do encounter it again in the future.
