### ISSUE TITLE
Function not found: random; Did you mean rand?

### ISSUE THREAD

**Issue by mwilson19** [r-dbi/bigrquery#448]
Getting error when running simple query in dplyr syntax with `slice_sample` on bigquery sample data.  I am able to query if I replicate using standard SQL and the RAND() function. 

The error reads 

> Function not found: random; Did you mean rand? at [2:508] 

Maybe need to update backend with a new function? Looks like the `show_query` uses `RANDOM` not `RAND`.

```r
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(DBI)

# bigquery authentication
bq_auth(path = 'xxxx.json')

con <- dbConnect(
  bigrquery::bigquery(),
  project = "bigquery-public-data",
  dataset = "samples",
  billing = "billing"
)

# THIS WORKS
sql <- "SELECT *
         FROM `publicdata.samples.natality`
         WHERE RAND() < 0.001"

example <- dbGetQuery(con, sql2)
glimpse(example)


# THIS DOES NOT WORK
# use dbi/dplyr syntax
natality <- tbl(con, "natality")

nat <- 
  natality %>%
  slice_sample(n=50) %>%  
  collect()
```

**Comment by byapparov** [comment]
I believe this would be related to this PR: 
https://github.com/tidyverse/dbplyr/pull/673

**Comment by mgirlich** [comment]
I created a [PR](https://github.com/tidyverse/dbplyr/pull/749) in `dbplyr` that exports the generic `sql_random()`

```r
# registered onLoad
sql_random.BigQueryConnection <- function(con) {
  sql_expr(RAND())
}
```
