### ISSUE TITLE
How to force bigrquery to re-authorize

### ISSUE THREAD

**Issue by abalter** [r-dbi/bigrquery#449]
Brief description of the problem

I have an RStudio Server instance running on a GCP VM. I'm getting the following error

``` r
library(tidyverse)
library(magrittr)
#> 
#> Attaching package: 'magrittr'
#> The following object is masked from 'package:purrr':
#> 
#>     set_names
#> The following object is masked from 'package:tidyr':
#> 
#>     extract
library(bigrquery)

bq_deauth()
bq_auth(email="ariel.balter@providence.org")
bq_conn = dbConnect(
  bigquery(),
  project = "?????????????",
  dataset = "balter"
)


tbl(bq_conn, "bigquery-public-data.austin_311.311_service_requests")
#> # Source:   table<bigquery-public-data.austin_311.311_service_requests> [?? x
#> #   24]
#> # Database: BigQueryConnection
#>    unique_key  complaint_type complaint_descrip… owning_departme… source  status
#>    <chr>       <chr>          <chr>              <chr>            <chr>   <chr> 
#>  1 19-00243479 DRVECTRL       Creek & Pond Vege… Watershed Prote… Phone   Closed
#>  2 20-00440346 SCHOOLZ2       School Zone Flash… Transportation   Spot31… Closed
#>  3 19-00492617 ACCOYTE        Coyote Complaints  Animal Services… Phone   Closed
#>  4 20-00349773 ACCOYTE        Coyote Complaints  Animal Services… Phone   Closed
#>  5 19-00140825 SBSTRES        Street Resurfacing Public Works     Phone   Closed
#>  6 19-00399194 ACCOYTE        Coyote Complaints  Animal Services… Phone   Closed
#>  7 19-00424223 ACCOYTE        Coyote Complaints  Animal Services… Phone   Closed
#>  8 19-00215436 DRSDPIPE       Storm Drain Pipe … Watershed Prote… Phone   Closed
#>  9 19-00461812 STREETL1       Street Lights New  Austin Energy D… Phone   Closed
#> 10 20-00333823 ACCOYTE        Coyote Complaints  Animal Services… Phone   Closed
#> # … with more rows, and 18 more variables: status_change_date <dttm>,
#> #   created_date <dttm>, last_update_date <dttm>, close_date <dttm>,
#> #   incident_address <chr>, street_number <chr>, street_name <chr>, city <chr>,
#> #   incident_zip <int>, county <chr>, state_plane_x_coordinate <chr>,
#> #   state_plane_y_coordinate <dbl>, latitude <dbl>, longitude <dbl>,
#> #   location <chr>, council_district_code <int>, map_page <chr>, map_tile <chr>
tbl(bq_conn, "??????????.s.balter.gnomad_v2_select_allele_frequencies")
#> Error: Access Denied: Table ??????????.gnomad_v2_select_allele_frequencies: Permission bigquery.tables.get denied on table ??????????.:balter.gnomad_v2_select_allele_frequencies (or it may not exist). [accessDenied]
```

<sup>Created on 2021-05-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

However, this code runs fine on my local machine and in AI notebooks.

Also, in the RStudio terminal I can run `gcloud auth login`, set up auth.

So the VM can connect to data in my project, but for some reason `bigrquery` can't auth.

How can I reset the auth information in `bigrquery`?

**Comment by jennybc** [comment]
Also: what is your intent ... to use the regular OAuth2 web flow + gargle's token cache or to use Application Default Credentials (ADC)? Above I see evidence of both.

`bq_auth()` is associated with "regular OAuth2 web flow + gargle's token cache".

"Also, in the RStudio terminal I can run gcloud auth login, set up auth, and then ..." is associated with ADC.

Which do you mean to use?

**Comment by abalter** [comment]
@jennybc  I did try that, as well as deleting the _.httr_oauth_ file. 

On my local machine as well as AI notebook when I do as you suggested I get a query in the terminal to choose an email, then a browser window opens for authentication.

Any other ideas?

**Comment by jennybc** [comment]
I can tell from the above that this is not the currently released version of gargle. So you should update gargle before you do anything else.

Also you should not call gargle directly, i.e. you should not call `gargle::credentials_user_oauth2()`. Above it's resulting in a token that has essentially no scopes, which is why (at least in this case), you can't do anything with the token on BigQuery. You should work through `bq_auth()`, which adds the scopes needed to do BigQuery work.

**Comment by abalter** [comment]
```
(base) balter@ab-rstudio:~$ conda list | grep gargle
r-gargle                  1.1.0             r40hc72bb7e_0    conda-forge
```

**Comment by abalter** [comment]
Bumping this---still having the same problem. The only time I can't properly authorize to bigquery is when I'm working on a VM actually on GCP.

**Comment by abalter** [comment]
Still having this problem. RStudio Server in cloud VM, and can't authenticate.

**Comment by abalter** [comment]
https://stackoverflow.com/questions/71327718/cant-authorize-bigrquery-on-google-cloud-vm-but-can-on-local-machine/71356377#71356377

**Comment by abalter** [comment]
https://github.com/r-lib/gargle/issues/138#issuecomment-1114133838
