### ISSUE TITLE
Deprecate `max_results` argument of `bq_table_download()` in favour of `n_max`

### ISSUE THREAD

**Issue by jennybc** [r-dbi/bigrquery#457]
I forgot to get your view on this @Hadley:

https://github.com/r-dbi/bigrquery/pull/456/files#r676976833

I think the `max_results` argument of `bq_table_download()` is unfortunately named. We absolutely use it in the spirit of `n_max` in other packages/functions and the `page_size` argument is what might actually be sent as `maxResults` query parameter, in API-speak. It's pretty confusing.

If I deprecated `max_results` properly, what do you think?

Where "deprecated it properly" means: <https://lifecycle.r-lib.org/articles/communicate.html#renaming-an-argument>

**Comment by hadley** [comment]
Yeah, proper deprecation sounds good to me.

**Comment by hadley** [comment]
Looks like this was done in #456
