### ISSUE TITLE
Unable to create partitioned tables...again

### ISSUE THREAD

**Issue by wenhsinhu** [r-dbi/bigrquery#460]
Hi, 

This issue is related to #359.

I tried to generate a partitioned table with the solutions within the above issue and encountered some problems. Not sure if this is caused by version updates.

1. Specifiy the fields as json:
for a json like this:
``` r
name = c('date','dummy_columnA','dummy_columnB')
type = c('DATE','STRING','INT64')
schema = jsonlite::toJSON(as.data.frame(cbind(name,type)))
schema
#> [{"name":"date","type":"DATE"},{"name":"dummy_columnA","type":"STRING"},{"name":"dummy_columnB","type":"INT64"}]
```
I tried the following scripts:
``` r
bigrquery::bq_table_create(x = bq_table, fields = schema,
            timePartitioning = list(timepartitioning = list(type='DAY', field= 'date'))
            )
```
an error returned
```r
#> Error in UseMethod("as_bq_fields"): no applicable method for 'as_bq_fields' applied to an object of class "json"
```

2. Specify the field as bq_fields
```r
bq_fields <- bigrquery::as_bq_fields(list(bigrquery::bq_field('date','DATE'),
                                          bigrquery::bq_field('dummy_columnA','STRING'),
                                          bigrquery::bq_field('dummy_columnB','INT64')))


bigrquery::bq_table_create(x = bq_table, fields = bq_fields,
                timePartitioning = list(timepartitioning = list(type='DAY', field= 'date'))
)

```
A partitioned table is generated, whereas the field setting is not working.

![截圖 2021-08-10 上午11 21 29](https://user-images.githubusercontent.com/18327156/128807543-f275cbb3-70cc-45db-ae9e-3ecf3cc1c4f1.png)

**NOTES:**
The following bq commend works for me:
```
bq mk \
--schema=date:DATE,dummy_colA:STRING,dummy_colB:INTEGER \
 --time_partitioning_field=date \
 --time_partitioning_type=DAY bi_report.dummy_user_profile
```
![截圖 2021-08-10 下午12 22 35](https://user-images.githubusercontent.com/18327156/128807873-03a57828-ea1a-49f3-9aea-1af906abdfd8.png)

**Comment by byapparov** [comment]
You have double layer of timepartitoning lists. Can you double check the example from the previous issue

**Comment by hadley** [comment]
Closing this since it's been 2 years without further communication.
