### ISSUE TITLE
`bq_table_download()` empirically chosen page size

### ISSUE THREAD

**Issue by arohland** [r-dbi/bigrquery#461]
I am using the bq_table_download function to download from a nested dataset, using the new empirically chosen page_size argument from bigrquery 1.4. The automatically chosen page_size seems to be too big for at least some pages and I receive an error that not all rows were downloaded. I guess some later pages have more nested entries and go across the chosen page_size.

I can specify a page_size manually to avoid the bug, but have to be quite conservative which slows down the downloads. I am also aware that this is not the recommended use of bq_table_download to download big datasets, but it works quite conveniently in our setup.

I could reproduce the problem with a nested public dataset.  It takes a while to run as there are a lot of rows to download.

``` r
library(bigrquery)
library(magrittr)

bigrquery::bq_auth()
#> ! Using an auto-discovered, cached token.
#>   To suppress this message, modify your code or options to clearly consent to
#>   the use of a cached token.
#>   See gargle's "Non-interactive auth" vignette for more details:
#>   <https://gargle.r-lib.org/articles/non-interactive-auth.html>
#> ℹ The bigrquery package is using a cached token for
#>   '************@********'.
bigrquery::bq_project_query(
    x          = bq_test_project(),
    query      = "SELECT * FROM `bigquery-public-data.samples.github_nested`"
  ) %>%
  bigrquery::bq_table_download()
#> Error in bq_parse_files(schema_path, c(path_first_chunk, chunk_plan$dat$path), : 2541639 rows were requested, but only 2530071 rows were received.
#>   Leave `page_size` unspecified or use an even smaller value.
```

<sup>Created on 2021-08-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I think this is a success for the new approach since you're learning that the data is corrupted and being encouraged to pick a smaller page size. So I'm not quite sure what the issue is.

**Comment by arohland** [comment]
It's certainly a success in that we know we receive corrupted data. Before we hardcoded a page_size and probably received corrupted downloads now and then. So I'm very grateful for the update!
I just assumed that the empirically chosen page_size would prevent this from happening, by somehow readjusting the size. Probably a misunderstanding on my side, as I was surprised to see the error appear.

**Comment by jennybc** [comment]
We use one page size (75% of the size of the first page, where size is determined by the data).

And yeah there are undoubtedly datasets where complexity and sparsity combine to mean that even that page size is too large for some slice of the data.

At this point, you really do have to choose between using another method entirely or using an even smaller, manually set page size.

**Comment by arohland** [comment]
FYI: For anyone running into the same problems. I ended up writing a wrapper function around bq_table_download that catches failing downloads, reduces the page size and retries the download. This way it works reliably in our dashboards :)
```
#' Wrapper around bq_table_download
#'
#' @description
#' This function downloads a bq_table and reduces the automatically chosen page
#' size if the download fails.
#'
#' @param .bq_table A bq_table object as provided by bq_project_query
#' @param .page_size Integer: Page size argument for downloading data
#' @param .quiet Flag if function should send messages. FALSE necessary for
#' reducing page_size
#' @param .tries Integer: Amount of times the tryCatch should reduce page_size
#'
#' @return
#' A `tibble` object containing the requested data from BigQuery

bq_download_retry <- function(.bq_table,
                              .page_size,
                              .quiet = FALSE,
                              .tries = 4) {
  results <- NULL
  try <- 1
  
  while(is.null(results) & try < .tries) {
    tryCatch(
      {
        logs <- ""
        # WithCallingHandlers can manage Errors/Messages displayed by code. Is used
        # here to capturing the messages displayed by the function
        withCallingHandlers(
          {
            try <- try + 1
            results <- bigrquery::bq_table_download(
              x         = .bq_table,
              page_size = .page_size,
              quiet     = .quiet
            )
          },
          message = function(msg) {
            # <<- (Super assignment operator) used as logs need to be used in different
            # environment
            logs <<- paste(logs, msg)
          }
        )
      },
      error = function(err) {
        .page_size <<- stringr::str_extract(
          stringr::str_flatten(logs),
          "(?<=\\(up\\sto\\)\\s)\\d+[:punct:]?\\d+"
        ) %>%
          stringr::str_replace("[:punct:]", "") %>%
          as.integer() %>%
          "*"(0.5) %>%
          round()
        
        message("Download failed: Page size will be reduced! \n", err)
        message("Start try ", try, ". Page size set to ", .page_size, ".")
      }
    )
  }

  return(results)
}
```

**Comment by calbach** [comment]
I just hit this issue today as well. Perhaps I'm missing some context but this seems like a bug:

1. As a bigrquery user, it seems incorrect that I should have to hand-tune page_size depending on the nature my specific query results. This affects code portability on different datasets and also reproducibility, as I don't think the BigQuery API makes any guarantees around consistent page size behavior. This seems like a low-level detail that the library would ideally have a reasonable default behavior for (especially when I'm not specifying any page_size parameter).
2. In terms of implementation, why would this case be treated as an error? https://github.com/r-dbi/bigrquery/blob/504185da32f63f83cbd38a022575df7797ba7504/R/bq-download.R#L149 ; given the nature of `max_results` in the BigQuery API, the case where `len(results) < max_results` is expected. Is there a reason this scenario cannot just be accounted for in the implementation?
