### ISSUE TITLE
dbFetch method cannot be called with quiet = TRUE

### ISSUE THREAD

**Issue by hdshea** [r-dbi/bigrquery#463]
A small issue - important for deploying though.

The `dbFetch` method (R/dbi-results.R) cannot be called with the quiet option.  `dbFetch` is called with a `res` object, not a `conn` object and so does not have access to `conn@quiet`.  It also does not (currently) take a `quiet` parameter.  So, there is no way to make the internal call to `bq_table_download` (R/bq-download.R) employing either of the above options, and `bq_table_download` has the default `quiet` parameter set to `NA`.

```r
if (gargle:::secret_can_decrypt("bigrquery")) {
  json <- gargle:::secret_read("bigrquery", "bigrquery-testing.json")
  bigrquery::bq_auth(path = rawToChar(json))
}
con <- DBI::dbConnect(
  bigquery(),
  project = bq_test_project(),
  dataset = "basedata",
  bigint = "integer"
)

res <- bigrquery::dbSendQuery(con, "SELECT cyl, mpg FROM mtcars")
rval <- bigrquery::dbFetch(res)
bigrquery::dbClearResult(res)

bigrquery::dbDisconnect(con)
```

Gives this output:

```r
#> Downloading first chunk of data.
#> First chunk includes all requested rows.
```

**Comment by hdshea** [comment]
Apologies, the call to DBI::dbConnect should have a quiet = TRUE in it.

**Comment by joranE** [comment]
Discovered this myself recently. It really should be a trivial fix. I think you just need to include `quiet = res@quiet` in the `bq_table_download` call when defining the `dbFetch` method at line 115 in dbi-result.R
