### ISSUE TITLE
Unable to disconnect with `DBI::dbDisconnect`

### ISSUE THREAD

**Issue by dylanrussellmd** [r-dbi/bigrquery#470]
I am unable to disconnect from a `BigQueryConnection`.

I would expect behavior similar to below:

```r
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbIsValid(con) # TRUE
dbDisconnect(con)
dbIsValid(con) # FALSE

```
Instead, there is the following behavior:

```r
billing <- bigrquery::bq_test_project()
con <-   DBI::dbConnect(
    bigrquery::bigquery(),
    project = "publicdata",
    dataset="samples",
    billing = billing
  )
DBI::dbIsValid(con) # TRUE
DBI:dbDisconnect(con) 
DBI::dbIsValid(con) # TRUE

```
On a related note, if I simply reassign `con`, is a connection safely terminated?
```
con <- NULL

**Comment by hadley** [comment]
bigrquery doesn't have any state that needs to be disconnected so these methods don't do anything.
