### ISSUE TITLE
Need a workaround for array_agg

### ISSUE THREAD

**Issue by abalter** [r-dbi/bigrquery#482]
I was able to create my own `unnest` function, but now I need something the equivalent of `dplyr::nest` or `array_agg` in bigquery.

The the reprex below, I show what I would like to do using a raw tibble. Then I try various approaches to replicate it on a lazy table.

Brief description of the problem

``` r
library(bigrquery)
library(tidyverse)
library(knitr)

projname = "eacri-genomics"
email="ariel.balter@providence.org"

bq_deauth()
bq_auth(email=email)


### Now BigQuery
conn = dbConnect(
  bigquery(),
  project = projname
)

### Create lazy table
tb_bq = 
  tbl(conn, "bigquery-public-data.austin_bikeshare.bikeshare_trips") %>% 
  select(start_station_id, end_station_id)
#> Auto-refreshing stale OAuth token.

### Get ~1000 random rows
N = tb_bq %>% count() %>% pull(n)
tb_bq = tb_bq %>% filter(rand() < 1000/N)

### collect
tb = tb_bq %>% collect()
tb %>% head(10) %>% kable()
```

| start_station_id | end_station_id |
|-----------------:|:---------------|
|             2546 | 2546           |
|             2546 | 1007           |
|             2546 | 1008           |
|             2536 | 2545           |
|             2541 | 2541           |
|             2823 | 2823           |
|             3685 | 3293           |
|             3294 | 3294           |
|             4058 | 4058           |
|             4055 | 4055           |

``` r
tb2 =
  tb %>% 
  group_by(start_station_id) %>% 
    nest(end_stations = end_station_id) %>% 
  ungroup()

tb2 %>% head(5) %>% kable()
```

| start_station_id | end_stations                            |
|-----------------:|:----------------------------------------|
|             2546 | 2546, 1007, 1008, 2547                  |
|             2536 | 2545, 2496, 2542, 2569, 2711            |
|             2541 | 2541, NA , 2497, 2538, 2539, 2547, 2707 |
|             2823 | 2823, 2542, 2570, 3513                  |
|             3685 | 3293, 2575                              |

``` r
tb3 =
  tb %>% 
  group_by(start_station_id) %>% 
    mutate(end_stations = list(end_station_id)) %>% 
  ungroup() %>% 
  select(-end_station_id)

tb3 %>% head(5) %>% kable()
```

| start_station_id | end_stations                            |
|-----------------:|:----------------------------------------|
|             2546 | 2546, 1007, 1008, 2547                  |
|             2546 | 2546, 1007, 1008, 2547                  |
|             2546 | 2546, 1007, 1008, 2547                  |
|             2536 | 2545, 2496, 2542, 2569, 2711            |
|             2541 | 2541, NA , 2497, 2538, 2539, 2547, 2707 |

``` r
tb_bq = 
  tbl(conn, "bigquery-public-data.austin_bikeshare.bikeshare_trips") %>% 
  select(start_station_id, end_station_id)

N = tb_bq %>% count() %>% pull(n)

tb_bq = tb_bq %>% filter(rand() < 1000/N)

tb_bq %>% count()
#> # Source:   lazy query [?? x 1]
#> # Database: BigQueryConnection
#>       n
#>   <int>
#> 1   993

tb_bq %>% head(5) %>% collect() %>% kable()
```

| start_station_id | end_station_id |
|-----------------:|:---------------|
|             2823 | 2823           |
|             2536 | 2568           |
|             2546 | 2546           |
|             1007 | 2564           |
|             2568 | 2546           |

``` r
tb2_bq = 
  tb_bq %>% 
  group_by(start_station_id) %>% 
    nest(end_stations = end_station_id) %>% 
  ungroup() 
#> Error in UseMethod("nest"): no applicable method for 'nest' applied to an object of class "c('tbl_BigQueryConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"

tb2_bq %>% head(5) %>%collect() %>% kable()
#> Error in head(., 5): object 'tb2_bq' not found

tb3_bq = 
  tb_bq %>% 
  group_by(start_station_id) %>% 
    mutate(end_stations = list(end_station_id)) %>% 
  ungroup() %>% 
  select(-end_station_id)

tb3_bq %>% head(5) %>% collect() %>% kable()
#> Error: Job 'eacri-genomics.job_I3-xCD2x5frvGW6qL_u6D8OYjjTv.US' failed
#> x Function not found: list at [2:52] [invalidQuery]

tb4_bq = 
  tb_bq %>% 
  group_by(start_station_id) %>% 
    mutate(end_stations = array_agg(end_station_id)) %>%
  ungroup() %>%
  select(-end_station_id)

tb4_bq %>% head(5) %>% collect() %>% kable()
#> Error: Job 'eacri-genomics.job_sxsYCd0caaZVK8gICkvQ4atQwmIQ.US' failed
#> x SELECT list expression references column start_station_id which is neither grouped nor aggregated at [2:14] [invalidQuery]
```

<sup>Created on 2022-01-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by samterfa** [comment]
+1 for this.

**Comment by hadley** [comment]
Could you please work on making a simpler reprex, along the lines of https://github.com/r-dbi/bigrquery/issues/485#issuecomment-1792359237?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
