### ISSUE TITLE
BigQuery uses FLOAT64, not FLOAT

### ISSUE THREAD

**Issue by joranE** [r-dbi/bigrquery#483]
---

My BigQuery instance only appears to acknowledge a type of FLOAT64 while bigrquery appears to, when uploading data, translate SQL casting to FLOAT.

I'm on  R 4.1.1, Windows 10 x64 using bigrquery 1.4.0 and DBI 1.1.1.

```r
library(tidyverse)
library(bigrquery)
library(DBI)

con <- dbConnect(bigrquery::bigquery(),
project = '***',
dataset = '***',
billing = '***')

> dbCreateTable(conn = con,name = 'mtcars',fields = mtcars)
Error: Job '******' failed
Type not found: FLOAT at [2:9] [invalidQuery]
In addition: Warning message:
In class(obj) <- c("scalar",class(obj)) : 
  Setting class(x) to multiple strings ("scalar","SQL", ...): result will no longer be an S4 object 
```

I have looked at the generated SQL sent to BigQuery in the BigQuery console and confirmed that *any* CREATE table statement using FLOAT fails with this exact error in BigQuery itself, whereas is works fine when I run it in BigQuery using a type of FLOAT64.

If I create the table in BigQuery first using FLOAT64, bigrquery will successfully insert mtcars.

I'm very new to BigQuery (and I have no admin control or access to my BigQuery, it's a work thing) so it's possible that this is particular to our BigQuery account, I'm not sure. But all of the [documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric_types) I look for on data types in BigQuery only reference a FLOAT64 type not a FLOAT type. This makes me wonder why bigrquery is translating SQL using a FLOAT data type, not FLOAT64.

UPDATE: I've determined that `dbWriteTable` works fine, and somehow creates the table with FLOAT (not FLOAT64) columns in the resulting BigQuery table, but for some reason `dbCreateTable` chokes on declaring a column with type FLOAT instead of FLOAT64.

**Comment by hadley** [comment]
Thanks for spotting this!

**Comment by hadley** [comment]
Actual problem is that we needed a `dbCreateTable()` method that used the BQ api directly.
