### ISSUE TITLE
dbWriteTable ignores `billing` argument set in dbConnect

### ISSUE THREAD

**Issue by csmc88** [r-dbi/bigrquery#486]
A coworker was working interacting with our production warehouse hosted in BigQuery through R using this library. She encountered issues when attempting to move her code from sandbox to the development environment. The error that appeared asked her to have `roles/bigquery.jobUser` in the development project.

Our architecture for prod/dev is storage based. All Query executions go to other projects for cost-allocation. With that in mind, the following code failed.

```r
# test_data_object is an R dataframe
bq_auth(email = "person@company.com")
con <- dbConnect(
  bigrquery::bigquery(),
  project = "warehouse-storage-dev",
  billing = "query-slot-resources"
)
dbWriteTable(con, "warehouse-storage-dev.test_dataset.test_table", test_data_object)
```

The above failed with `[AccessDenied] User does not have bigquery.jobs.create in warehouse-storage-dev` And the following code was the required fix it.

```r
# test_data_object is an R dataframe
bq_auth(email = "person@company.com")
con <- dbConnect(
  bigrquery::bigquery(),
  project = "warehouse-storage-dev",
  billing = "query-slot-resources"
)
dbWriteTable(con, "warehouse-storage-dev.test_dataset.test_table", test_data_object, 
             billing = "query-slot-resources") #Adding the billing AGAIN during the write operation
```

It took a few tests while debugging to figure out that `dbWriteTable` is ignoring the value for billing project set in `dbConnect`. Expected behavior is that once a billing project is defined in the connection object, it is the project used

**Comment by hadley** [comment]
Indeed, it looks like a lot of the DBI wrappers fail to correctly set the `billing` field.

**Comment by hadley** [comment]
But it looks like only `dbWriteTable()` needs it.
