### ISSUE TITLE
Error with bq_job_meta

### ISSUE THREAD

**Issue by mihagazvoda** [r-dbi/bigrquery#488]
When running `bigrquery::bq_job_meta(job, fields = "statistics/totalBytesProcessed")` I get 
```
Error in curl::curl_fetch_memory(url, handle = handle): Error while processing content unencoding: invalid distance too far back
```
error. However, my coworker doesn't get it. We both use the 1.4 version of the package. The function works (and returns `totalBytesProcessed` in a nested list) if I skip the `fields` argument. 

``` r
job <- bigrquery::bq_project_jobs(YOUR_PROJECT, page_size = 1)[[1]]
#> Warning: Only first 1 results retrieved. Adjust with `max_pages` and `page_size`
#> parameters.
bigrquery::bq_job_wait(job)
bigrquery::bq_job_meta(job, fields = "statistics/totalBytesProcessed")
#> Error in curl::curl_fetch_memory(url, handle = handle): Error while processing content unencoding: invalid distance too far back
```

<sup>Created on 2022-03-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I get this error also when using `bq_job_meta` on other jobs.

**Comment by hadley** [comment]
Can you please give me more of a reprex? There's not much to go on in what you have there.

**Comment by mihagazvoda** [comment]
Hi Hadley,

Please, can you close the issue, I don’t remember it anymore.

Thank you,
Miha
