### ISSUE TITLE
Suggstion for improvement: bigrquery::bq_auth throw an error when invalid path is specified to json file.

### ISSUE THREAD

**Issue by EdwinTh** [r-dbi/bigrquery#490]
*Problem*
User provides an invalid path to  a json keyfile at the `path` argument of `bigrquery::bq_auth`.

```r
bigrquery::bq_auth(path = "/nonexisting/path/to/keyfile.json")
```

*Current behavior*:
The user is prompted to select an email address for authentication, as if there was no argument provided altogether. Calling the function with no arguments also give this interactive selection. (When the user never logged in before, I assume they will be directed to a login in the browser, but I have no way to test this since I have logged in before).  

*Proposed behavior*
Throw an error message that the path to the json file does not exist.

**Comment by jennybc** [comment]
This is not so easy to do within the current design. Part of how functions like `bq_auth()` work automagically with various methods of auth is try `tryCatch()` a bunch of methods and go with the first one that works. But the downside is that you *don't* get verbose output about the ones that are failing on the way down.

**Comment by EdwinTh** [comment]
I see, than it is indeed a challenge to distinguish between a 'genuine' error and an expected one. You could maybe check the validity of the path if it is provided using `file.exist()` before going into `tryCatch()` cascade. Not sure if this is feasible / fits in with the design of the package.

**Comment by jennybc** [comment]
The `path` argument of `bq_auth()` eventually gets passed as the `path` argument of `gargle::credentials_service_account()`. By design, `path` can be a path to the JSON representing a service account or a JSON string.

https://gargle.r-lib.org/reference/credentials_service_account.html

This is intentional and is a feature that gets used.

The general advice for troubleshooting advice for a gargle-using package is here:

https://gargle.r-lib.org/articles/troubleshooting.html

> ... gargle is designed to try a bunch of auth methods (many of which will fail) and persist doggedly until one succeeds. If none succeeds, gargle tries to guide the user through auth or, in a non-interactive session, it throws an error.
>
> If you need to see all those gory details, set the “gargle_verbosity” option to “debug” and you’ll get much more output as gargle works through various auth approaches.
