### ISSUE TITLE
Can no longer authenticate interactively (really at all).

### ISSUE THREAD

**Issue by abalter** [r-dbi/bigrquery#491]
I can no longer get `bigrquery` to authenticate me. I have limited options through my organization. For instance, I cannot create a service account token. In the past, I have used the method where I get a prompt listing my google emails, I select one, and then authenticate through the browser. This is no longer functioning.

## WSL2 Ubuntu
```sh
(base) balter@spectre:~$ bq ls

Welcome to BigQuery! This script will walk you through the
process of initializing your .bigqueryrc configuration file.

First, we need to set up your credentials if they do not
already exist.

Setting project_id ?????-genomics as the default.

BigQuery configuration complete! Type "bq" to get started.

       datasetId
 ---------------------
  ETL
  balter
  cloud_inventory
...
...
(base) balter@spectre:~$ gcloud projects list
PROJECT_ID               NAME                     PROJECT_NUMBER
...
...
?????-genomics           ?????-genomics          ########
...
...
(base) balter@spectre:~$ R -q
> library(bigrquery)
> bq_auth(email="ariel.balter@providence.org")
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Error: Can't get Google credentials.
Are you running bigrquery in a non-interactive session? Consider:
  * Call `bq_auth()` directly with all necessary specifics.
> bq_projects()
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Error: Can't get Google credentials.
Are you running bigrquery in a non-interactive session? Consider:
  * Call `bq_auth()` directly with all necessary specifics.
```

## Windows CMD
```
C:\WINDOWS\system32>R -q
> library(bigrquery)
> bq_projects()
The bigrquery package is requesting access to your Google account.
Select a pre-authorised account or enter '0' to obtain a new token.
Press Esc/Ctrl + C to cancel.

1: ariel.balter@providence.org

Selection: 1
Auto-refreshing stale OAuth token.
Error in `signal_reason()`:
! Request had insufficient authentication scopes. [insufficientPermissions]
Run `rlang::last_error()` to see where the error occurred.
>
```

**Comment by jennybc** [comment]
> Request had insufficient authentication scopes. [insufficientPermissions]

These OAuth consent screens have changed in the past several months / year and you should look carefully to see if there is a check box there, in which you need to explicitly grant the app permission to use specific scopes on your behalf. If there is, and you don't check it, you'll get a token but it won't have the scopes needed to do BigQuery work. That is my hunch, based on this error.

**Comment by jennybc** [comment]
A lot of improvements have happened in gargle since this issue was opened. I recommend you update gargle and see if these problems have resolved. Even if not, hopefully we also reveal some more useful debugging into when you run with `options(gargle_verbosity = "debug")`. Please open a new issue if you're still seeing this with gargle >= 1.4.0.

**Comment by obarisk** [comment]
I found that when 

- with gcloud auth login
- without gcloud auth application-default login

with gargle. possibly `insufficientPermissions`

A better solution should be delete all gargle cache
run `gcloud auth login` and `gcloud auth application-default login`

no more auth via gargle. calling the apis directly.
