### ISSUE TITLE
Could I pass allow_large_results = True to avoid the error, Response too large to return?

### ISSUE THREAD

**Issue by ujlim** [r-dbi/bigrquery#494]
We need 'allow_large_results = TRUE' to get query's results larger than 10 GB , which is the limit of bigquery. The way to remove the limit is described in https://cloud.google.com/bigquery/docs/samples/bigquery-query-legacy-large-results#bigquery_query_legacy_large_results-python. There are practices of Python, node.js but R.

I tried but failed as like [1]

```
[1]
sqlload = "select * from 'gcp-project.DLKL2BL22.KOTI_TRIP WHERE BASE_DT = DATE('2022-03-24')
project_id='gcp-project'
tb = bq_project_query(project_id, sqlload, allow_large_results = TRUE)
#tb = bq_project_query(project_id, sqlload)

Error in `bq_job_wait()`:
! Job 'gcp-project.job_sHMPaoifpeowij.asia-northeast3' failed
X Response too large to return. Consider specifying a destination table in your job configuration. For more details, see https://cloud.google.com/bigquery/troubleshooting-errors [responseTooLarge]
Traceback:

1. bq_project_query(project_id, sqlload, allow_large_results = TRUE)
2. bq_job_wait(job, quiet = quiet)
3. rlang::abort(c(paste0("Job '", if (!isTRUE(quiet)) x, "' failed"), bullets))
4. signal_abort(cnd, .file)
```

**Comment by hadley** [comment]
Could you attempt to explain how to recreate this error using a large public dataset? I don't regularly use bigquery so anything you can do to help me reproduce the problem is useful.

**Comment by hadley** [comment]
Actually, it sounds like you should start by following the advice in the error message and provide a `destination_table`.
