### ISSUE TITLE
Avoid calling encodeString() in dbQuoteIdentifier()

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/bigrquery#497]
to avoid escaping backslashes.

``` r
requireNamespace("bigrquery")
#> Loading required namespace: bigrquery
DBI::dbQuoteIdentifier(new("BigQueryConnection", use_legacy_sql = FALSE), "a\\b")@.Data
#> [1] "`a\\\\b`"
```

<sup>Created on 2022-06-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Recent reprex:

``` r
library(bigrquery)

con <- DBI::dbConnect(bigquery(), project = bq_test_project())
DBI::dbQuoteIdentifier(con, "a\\b")
#> <SQL> `a\\b`
```

<sup>Created on 2023-11-08 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

I think this is correct. Quoted identifiers use the same escapes as string literals (https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#quoted_identifiers) and string literals use backslash escaping (https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#string_and_bytes_literals). This seems to be a deviation from the historical SQL convention of doubling up quotes.
