### ISSUE TITLE
Error in api-table documentation example

### ISSUE THREAD

**Issue by calebwpalmer** [r-dbi/bigrquery#506]
Running `bq_table_create()` in the `api-table` documentation results in the error:

Error in UseMethod("as_bq_table") : 
  no applicable method for 'as_bq_table' applied to an object of class "bq_dataset"

This is because "mtcars" is assigned to the fields argument. A simple fix is to change ds to bq_table(ds,"mtcars"). This mirrors the examples in `api-dataset`.

```r
if (bq_testable()) {
ds <- bq_test_dataset()

bq_mtcars <- bq_table_create(
  ds,
  "mtcars",
  friendly_name = "Motor Trend Car Road Tests",
  description = "The data was extracted from the 1974 Motor Trend US magazine",
  labels = list(category = "example")
)
}
```

**Comment by hadley** [comment]
Ooops, a lot of this example was wrong. I'll also look into the build chain to make sure these are getting run.
