### ISSUE TITLE
Error in strsplit() on "head-only" queries

### ISSUE THREAD

**Issue by calebwpalmer** [r-dbi/bigrquery#509]
When running a "head-only" query, the following error is returned

`Error in strsplit(name, ".", fixed = TRUE) : non-character argument`

Drilling down, the error occurs in dbplyr.R line 113: https://github.com/r-dbi/bigrquery/blob/73781ba90477025653ef2d10ee825bee7f407133/R/dplyr.R#L113
op_table() eventually arrives at op_table.lazy_select_query(), which returns a list instead of a character string. https://github.com/r-dbi/bigrquery/blob/73781ba90477025653ef2d10ee825bee7f407133/R/dplyr.R#L192 returns a list instead of the name.

This error does not occur when explicitly calling collect()

```r
if (bq_testable()) {
  ds <- bq_test_dataset(name = "bigrquery_test")

  bq_mtcars <- bq_table(ds, "mtcars")
  bq_table_exists(bq_mtcars)
  
  bq_table_upload(bq_mtcars, mtcars)
  
  library(dplyr)
  con <- bigrquery::dbConnect(bigrquery::bigquery(),
                              bigint = "character",
                              project = Sys.getenv("BIGQUERY_TEST_PROJECT"))
  
  test <- tbl(con, "bigrquery_test.mtcars")
  
  # strsplit error
  test

  # no strsplit error
  collect(test)
  
  }
```

**Comment by thomasjohnflaherty** [comment]
Any updates here? This also affects functions like `glimpse()`.

**Comment by issactoast** [comment]
I still have the same error when I try to print head of the db table or glimpse(). Other codes work fine, tho.

> head(ord_prd_data)
Error in strsplit(name, ".", fixed = TRUE) : non-character argument

> ord_prd_data |> glimpse()
Rows: ??
Error in strsplit(name, ".", fixed = TRUE) : non-character argument

Version info 
dbplyr 2.3.2.9.000
bigrquery 1.4.1
R 4.2.2
