### ISSUE TITLE
Documentation request: Is bq_deauth the opposite of bq_auth?

### ISSUE THREAD

**Issue by MichaelChirico** [r-dbi/bigrquery#522]
Another companion issue to https://github.com/tidyverse/googledrive/issues/412, _mutatis mutandis_ `googledrive::drive_auth()`/`googledrive::drive_deauth()` ↔️ `bigrquery::bq_auth()`/`bigrquery::bq_deauth()`.

In this case, the existing documentation gets closer to confirming `bq_deauth()` can be used to undo `bq_auth()`:

> bigrquery is not usable in a de-authorized state... calling bq_deauth() only clears the token

but I think we can still be more explicit

**Comment by jennybc** [comment]
I see these docs for `bq_deauth()`:

> Clears any currently stored token. The next time bigrquery needs a token, the token acquisition process starts over, with a fresh call to [bq_auth()](http://127.0.0.1:31031/help/library/bigrquery/help/bq_auth) and, therefore, internally, a call to [gargle::token_fetch()](http://127.0.0.1:31031/help/library/gargle/help/token_fetch). Unlike some other packages that use gargle, bigrquery is not usable in a de-authorized state. Therefore, calling bq_deauth() only clears the token, i.e. it does NOT imply that subsequent requests are made with an API key in lieu of a token.

What questions does this leave about what `bq_deauth()` does?

**Comment by MichaelChirico** [comment]
It describes what it does, I think we can expound on _how to use it_. Currently we're left reading between the lines a bit -- is "clearing the token" equivalent to re-setting the state? At a glance it's hard to know without understanding a lot more detail about what authorization entails for this API / this package.

I think we can add something like a sentence explicitly saying "This is therefore an inverse of `bq_auth()` that can be used to re-set the auth state, e.g. in the context of unit tests".

Alternatively / in addition, we can add `withr`-esque helpers `with_bq_auth()` / `local_bq_auth()`; users can run these without having to concern themselves with details about what resetting state entails.

**Comment by jennybc** [comment]
I don't see obvious improvements here that are both accurate and not opening a can of worms I don't want to open in the bigrquery docs.

So I'm going to just answer your specific question. So far I haven't exported these sort of with/local helpers in gargle-using packages and really "guaranteed" them for external use. It is not a common use case. But if it helps, here's an internal example that use in the googlesheets4 tests:

https://github.com/tidyverse/googlesheets4/blob/849f2b8ae116304cf226070750fc716900a3510d/R/gs4_auth.R#L313-L329
