### ISSUE TITLE
bq_table_upload not working as expected with dispositions to overwrite

### ISSUE THREAD

**Issue by casbolwerk** [r-dbi/bigrquery#525]
Maybe I misunderstand how BigQuery is meant to work, but if you would define a `bq_table_upload` call with a `create_disposition='CREATE_IF_NEEDED'` and a `write_disposition='WRITE_TRUNCATE'`, I would expect the statement to always write to the table no matter what is already existing there. But as of right now, `WRITE_TRUNCATE` only applies to the values in the table and not the table's schema.

If the table already exists in BigQuery (with columns A, B and C) and new values are uploaded where (in this example) the C column is missing, the table schema still mentions C, but now it has null values. If we add another column `test`, the code errors out completely, stating `Error while reading data, error message: JSON parsing error in row starting at position 0: No such field: test. [invalid]`. I would expect a statement with these dispositions to overwrite a table, no matter what is in it. Let me know if this behaviour is as intended!

```r
library(bigrquery)

service_account <- "service_account.json"
# authenticate bigquery
bq_auth(path = service_account)

PROJECT_ID <- "project"
DATASET_ID <- "dataset"
TABLE_ID <- "test"

data = tibble(
  A = 1:3,
  B = sqrt(1:3),
  C = letters[1:3]
)
data$test <- data$A * data$B

bq_table <- bq_table(project = PROJECT_ID, dataset = DATASET_ID, table = TABLE_ID)
bq_table_upload(x=bq_table, values=data, create_disposition='CREATE_IF_NEEDED', write_disposition='WRITE_TRUNCATE')
```

**Comment by hadley** [comment]
This sounds like a question about the bigquery API, not bigrquery, since we just forward these parameters on to the API.
