### ISSUE TITLE
bq_job_wait signals errors when a jobs.get call return a 503

### ISSUE THREAD

**Issue by meztez** [r-dbi/bigrquery#535]
Sometimes, not always, it takes a couple seconds for BigQuery to register a job.

If you poll the jobs.get endpoint too fast, you might receive a 503 http status with a backendError, which is normal per https://cloud.google.com/bigquery/docs/error-messages.

The `bq_job_wait` method is supposed to loop until the job is done or fails.
Since the first call to the endpoint resulted in a 503, it ends up aborting.
It does not get to the while loop.

```
bq_job_wait > bq_job_status > bq_job_meta > bq_get > process_request > bq_check_response (503) > signal_reason > abort
```

I'm unsure about the best way to address this issue.

Google suggest waiting a few seconds before retrying to pool the jobs.get api.
I'm thinking of adding a single conditional 2 seconds sleep on 503 to the jobs.get API.
It feels kinda hacky.

Would you have an opinion on the best way to resolve this?

**Comment by meztez** [comment]
This code has been in production for 2 months. The issue was not seen since.

**Comment by hadley** [comment]
I think it might be slightly cleaner to catch and recover from the 503 error in `bq_job_wait()`. Alternatively maybe we should generally retry on a 500/503 as the docs suggest.
