### ISSUE TITLE
`dbWriteTable()` doesn't work with Id objects

### ISSUE THREAD

**Issue by mgirlich** [r-dbi/bigrquery#537]
From https://github.com/darwin-eu/CDMConnector/pull/6#issuecomment-1610049391

<details>
> @mgirlich Also I noticed the bigrquery uses "." to separate catalog, schema, and table components.
> 
> https://github.com/r-dbi/bigrquery/blob/9bd1425171ccc9897a8992ac8de56abd64274196/R/dbi-connection.R#L306
> 
> Using DBI::Id does not work.
> 
> ```r
> bigrquery::bq_auth(path = Sys.getenv("BIGQUERY_SERVICE_ACCOUNT_JSON_PATH"))
> 
> con <- DBI::dbConnect(
>   bigrquery::bigquery(),
>   project = Sys.getenv("BIGQUERY_PROJECT_ID"),
>   dataset = Sys.getenv("BIGQUERY_CDM_SCHEMA")
> )
> 
> # does not work
> DBI::dbWriteTable(con, DBI::Id(schema = "scratch", table = "temp_test"), cars, overwrite = TRUE)
> #> Error in `signal_reason()`:
> #> ! Not found: Dataset ohdsi-276919:`scratch` [notFound] 
> #> Backtrace:
> #>      ▆
> #>   1. ├─DBI::dbWriteTable(...)
> #>   2. └─DBI::dbWriteTable(...)
> #>   3.   ├─DBI::dbWriteTable(...)
> #>   4.   └─bigrquery::dbWriteTable(...)
> #>   5.     └─bigrquery (local) .local(conn, name, value, ...)
> #>   6.       └─bigrquery::bq_table_upload(...)
> #>   7.         └─bigrquery::bq_perform_upload(x, values, ...)
> #>   8.           └─bigrquery:::bq_upload(...)
> #>   9.             └─bigrquery:::process_request(req)
> #>  10.               └─bigrquery:::bq_check_response(status, type, content)
> #>  11.                 └─bigrquery:::signal_reason(json$error$errors[[1L]]$reason, json$error$message)
> #>  12.                   └─rlang::abort(message, class = paste0("bigrquery_", reason))
> 
> # works
> DBI::dbWriteTable(con, "scratch.temp_test", cars, overwrite = TRUE)
</details>

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(bigrquery)
options(gargle_oauth_email = TRUE)

con <- DBI::dbConnect(bigrquery::bigquery(), project = bq_test_project())
ds <- bq_test_dataset()
#> ℹ The bigrquery package is using a cached token for 'hadley@posit.co'.

dbWriteTable(con, paste0(ds$dataset, ".mtcars1"), mtcars)
dbWriteTable(con, DBI::Id(schema = ds$dataset, table = "mtcars2"), mtcars)
#> Error in `signal_reason()` at bigrquery/R/bq-request.R:191:5:
#> ! Not found: Dataset gargle-169921:`TESTING_ifyotkakkv` [notFound] 
```

<sup>Created on 2023-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
