### ISSUE TITLE
tbl() breaking when used with dbConnect - again?

### ISSUE THREAD

**Issue by evanrollinsdrumline** [r-dbi/bigrquery#593]
We've been building workflows using bigrquery for data queries, uploads and downloads. All has worked fine this year for hundreds of uses until today when I had to uninstall and reinstall R and all packages - now I get the following error during the very basic dbConnect and query process.

Is this related to the [same issue raised last year](https://github.com/r-dbi/bigrquery/issues/492)? 

```
#BQ connection
  bq_con <- dbConnect(bigrquery::bigquery(),
                      project  = "a-bq-project",
                      dataset = "a_bq_dataset",
                      max_connections = 3L)
  
  #create table object
  bq_nb <- dplyr::tbl(bq_con, "a_simple_table")
```

Then when executed:
`Error in strsplit(name, ".", fixed = TRUE) : non-character argument`

Current packages are all freshly installed and up to date - 
bigrquery 1.4.2
dplyr 1.1.4

**Comment by hadley** [comment]
Closing this since I'm about to start the release process.
