### ISSUE TITLE
`dbplyr::table_path_components()` fails to parse components as table name is enclosed with backticks 

### ISSUE THREAD

**Issue by mcanouil** [r-dbi/bigrquery#605]
I am working on multiple datasets and tables, which involve join queries so I need to set the dataset to NULL in the connection and set it as the table name using the syntax: `dataset.table`.
The SQL query generated is correct (via `dbplyr::sql_render()`), but the "preview" via `dplyr` cannot be displayed when in such setup.

See below, an example of code to reproduce the error and the full stack trace:
(I kept from my real case the same "syntax" for the project, dataset, and table, such as underscores, upper case, etc.)

```r
library(bigrquery)
library(dplyr)
bq_con <- src_bigquery(project = "my-project", dataset = NULL)
tbl(bq_con, "my_dataset.MYTABLE")
#> Error in `as_bq_table()`:
#> ! `name` ("`my_dataset.MYTABLE`") must have 2 or 3 components if the connection doesn't have a dataset.
#> Run `rlang::last_trace()` to see where the error occurred.
```

```r
rlang::last_trace(drop = FALSE)
#> <error/rlang_error>
#> Error in `as_bq_table()`:
#> ! `name` ("`my_dataset.MYTABLE`") must have 2 or 3 components if the connection doesn't have a dataset.
#> ---
#> Backtrace:
#>      ▆
#>   1. ├─base (local) `<fn>`(x)
#>   2. └─dbplyr:::print.tbl_sql(x)
#>   3.   ├─dbplyr:::cat_line(format(x, ..., n = n, width = width, n_extra = n_extra))
#>   4.   │ ├─base::cat(paste0(..., "\n"), sep = "")
#>   5.   │ └─base::paste0(..., "\n")
#>   6.   ├─base::format(x, ..., n = n, width = width, n_extra = n_extra)
#>   7.   └─pillar:::format.tbl(x, ..., n = n, width = width, n_extra = n_extra)
#>   8.     └─pillar:::format_tbl(...)
#>   9.       └─pillar::tbl_format_setup(...)
#>  10.         ├─pillar:::tbl_format_setup_dispatch(...)
#>  11.         └─pillar:::tbl_format_setup.tbl(...)
#>  12.           └─pillar:::df_head(x, n + 1)
#>  13.             ├─base::as.data.frame(head(x, n))
#>  14.             └─dbplyr:::as.data.frame.tbl_sql(head(x, n))
#>  15.               ├─base::as.data.frame(collect(x, n = n))
#>  16.               ├─dplyr::collect(x, n = n)
#>  17.               └─bigrquery:::collect.tbl_BigQueryConnection(x, n = n) at dplyr/R/compute-collect.R:51:3
#>  18.                 ├─bigrquery::as_bq_table(con, name)
#>  19.                 └─bigrquery:::as_bq_table.BigQueryConnection(con, name)
#>  20.                   └─cli::cli_abort("{.arg name} ({.str {name}}) must have 2 or 3 components if the connection doesn't have a dataset.")
#>  21.                     └─rlang::abort(...)
```

**Comment by mcanouil** [comment]
It seems the issue is the following because of the backticks.

- https://github.com/r-dbi/bigrquery/blob/1056d8bc109d55a41e7e53c4a99b0ed613271c87/R/dbi-connection.R#L464

The above line of code where "name" is ``<table_path> `my_dataset.MYTABLE` `` returns `my_dataset.MYTABLE`

The backticks directly comes from `lq <- tbl(bq_con, "my_dataset.MYTABLE")$lazy_query`.

I am not sure what would be the best fix here but I would be include to keep the backticks and ensure `dbplyr::table_path_components` can handle them in this case.

**Comment by mcanouil** [comment]
Seems related to https://github.com/tidyverse/dbplyr/issues/1453

**Comment by mcanouil** [comment]
Maybe the issue should be solved directly in `dbplyr`.

**Comment by hadley** [comment]
I think `I()` is the solution: https://www.tidyverse.org/blog/2024/04/dbplyr-2-5-0/

**Comment by mcanouil** [comment]
I missed that blog post.
Then the example should probably be be updated for <https://bigrquery.r-dbi.org/reference/src_bigquery.html>.
I could make a PR but I wouldn't be able test the example locally.
