### ISSUE TITLE
bigrquery::bq_auth() Doesn't work, Warning message: Unable to refresh token: invalid_grant Account has been deleted

### ISSUE THREAD

**Issue by benyamindsmith** [r-dbi/bigrquery#610]
I am trying to use the `bigrquery` package to read and write data to BigQuery. 

When I try to get started with  the `bq_auth()` function I get the following error: 
```r
> library(bigrquery)
> bq_auth()
Warning message:
Unable to refresh token: invalid_grant
Account has been deleted
```

Whats the issue here? Do I need to do anything which I missed in the docs?

**Comment by jennybc** [comment]
This would be pretty surprising as a very first `bq_auth()` experience, because ... what token is it trying to refresh? 🤔

Can you give any more details about the context?

**Comment by benyamindsmith** [comment]
@jennybc  just following up on this so that if someone else runs into the same issue they can see it here. 

This was the first time I installed `bigrquery` and I wanted to connect to bigquery in a manner that would be similar to how I usually experienced things with `googlesheets4`. 

As a workaround there are 2 approaches:

## Possible Workarounds
### 1. Making a token with `gargle`

```r
token<-gargle::credentials_user_oauth2(scopes="https://www.googleapis.com/auth/bigquery")
bigrquery::bq_auth(token = token)  
```

### 2.  Use service account credentials. 

Navigate in the GCP console to "IAM & Admin", add/select a relevant account and permissions. Generate an access key and run in R.

```r
bq_token <- gargle::credentials_service_account(
  path = "./data/service.json",
  scopes = "https://www.googleapis.com/auth/bigquery"
)
bigrquery::bq_auth(token=bq_token)
```

---

I find __2.__  a better solution for pipeline development as its more friendly to deal with in a Docker setting. 


Feel free to close the issue.

**Comment by jennybc** [comment]
I still don't understand what token the initial attempt was failing to refresh. But I can live with the mystery. The typical user can allow `bq_auth()` to "just work", i.e. it eventually calls the gargle functions shown above . But yes, the explicit token creation and use you show works. It just shouldn't be necessary, in general.

**Comment by JordanMPDS** [comment]
Perhaps for the OP, the system environment wasn't set.  I had a similar issue of a service account not working as expected and the workaround worked https://github.com/r-dbi/bigrquery/issues/610#issuecomment-2159708252 .  **But** the workaround isn't needed if the system environment is set such as:

`Sys.setenv(GOOGLE_APPLICATION_CREDENTIALS = json_path)`

I believe this may be what was missing from the OP, and at least it resolved my issue of not getting the service account working properly.
