### ISSUE TITLE
Error after first attempt to execute query when permissions have been revoked

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/bigrquery#73]
https://github.com/hadley/httr/pull/315#issuecomment-170003813
- Initial state: Connection from bigrquery works, no service token set
- Revoke access via https://myaccount.google.com/security#connectedapps
  - I can still connect from bigrquery for a minute or so
- Eventually, I'm seeing the following as a result from query_exec():
  
  ```
  Auto-refreshing stale OAuth token.
  No encoding supplied: defaulting to UTF-8.
  Error: Invalid Credentials
  In addition: Warning message:
  Unable to refresh token 
  9: stop(out$err$message, call. = FALSE) at request.r#67
  8: process_request(req) at request.r#34
  7: bq_post(url, body) at jobs.r#60
  6: insert_query_job(query, project, destination_table = destination_table, 
         default_dataset = default_dataset) at query.r#32
  5: query_exec(sql, project = project) at oauth.R#5
  4: eval(expr, envir, enclos)
  3: eval(ei, envir)
  2: withVisible(eval(ei, envir))
  1: source("~/git/R/bigrquery/oauth.R", echo = TRUE)
  ```
- The second call of query_exec() finally opens the authentication page in the browser

**Comment by hadley** [comment]
I'd say the minute delay is because it takes a while for the revocation to trickle through google's systems. Can you confirm @craigcitro?

Fixing the second problem probably needs more logic in `get_access_cred()` - I see there's a comment in it suggesting it's not complete.

**Comment by hadley** [comment]
Also it's not exported but you should be able use `httr:::revoke_oauth2.0()` to avoid the manual step

**Comment by hadley** [comment]
Maybe like this:

```R
bigquery_scope <- c(
  "https://www.googleapis.com/auth/bigquery",
  "https://www.googleapis.com/auth/cloud-platform"
)

get_access_cred <- function() {
  cred <- bq_env$access_cred
  if (is.null(cred)) {
    return(cred)
  }
  
  tryCatch(
    cred <- oauth2.0_token(google, bigqr, scope = bigquery_scope),
    error = function(e) {
      set_access_cred(NULL)
      stop(e)
    }
  )  
  # Stop if unsuccessful
  set_access_cred(cred)
}
```

**Comment by hadley** [comment]
I'm going to punt on this - this will eventually be resolved in gargle if we determine that it is still a problem.
